### ISSUE TITLE
Customization options in Style Settings

### ISSUE THREAD

**Issue by JigenDD** [Akifyss/obsidian-border#1]
Hi! Are there more customization options in the pipeline for this theme in Style Settings? I have to say, this is one of the finer, more thoughtfully implemented themes for Obsidian 1.0 thus far. In fact, as-is, I prefer it to minimal, which is quite the feat. The way roundness was implemented + the subtle interplay with translucency is quite the sight to behold and makes for very pleasant work sessions.  

I understand that you may prefer to keep things visually simple with this theme, BUT at the same time, I feel like a few (only a few) crucial customization options are missing:
- **Option for different heading sizes:** Having the option to easily increase the size difference between headers would be great
- **Option for different heading colors:** I know there's different colored underlines with a slight gradient differentiating headers, but after long hours typing, it becomes tiring to the eyes to differentiate them. If those same gradient colors were also applied to the header characters themselves, it would be way easier on the eyes. 
- **Option for separate heading fonts:** Self-explanatory. Would massively help in visually distinguishing between different sections of the text.
- **Option to individually change the colors for bold, italic, internal link, external link, tags:** This is one exceptional aspect where I think the user should be given a bit more freedom, as some accent colors *(which globally affect the entire theme -- a nice aesthetic decision I REALLY like)* make it harder for some pre-determined text colors to be seen. Dark red accent color makes bold visually hard to distinguish. Yellow accent color makes tags the same color as italic. What's more, some users may be very dependent on a specific type of text, and may need tags or italics to really pop. And pop with different colors.

Either way, congratulations in creating one of the better Obsidian themes out there

**Comment by Akifyss** [comment]
Thank you so much for the suggestions! I think these suggestions are really helpful and I will work on this later.

**Comment by JigenDD** [comment]
Thank you for considering them!

Oh and one more thing I forgot to mention above: I _think_ it would be visually more interesting (and prettier) to have the focused paragraph in light mode be a very light shade of the corresponding selected accent color, instead of a simple #f2f2f2 tone

**Comment by Akifyss** [comment]
More customization options have been added to Style Settings, which you can find in the "Editor" section. Please update the theme to have a try.
