### ISSUE TITLE
功能建议：希望大佬能增加对阴影调节的控制功能功能

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#10]
<img width="468" alt="image" src="https://user-images.githubusercontent.com/115944923/211181386-0658e80c-a499-48db-94d0-92f1e509ab3d.png">

如图所示，能够开关阴影和调节阴影（狗头）

**Comment by Akifyss** [comment]
已更新，可以在 “外观-自定义阴影” 里找到。需要自己填写[box-shadow](https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-shadow)值来调节。要关闭的话，直接填写空值就可以。

**Comment by miaoziguan** [comment]
<img width="279" alt="image" src="https://user-images.githubusercontent.com/115944923/211223882-7a70f567-90ab-426e-a535-11c0599b89e8.png">
试用了一下，非常nice，高定义的可玩空间又更近了一步，奥力给
