### ISSUE TITLE
Outline panel lags when moving a header around between other headers

### ISSUE THREAD

**Issue by RhymeRequiem** [Akifyss/obsidian-border#104]
I created a new vault, downloaded style settings, enabled it, and applied the Border theme to test this to see if it was just me. Here is a video demonstrating the issue: https://streamable.com/tbx0dy. I would upload the video to Github, but it seems to not upload properly when I do with how I'm recording or something, so I hope that'll suffice.

**Comment by Akifyss** [comment]
The new version has fixed this issue, you can update and give it a try.
