### ISSUE TITLE
使用memo插件时会出现卡顿

### ISSUE THREAD

**Issue by Amy-Liu-FW** [Akifyss/obsidian-border#105]
安装并使用border主题，导入Neumorphism预设主题，在使用memo插件时会出现卡顿。memo放置在侧边栏时尤其明显。

obsidian：1.3.7，1.4.9 1.4.13均有类似情况。
border：2023.09.24更新到最新版。
memos：1.9.7

**Comment by Akifyss** [comment]
主题并没有对memos插件进行处理，卡顿问题应该和主题本身的性能问题有关。
而主题的性能问题目前应该只能通过手动移除一些（性能占用高的）功能的代码来实现，因此，如果你不用这些功能的话可以考虑手动删除这些代码来提高主题的性能：
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/f81b8412-f71b-4e0a-9ca2-dfa07915f309)
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/21458750-8bfd-4c12-b182-9cfe0d278c2e)
