### ISSUE TITLE
请问可不可以添加 callout 块的设置呢？我在 style setting 插件里面没有找到哎

### ISSUE THREAD

**Issue by CMD-cmd** [Akifyss/obsidian-border#106]

**Comment by Akifyss** [comment]
目前主题没有对callout 块进行修改，所以也就没有相关的设置。想了解你是需要 callout 块的哪方面的设置？

**Comment by CMD-cmd** [comment]
就是比如 callout 块颜色的透明度呀，边框粗细呀这些。还有就是样式，比如框线或者全底色这种的

**Comment by Akifyss** [comment]
新版已添加，可以在“editor-标注”处调整设置
