### ISSUE TITLE
Plugin hide animations bug

### ISSUE THREAD

**Issue by oyes77** [Akifyss/obsidian-border#107]
https://github.com/olrenso/obsidian-home-tab
When using this plugin, the hide animations don't work unless you change the theme to light/dark mode, and if you go back to the homepage the animations stop working back, stuff started working back when I turned off the plugin and restarted obsidian

**Comment by Akifyss** [comment]
What "hidden animations"? Is there any video or image? Sorry, I didn't quite understand what you meant.

**Comment by oyes77** [comment]
The plugin aniamtions didn't work sometimes, I tested further and that was the case with other themes with "interface hiding" animations, so I think it has to do with plugin or css snippets conflicts, it seems to be fixed now, or doesn't happen nearly as often
