### ISSUE TITLE
关于DB Folder 表格样式的小问题

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#11]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/115944923/211224059-81ea19be-5399-43b3-a2a7-d1105ee09c48.png">
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/115944923/211224124-89b03314-55db-44ee-b7fe-7085cbf106c2.png">

在白天模式下DB Folder表格呈现交替色彩网格，视觉效果没有统一的好，大佬看看能否增加一个选项统一表格的色彩。

**Comment by Akifyss** [comment]
添加了一个开关，在“插件-DBFolder”里，需要手动开启

**Comment by miaoziguan** [comment]
大佬神速，再次感谢🙏。
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/115944923/211253116-01274c95-79b6-40f9-a6df-0fbb960d2b72.png">
如图所示，就是还是会有部份颜色不够统一😭，影响美观感

**Comment by Akifyss** [comment]
刚刚修复了，再更新试试

**Comment by miaoziguan** [comment]
暗模式是OK的，亮模式又出现间隔条了？
如图
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/115944923/211275693-a270f4a9-fda2-4922-b758-93395315d0ce.png">

**Comment by Akifyss** [comment]
这个应当是改了自定义颜色的缘故，按照默认的颜色应该是正常的。新版本把颜色都改为透明了，再试试看有没有问题

**Comment by miaoziguan** [comment]
完美解决，感谢大佬🙏
