### ISSUE TITLE
Heading divider using Style Settings plugin not working correctly

### ISSUE THREAD

**Issue by ha1kron** [Akifyss/obsidian-border#111]
The heading divider changes to a different place when viewed from the reading mode. I have attached a video of that happening. I have the latest version of Border Theme and Style Settings as of now.

[Screencast from 2023-10-20 09-45-45.webm](https://github.com/Akifyss/obsidian-border/assets/77142658/49dddc54-9b5b-4e11-9e7c-89df3fa29d75)

**Comment by Akifyss** [comment]
This is strange. This feature shows fine in my environment:
I don't know why for now, could you please try it again in a sandbox environment?

![1](https://github.com/Akifyss/obsidian-border/assets/23567154/abd0dacf-141f-47c7-8f1a-e766cb2d621a)

**Comment by ha1kron** [comment]
Could you try this one?
I think it only happens when you include Callouts.

```
# Header 1
> [!info]
>> [!warning]
>> This is a warning
>
## Smaller Header
> [!school]
>> [!reading]
>> To read

# Header 2
> [!audio]
>> [!example]
>> Rock music
```

**Comment by Akifyss** [comment]
I just tried it and these texts behave normally in my environment, have you tried it in a sandbox environment? How do these texts behave in a sandbox environment?
![1](https://github.com/Akifyss/obsidian-border/assets/23567154/e6ed278f-b14d-46ca-aebc-462283eaaf29)
