### ISSUE TITLE
请问引用和代码区域的网格背景可以修改吗

### ISSUE THREAD

**Issue by PupupupuTong** [Akifyss/obsidian-border#114]
就是这种，感觉有点影响阅读

![image](https://github.com/Akifyss/obsidian-border/assets/69069739/4c39481d-e30b-4494-81bc-97c27e9ecc3a)

**Comment by Akifyss** [comment]
可以在这里修改
<img width="799" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23567154/da6f394c-0a02-45c2-9d16-7c42df0cc038">

**Comment by PupupupuTong** [comment]
原来引用也归在代码块设置里了呀，感谢！
