### ISSUE TITLE
请问能否使阅读模式下图片也保持居中？

### ISSUE THREAD

**Issue by PupupupuTong** [Akifyss/obsidian-border#115]
![image](https://github.com/Akifyss/obsidian-border/assets/69069739/0c65d357-9962-4282-b824-b6877ef08fa9)

这个设置项似乎仅在编辑模式下生效

**Comment by Akifyss** [comment]
新版已修复，可以更新试试

**Comment by PupupupuTong** [comment]
好了，感谢大大！
