### ISSUE TITLE
能否增加修改标题前后间隔的方式，有观察到阅读模式下标题后边距有变化

### ISSUE THREAD

**Issue by yx1024** [Akifyss/obsidian-border#117]
在代码中有看到
`bottom: calc(var(--font-text-size) * var(--line-height-normal) * 0.2 - var(--size-2-1));`
能否设置在编辑模式下也保持类似的设计，所见即所得的同时也不用打出多余的换行，也能在修改段落间距的同时提升整体编辑阅读体验
我已使用`margin-bottom: 1em;`进行自定义尝试，但仍然希望有更方便快捷的途径

谢谢作者，真的很喜欢这个主题~

**Comment by Akifyss** [comment]
这行代码实际上是用来创建标题分割线的，能否提供一些额外的信息或图片来描述效果

**Comment by yx1024** [comment]
问题是这样的，现在主要是**通过换行来达到标题与正文之间的间距，正文段落之间的间隔**，但多余的换行总是不必要的，想要达到类似word中段前段后距离控制的类似效果，如图所示
![image](https://github.com/Akifyss/obsidian-border/assets/56633531/150d2b2e-386e-43dd-95c2-bb58aab30745)
**但现有控制行高并不能实现标题后距离的控制，与正文的距离太近**，如图是不加空格的效果
![image](https://github.com/Akifyss/obsidian-border/assets/56633531/e7c82c68-92b7-42e5-b04f-bd9511dd8ab0)

现有的解决策略我有看到两个，我测试使用的margin去控制会有一些问题，所以pass；
一个是控制格式，同时控制标题与正文之间的空行，进行格式化，比如**插件Linter**，以下是配置项
![image](https://github.com/Akifyss/obsidian-border/assets/56633531/fa4ca2ae-7eac-43c2-9256-061e3f23f775)
> 对于标题的控制项

![image](https://github.com/Akifyss/obsidian-border/assets/56633531/3226f205-0d30-43f7-ac6f-0f4cf8656ebc)
> 对于段落的控制项


虽然可以达到快速控制，但也有一些word类似软件的使用经历，仍然还是觉得不加多余的控制编辑会更干净清爽，类似这样
![image](https://github.com/Akifyss/obsidian-border/assets/56633531/2785ba16-20b1-414a-97e6-3f22be4e3eed)

还有一个是查到的**使用padding**解决，但需要在源代码中修改，目前测试下来会存在一些问题，但是是一个可能有效的解决办法，希望能给专业人士一点启发：[padding修改段间距](https://rjiazhen.top/Obsidian%E4%B8%AD%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%96%E8%BE%91%E6%A8%A1%E5%BC%8F%E7%9A%84%E6%AE%B5%E9%97%B4%E8%B7%9D)

虽然不算一个必须解决的问题，但对于强迫症本人来说会帮大忙，感谢作者关注~

**Comment by yx1024** [comment]
> 这个代码片段应该可以在style setting中调节编辑模式下的段间距。只是行高亮这个功能和这个片段是冲突的，推荐关掉行高亮这个功能或者搭配其他主题使用 [Paragraph spacing.zip](https://github.com/Akifyss/obsidian-border/files/13189924/Paragraph.spacing.zip)

谢谢回复~才有空解决这个问题，不过试了一下引用格式下的应用效果不好（因为有设置底色所以padding不太适用），还是在开发者模式用margin去处理了，基本达到预期了
![image](https://github.com/Akifyss/obsidian-border/assets/56633531/bb50c430-9941-4b75-89fd-d3ceb48d928d)
