### ISSUE TITLE
Use this snippet for the Kanban plugin

### ISSUE THREAD

**Issue by oyes77** [Akifyss/obsidian-border#118]
https://forum.obsidian.md/t/kanban-plugin-redesign-a-css-snippet/50362

**Comment by Akifyss** [comment]
While I appreciate the recommendation, it seems that the snippet can be directly used without having to copy it into my theme. However, I may have misunderstood your intentions, and I apologize if that's the case.

**Comment by oyes77** [comment]
The snippet can be used but doesn't use the theme colors, sorry for my lack of explanation
