### ISSUE TITLE
页面宽幅显示和文件名称的请求

### ISSUE THREAD

**Issue by minilulubai** [Akifyss/obsidian-border#119]
作者，
       你好，
       非常感谢你为obsidian的用户提供如此精美的主题。
       我目前使用dataview插件，设计个人书架页面时，发现无法全宽显示表格、列表、callouts、段落等。
      1、不知道后期是否有计划实现支持？
      2、对于较长的文件名，不做换行处理，而选择展示一部分；鼠标悬浮其上，展示全称，是否可行呢? 
      谢谢。

    (ps.通过style settings 设置过表格表格宽度 像素值。但效果不明显)

    目前情况如下：
    ![表格和文本块宽幅显示](https://github.com/Akifyss/obsidian-border/assets/7126461/c16b14b7-52cc-4622-8b14-eb64eb4ddff6)

    希望如下：
    ![希望](https://github.com/Akifyss/obsidian-border/assets/7126461/33b22ed5-97a2-4641-ab9e-c12e3d8b16c1)

    文件名过长的情况:
    ![文字](https://github.com/Akifyss/obsidian-border/assets/7126461/5dafce7f-7316-4464-a1f0-94dabb18b9bf)

**Comment by Akifyss** [comment]
对于第一个问题，你可以调整“段落行宽”来让页面宽幅显示：
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/fb465b55-1123-408b-ab09-7eb0f5111766)
对于第二个问题，之前尝试过你说的方案，之前尝试做过，但是效果并不理想，还会和主题的其他部分起冲突，目前还不会支持
