### ISSUE TITLE
Issue with Lightdown-Green

### ISSUE THREAD

**Issue by WinnerWind** [Akifyss/obsidian-border#122]
![image](https://github.com/Akifyss/obsidian-border/assets/71366717/14496e81-39b6-4158-8edd-944fdfb3ebef)
Notice how the tab bar text is barely readable. I was unable to fix this using style settings, so it could be something to do with the background. A simple fix is to make the background darker.

**Comment by Akifyss** [comment]
You can consider changing this section of options to create enough contrast with the background:

![image](https://github.com/Akifyss/obsidian-border/assets/23567154/a92c467d-2eb6-4e59-9d5a-1a5f3a181cd3)
