### ISSUE TITLE
Support for visual Markdown Table editor (v1.5) is broken

### ISSUE THREAD

**Issue by imgradeone** [Akifyss/obsidian-border#124]
Obsidian v1.5 introduced a new visual Markdown Table editor, but some behaviors like Drag & Drop handle are broken on Border theme (version 1.5.8 with Obsidian 1.5.0).

Obsidian Default theme (video file):
https://github.com/Akifyss/obsidian-border/assets/30969327/b2280ba6-533f-4bd4-a8c0-6f4b0d0d0f78

Border theme (video file):
https://github.com/Akifyss/obsidian-border/assets/30969327/5ee2c9c9-0897-45ad-84a6-5aa363f78cb0

**Comment by Akifyss** [comment]
The new version has fixed this issue, you can update and give it a try.
