### ISSUE TITLE
建议：标题分隔线的位置能否下调少许？

### ISSUE THREAD

**Issue by PupupupuTong** [Akifyss/obsidian-border#126]
汉字字符比英文字符大些，高级标题如果较长分隔线会和字底部重合

![image](https://github.com/Akifyss/obsidian-border/assets/69069739/70fc0424-0306-4192-afcc-cb3ea18cf922)

**Comment by Akifyss** [comment]
新版已调整，可以更新试试

**Comment by Akifyss** [comment]
已经降到每一行的最底部了，再下调就得是负数了，可能会和下一行的字粘在一块。不过我也还没试，你可以手动调一调这几行看看效果
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/c90d4bd2-8666-4692-8d51-643a5b185b91)

**Comment by Akifyss** [comment]
可以在“设置-外观-css代码片段” 添加这些代码，调高标题的行高
```CSS
--h1-line-height: 1.5;
--h2-line-height: 1.5;
--h3-line-height: 1.5; 
--h4-line-height: 1.5;
--h5-line-height: 1.5; 
--h6-line-height: 1.5; 
```

**Comment by PupupupuTong** [comment]
非常感谢(｡◕◡◕｡)ﾉ效果很棒
