### ISSUE TITLE
建议：能否提供一个表格线条的开关

### ISSUE THREAD

**Issue by Morganwan90** [Akifyss/obsidian-border#127]
目前表格完全没有横竖线条，能否提供一个开关允许显示或隐藏线条。

**Comment by Akifyss** [comment]
你好，请问有相关的图片吗？目前有些不太理解

**Comment by Morganwan90** [comment]
> 你好，请问有相关的图片吗？目前有些不太理解

抱歉，我又看了一下，我的问题是一个snippets造成的。 我关了这个建议了哈
