### ISSUE TITLE
一个新的想法💡：给卡片模式下加描边

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#13]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/115944923/211224709-4f576e3e-c8c1-4a42-a2bb-c6582494d86a.png">

大意如图所示，犹如美女穿黑丝，斯文败类风格boy带金边眼镜👓（狗头）

**Comment by Akifyss** [comment]
描边可以通过“自定义阴影”选项实现，比如输入0px 0px 0px 1px gold。
如果想要在描边的基础下为卡片添加阴影，可以在上面的基础上添加一个逗号继续填写阴影值，比如输入0px 0px 0px 1px gold, 0px 0px 6px black。
更多的box-shadow语法可以查看[MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-shadow)

**Comment by miaoziguan** [comment]
好的，感谢大佬解惑
