### ISSUE TITLE
Hello! Does Awesome Theme support...

### ISSUE THREAD

**Issue by zhouxinghong** [Akifyss/obsidian-border#130]
Hello!
Does this theme support VSCode installations?
It would be great if you could install this theme in VSCode! 👍😜

**Comment by Akifyss** [comment]
Apologies, but currently there is no version for VSCode. Themes for VSCode are primarily focused on color schemes. Unfortunately, the color scheme of this  theme is not good and is not well-suited for VSCode. There are no plans to create a version for it at this time.
