### ISSUE TITLE
Main window background settings not working (Transparency/rgba)

### ISSUE THREAD

**Issue by TUp1** [Akifyss/obsidian-border#132]
Hello,
I tried using the [Glassmorphism](https://github.com/Akifyss/obsidian-border/blob/main/presets/Glassmorphism.json) theme, however the main window remains the default colour. 
I tried changing style settings and applying "customize CSS" in the Middle Pane Background option under Dark mode settings, but that doesn't take effect either. 
Transparency in "Appearance settings" is switched on and I have tried other modes in Dark Mode Settings for the main window, however the rgba value doesn't work. All border themes with transparent main windows give me the same issue. 
Any suggestions on what else I could try? 
cheers,
L

Settings I have enabled:
![image](https://github.com/Akifyss/obsidian-border/assets/26164890/65fe7b47-676a-46fa-8e42-f8d51509d944)

The left sidepane applies the selected background settings correctly, but the middle pane doesn't. 
![image](https://github.com/Akifyss/obsidian-border/assets/26164890/cc4d7e10-6534-4cef-9198-c5996bdfc5e4)

**Comment by Akifyss** [comment]
Sorry, but custom CSS is not permitted in stack mode. Allowing custom styles could result in overlapping tabs with transparent backgrounds, which would significantly hinder readability. Disabling stack mode should restore normal functionality.
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/e94f010e-a45f-4086-b115-d33f4126b22d)
