### ISSUE TITLE
【报错】通过image captions插件设置的图片注释文字上半部会被遮挡且图片会不再居中

### ISSUE THREAD

**Issue by PupupupuTong** [Akifyss/obsidian-border#134]
如图

![image](https://github.com/Akifyss/obsidian-border/assets/69069739/a82c0c12-f847-4d21-bef6-a579e6fbfc11)

用ob简化的引用格式也会出现这个情况，其他主题没有这样

**Comment by Akifyss** [comment]
抱歉，这个插件在我这里（默认主题下）不起作用，因此无法调试和定位问题

![image](https://github.com/Akifyss/obsidian-border/assets/23567154/4aeb2c0f-bc2a-4264-95b6-b4f47afe5ce1)
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/4dcaf8af-7ee5-4977-bcc2-15a5b3a6748f)

**Comment by PupupupuTong** [comment]
奇怪了，不应该啊，我这里默认主题下是正常的

![image](https://github.com/Akifyss/obsidian-border/assets/69069739/bb898159-27f1-4210-b100-f7d69fd727a5)
![image](https://github.com/Akifyss/obsidian-border/assets/69069739/3536d46c-7963-4067-8b14-fb63913745a2)

**Comment by PupupupuTong** [comment]
试了下，不开这个插件字也是会被遮挡的

默认主题：
![image](https://github.com/Akifyss/obsidian-border/assets/69069739/4737be79-36d5-4268-b44e-bd6c17040952)

Border：

![image](https://github.com/Akifyss/obsidian-border/assets/69069739/c315b02c-d3e7-49b8-a8b8-c3e26e598410)

**Comment by Akifyss** [comment]
下面的字是怎么加上去的？为什么我按照你的语法写没有出现下方的字
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/4a2e9675-02a8-40d8-9e46-e70ccd9f7600)

**Comment by PupupupuTong** [comment]
中邪了，我把image captions关掉之后它还会存在，再关有的时候会没有，有的时候还在。。。我装的图片相关的插件没几个，测试下来没发现其他的复现方法

**Comment by Akifyss** [comment]
刚刚看了image captions的[issues](https://github.com/bicarlsen/obsidian_image_caption/issues)，也有一些人和我情况一样，无法把captions弄出来。这种情况下实在修复不了，抱歉

**Comment by PupupupuTong** [comment]
看来是captions的bug了……（超小声）考虑把这个功能内置吗大大？看到有的主题好像可以（比如maple）

**Comment by Akifyss** [comment]
可以外挂这个片段，然后再style settings中打开设置
[img-alt.zip](https://github.com/Akifyss/obsidian-border/files/13628199/img-alt.zip)

**Comment by PupupupuTong** [comment]
Bravo！赞美大佬✿✿ヽ(°▽°)ノ✿
