### ISSUE TITLE
Border theme slow down obsidian

### ISSUE THREAD

**Issue by MelodyDuplaix** [Akifyss/obsidian-border#136]
I have been using obsidian for several months. For some time now, I have noticed that obsidian is getting slow, especially when searching and when I open an excalidraw note.
I did some experiments, by deactivating plugins and snippets one by one. I noticed in the end that it came from the theme. As soon as I put the theme back by default, I no longer have the performance problem at all.
Just in case, here's my configuration info:
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 17
	Restricted mode: off
	Plugins installed: 37
	Plugins enabled: 31
		1: Excalidraw v2.0.10
		2: Plugin Groups v2.1.0
		3: Dataview v0.5.64
		4: Metadata Menu v0.6.8-beta-3
		5: Settings Search v1.3.10
		6: Tasks v5.3.0
		7: Templater v1.18.3
		8: Global Hotkeys v0.1.2
		9: QuickAdd v1.6.1
		10: Tray v0.3.5
		11: Auto Note Mover v1.2.0
		12: Hider v1.3.1
		13: Commander v0.5.1
		14: Google Calendar v1.10.14
		15: Imgur Plugin v2.4.0
		16: ReadItLater v0.4.0
		17: Code Editor Shortcuts v1.14.0
		18: Better Search Views v0.2.2
		19: Advanced Tables v0.19.1
		20: Natural Language Dates v0.6.2
		21: Number Headings v1.16.0
		22: Obsidian Columns v1.5.2
		23: Surfing v0.9.1
		24: Advanced URI v1.38.1
		25: BRAT v0.8.2
		26: Code Styler v1.1.4
		27: Style Settings v1.0.7
		28: Paste image rename v1.6.1
		29: Game Search v0.1.8
		30: Run v1.0.8
		31: Colored Tags Wrangler v0.15.0

**Comment by Akifyss** [comment]
Sorry, to address the performance issue with this theme, you can only manually remove some code, such as the "hover line indicator" and "autohide" sections.
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/974db61a-f830-4326-8d96-54b693529dbf)
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/a5f2d49a-abce-4099-bce5-06377de1246e)
