### ISSUE TITLE
大佬 怎么设置文件夹，文件前面的 icon？和展示的 icon 不一样呢

### ISSUE THREAD

**Issue by leohooho** [Akifyss/obsidian-border#137]
![image](https://github.com/Akifyss/obsidian-border/assets/151621009/a2328b39-0be3-4a8b-9879-002bb465ef62)  

和 README上展示 icon 不一样

**Comment by Akifyss** [comment]
抱歉，README上图标是旧版的，现在已经被新版图标替换了🥹。后面我看看能不能再加上
