### ISSUE TITLE
Button space with pinned tab on left panel

### ISSUE THREAD

**Issue by wsouto** [Akifyss/obsidian-border#14]
First, this is a great theme and I am liking it very much.

I spotted a minor layout problem that I'm unsure how to explain, so I took a couple of screenshots.

This is with the default theme:
![Sem título-2023-01-08-2305](https://user-images.githubusercontent.com/357932/211231588-c29d68c8-228b-4ab2-9a77-0f0d593c5688.png)

And that with Border theme:
![Sem título-2023-01-08-2303](https://user-images.githubusercontent.com/357932/211231641-d4a8f086-4ba0-4b5b-b398-eb5803fa9bf6.png)

Let me know if you need more information or if I can do something to help.

**Comment by Akifyss** [comment]
This bug has been fixed, please update and have a check.

**Comment by wsouto** [comment]
Nice! It's ok now. Thanks.
