### ISSUE TITLE
支持选择不同的代码显示风格

### ISSUE THREAD

**Issue by karterotte** [Akifyss/obsidian-border#141]
![image](https://github.com/Akifyss/obsidian-border/assets/9114743/ae9233bf-8f65-42cc-b3bc-c63ffcd58e91)
比如这种，可以切换不同的颜色？

**Comment by Akifyss** [comment]
这个不错，之后会考虑的。目前暂时可以考虑通过style settings手动修改这个地方的颜色
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/322ef30d-1f39-4d3d-8aba-53ebd63c6cc5)

**Comment by Akifyss** [comment]
新版已添加
