### ISSUE TITLE
Calendar plugin layout

### ISSUE THREAD

**Issue by shawnyeager** [Akifyss/obsidian-border#142]
The Calendar plugin layout is shifted as compared to other themes. Shown first is Border. Second, for contrast, is Minimal.

![image](https://github.com/Akifyss/obsidian-border/assets/980297/51eef528-32b5-4322-bbce-5b88479135e6)

![image](https://github.com/Akifyss/obsidian-border/assets/980297/c02aed56-1bc9-41c2-8b8a-97297e3a1355)

**Comment by Akifyss** [comment]
The new version has fixed this issue, you can update and give it a try.

**Comment by shawnyeager** [comment]
Looks good. Thanks for the fast fix.
