### ISSUE TITLE
Unexpected vault name with plugin Hider hiding vault name

### ISSUE THREAD

**Issue by shindgewongxj** [Akifyss/obsidian-border#145]
<img width="1440" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/59656935/08756524-8905-48f9-ab99-23b4292e7b84">

**Comment by Akifyss** [comment]
Compatibility measure for hider plugin will be improved later. Currently, you can hide the vault name through style settings：
<img width="818" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23567154/c3538ef0-a0ce-4d96-91f9-8dab30fcf0d8">
