### ISSUE TITLE
disable image zoom 

### ISSUE THREAD

**Issue by JINhuaqing** [Akifyss/obsidian-border#148]
你好，我是从minimal theme转过来的，它里面有一个功能是disable image zoom (ctrl+hold) ，就是点击图片不会放大。
不知道你们能不能也加上这个option，非常感谢。
因为这个image zoom和其他一些图片插件不兼容。

**Comment by Akifyss** [comment]
你可以在 style settings中的“编辑器-图片-关闭图像缩放”关闭这个功能
