### ISSUE TITLE
关于Checklist插件适配的需求

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#15]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/115944923/211694600-6484a6b2-a2d2-4d08-bbe7-ea6bd089b740.png">

如图所示，Checklist插件的自带样式没有对中文排版做优化，图标与文字的大小比例不是很精致。
相比之下，大佬对多彩文件夹的图标适配就很精致。
<img width="250" alt="image" src="https://user-images.githubusercontent.com/115944923/211695104-550cbb6a-95d4-49e6-a790-1570fc96c10e.png">

许愿对Checklist统一风格tong统一风格（狗头）

**Comment by miaoziguan** [comment]
🙏感谢大佬，第一时间更新了。
我一直在思考如何把Checklist打磨的更加符合[border]主题的设计理念。
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/115944923/212229576-630c0b8c-ad4b-401e-830f-1252dd0e90a9.png">
如图所示，Checklist这些条条框框其实很密集，去掉会更加清爽透彻
我的想法是和大佬的多彩文件夹一样，丰富和克制。
突然想到，Checklist也可像多彩文件夹一样给图标上色，丰满且克制。

**Comment by Akifyss** [comment]
条框之后应该会去掉的。“给图标上色” 的意思是给文本前面的圆圈上多种颜色吗

**Comment by miaoziguan** [comment]
对的，这样也比较符合border的整个设计调性（狗头）

**Comment by Akifyss** [comment]
新版已添加。可以在style settings里的 “插件-Checklist” 手动开启

**Comment by miaoziguan** [comment]
感谢大佬🙏，第一时间更新，效果非常nice
