### ISSUE TITLE
Edit mode loads slowly and flickers abnormally

### ISSUE THREAD

**Issue by ly5902534** [Akifyss/obsidian-border#150]
https://github.com/Akifyss/obsidian-border/assets/61930853/77835434-088c-407d-a2af-b74be10cbb4d

**Comment by Akifyss** [comment]
可以在一个沙箱里试试吗，我重来没有遇到过这种情况，因此猜测这可能和某个插件冲突了

Can you try it in a sandbox? I have never encountered this situation before, so I guess it may be conflicting with a certain plugin.
