### ISSUE TITLE
请问有无办法使行内插入的图片不单独一行显示？

### ISSUE THREAD

**Issue by PupupupuTong** [Akifyss/obsidian-border#151]
有些从外部导入的文本含有图片格式生僻字，例如这样

![image](https://github.com/Akifyss/obsidian-border/assets/69069739/d59e9fde-86b0-46fb-ac9d-a3a461010747)

单列一行视觉效果很诡异

**Comment by Akifyss** [comment]
是不是开启了图像居中功能，我这里是正常的

**Comment by PupupupuTong** [comment]
不开居中它也会另起一行

![image](https://github.com/Akifyss/obsidian-border/assets/69069739/c04cb857-aa5c-4717-8a99-05fc05f8fe38)

**Comment by PupupupuTong** [comment]
而且直接关掉图片居中那原本就单独成行的图片引用也无法居中显示了

**Comment by PupupupuTong** [comment]
理想的样式是把图片显示分成两种类型，举例来说就是

![image](https://github.com/Akifyss/obsidian-border/assets/69069739/ba58981b-60e8-49b6-878a-8af13bd2e717)

之前好像是用默认主题的时候无意中实现过行内显示图片的效果，但后面再改回默认又复现不了了，所有css都关掉也不行，不知道怎么回事。。。

**Comment by Akifyss** [comment]
我用的border主题可以做到，你是不是开了什么插件？
<img width="762" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23567154/269d4d45-aea9-43f6-8a4d-6a019a02ea0d">

**Comment by PupupupuTong** [comment]
哦，我知道了，是只有阅读模式不行，实时预览可以的

**Comment by PupupupuTong** [comment]
能让阅读模式也可以吗？含有大量生僻字的文档一般脚注也很多，几个脚注效果增强插件都只在阅读模式下才有用

**Comment by Akifyss** [comment]
我的两种模式都可以，是不是和什么插件冲突了
![1](https://github.com/Akifyss/obsidian-border/assets/23567154/73c71948-01a5-45b3-bf4b-55eba0c29429)

**Comment by PupupupuTong** [comment]
我把安全模式打开阅读视图也不可以。。。

**Comment by PupupupuTong** [comment]
开了一个全新的测试库，除了测试文件什么也没有，还是不可以

**Comment by Akifyss** [comment]
其他主题是正常的吗

**Comment by PupupupuTong** [comment]
试了八九个热门主题，好像都是这样，预览视图可以，阅读视图不行……所以大佬你是怎么做到的呀😭还是说我这个文档有毛病？

**Comment by Akifyss** [comment]
你的图片是内部的还是外部的

**Comment by PupupupuTong** [comment]
内部的附件

**Comment by Akifyss** [comment]
我也是内部的附件，也就是把图片贴进去而已。其他就不太清楚了，抱歉

**Comment by PupupupuTong** [comment]
我知道怎么回事了，引用语法的锅，`![]()` 不行，`![[]]` 就可以了

**Comment by Akifyss** [comment]
居然还有这种说法😲，不过我的好像确实都是第二种

**Comment by PupupupuTong** [comment]
谢谢大佬陪我浪费这么长时间🤣❤️

**Comment by PupupupuTong** [comment]
大佬，我参照你之前发给我的img-alt.css倒腾了一下，现在实现了仅单独成行的图片居中，但alt显示不出来，并且行内图片式子里只要有 `|`也会变居中，能请教下是怎么回事吗？以及该怎么改

```
/* @settings

name: image-alt
id: image-alt
settings:
    -
        id: image-alt
        title: add alt text below and center the image
        description: example ![[image.jpg|alt text]]
        title.zh: 在图片底部添加提示文本并居中图片
        description.zh: 样例 ![[图片.jpg|提示文本]]
        type: class-toggle
        default: true
*/

/* 提示文本，参考 https://github.com/chrisgrieser/shimmering-focus */
body.image-alt .view-content img[alt]:not([alt$=".png"], [alt$=".jpg"], [alt$=".jpeg"], [alt$=".tiff"], [alt$=".webp"], [alt$=".bmp"]) {
    display: block;
    margin: 0 auto;
}

body.image-alt .view-content img[alt]:not([alt$=".png"], [alt$=".jpg"], [alt$=".jpeg"], [alt$=".tiff"], [alt$=".webp"], [alt$=".bmp"])::after {
    content: attr(alt);
    display: block;
    text-align: center;
    margin-top: 1rem;
    margin-bottom: 1rem;
    font-size: var(--font-smaller);
    color: var(--text-faint);
}
```
