### ISSUE TITLE
Some UI Minor Improvements

### ISSUE THREAD

**Issue by shindgewongxj** [Akifyss/obsidian-border#152]
I have to admit that I am just an amateur design enthusiast, not a professional, and those are just based on my user experience:

![Untitled](https://github.com/Akifyss/obsidian-border/assets/59656935/6eb52539-d6ae-4f82-bd68-b81ade64a5e6)

**Comment by Akifyss** [comment]
For the "For side bar width..." issue, I didn't quite understand. Could you please provide more detailed information?？
For the "Apply leading alignment...?" issue, if you align the tab and content, the following situation will occur, which is not very aesthetically pleasing：
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/14f45fd6-ab41-432f-8111-84a66e5ee896)
For "Add some style..." issue, there is currently no plan to add it, sorry. However, you can customize it by adding the following code snippet.
```css
body:not(.is-mobile).workspace-tabs:not(.mod-stacked) .workspace-tab-header:not(.is-active) .workspace-tab-header-inner{
/*Add the style you want.*/}
```
For the "Bordered and trailing alignment?" issue, if you don't forcibly hide the sidebar button, there won't be this problem. May I ask if you have forced to hide the sidebar button? This issue will be addressed in the next update attempt.

**Comment by Akifyss** [comment]
The last issue has been fixed in the latest version. You can try updating it.

**Comment by shindgewongxj** [comment]
> The last issue has been fixed in the latest version. You can try updating it.

Sincere gratitude, and sorry for my unclear articulation!

Snapping Sidebar, which i mentioned is like a snap point for ideal width/height (show content fully avoiding scroll ?), like 

https://github.com/Akifyss/obsidian-border/assets/59656935/fbcfd82d-d994-41bc-9d99-0244105f1e97 

https://github.com/Akifyss/obsidian-border/assets/59656935/4ca89051-bf65-402c-9de3-f771c0688799

https://github.com/Akifyss/obsidian-border/assets/59656935/80121c21-f74f-434e-888e-871cb8ab6865

while in Border 

https://github.com/Akifyss/obsidian-border/assets/59656935/236d3bfc-c71e-4a83-b45c-8d2a11d220a8

Hope those can help

> For "Add some style..." issue, there is currently no plan to add it, sorry. However, you can customize it by adding the following code snippet.

Also a BIG THX for that!!!!!!!!

**Comment by Akifyss** [comment]
Thank you for your video demonstration, but I'm afraid this feature cannot be achieved with just a CSS theme due to the need to calculate the width of the icon bar. Sorry about that.
