### ISSUE TITLE
Page with Mermaid Digrams Loading Extremely Slowly

### ISSUE THREAD

**Issue by dvdmtw98** [Akifyss/obsidian-border#155]
I am a Markdown file that has a couple of Mermaid Diagrams. When I am using the Border theme it takes a very long time to load that file. Once the file loads it takes a few more minutes for Obsidian to go from Reading mode to Edit mode as well. This issue does not occur with any of the other Themes that I am using.

This seems to be a more specialized case of Issue #150

https://github.com/Akifyss/obsidian-border/assets/31100937/28363608-6c65-412f-acba-a065685195ff

The issue is present in the Sandbox Vault as well.

https://github.com/Akifyss/obsidian-border/assets/31100937/13a9ba2b-00d6-419f-b0ae-d757dd0815f2

File in which the issue is occurring for me: [mythos.md](https://github.com/Akifyss/obsidian-border/files/14056181/mythos.md)

**Comment by Akifyss** [comment]
This is strange, the difference between the boder theme (former) and the default theme (latter) is not too significant when I open this file:
![1](https://github.com/Akifyss/obsidian-border/assets/23567154/8317cc4d-f5c9-46c9-9446-cc4d53bf9f65)
![2](https://github.com/Akifyss/obsidian-border/assets/23567154/b5507067-1480-490e-a9fa-6870b8da3cea)

**Comment by dvdmtw98** [comment]
In my case with the default theme the file loads pretty much instantly (very small delay). 
But as seen in the above video with Borders its quite long and noticeable.

https://github.com/Akifyss/obsidian-border/assets/31100937/e126ecf0-60b9-4670-a03f-ff6920b9d520
