### ISSUE TITLE
求助实现 始终隐藏 左侧工具栏菜单

### ISSUE THREAD

**Issue by AsleepX** [Akifyss/obsidian-border#156]
尝试过用 hider 插件实现，但是会把边框整个隐藏变成以下样子
![image](https://github.com/Akifyss/obsidian-border/assets/129823735/b862060f-753a-4202-bda9-fb7d36f5c190)
在其他地方询问后并没有得到解答，不得不跑到这里来问了。

**Comment by Akifyss** [comment]
期望的效果是怎样的？是左侧有边框，并且鼠标hover上去是不会出现按钮的吗

**Comment by AsleepX** [comment]
> 期望的效果是怎样的？是左侧有边框，并且鼠标hover上去是不会出现按钮的吗

对的，就是一直隐藏不会触发，因为如果是自动隐藏的话，打开ob时，会有一个从打开到隐藏的动效，并且我并不会用到左侧工具栏，所以希望可以一直隐藏。

另外，非常感谢作者的辛苦付出，我真的很爱这个主题

**Comment by Akifyss** [comment]
打开自动隐藏，然后添加以下css代码片段试试？
```css
.workspace-ribbon {
  pointer-events: none;
}
```

**Comment by AsleepX** [comment]
> 打开自动隐藏，然后添加以下css代码片段试试？
> 
> ```css
> .workspace-ribbon {
>   pointer-events: none;
> }
> ```

使用时不会显现了，非常感谢。但是打开Ob时还是会有从打开到关闭的动效，我不确认是否有css或者其他方法可以实现左侧工具栏永远不会显现的功能。

**Comment by Akifyss** [comment]
这样有用吗？
```.workspace-ribbon {
    pointer-events: none;
    transition: none!important;

}

.workspace-ribbon >*{
    visibility: hidden;
}
```

**Comment by AsleepX** [comment]
> 这样有用吗？
> 
> ```css
> .workspace-ribbon {
>     pointer-events: none;
>     transition: none!important;
> 
> }
> 
> .workspace-ribbon >*{
>     visibility: hidden;
> }
> ```

有用！问题彻底解决了，衷心感谢！
