### ISSUE TITLE
[Issue] Image not showing on new tab

### ISSUE THREAD

**Issue by NextStep-IM** [Akifyss/obsidian-border#159]
### Issue:
- I put an imgur link in the 'New Tab' section in 'Style Settings' but the image is not showing. I have tried restarting Obsidian but no luck.

### Steps to Replicate:
1.  Copy an image link.
2. Go to settings of 'Style Settings' plugin → Components → New Tab 
3. Paste the url into 'customize new tab image' block.

### Extra Info:
- The image format is png.
- The background of the image has been removed.

**Comment by NextStep-IM** [comment]
> Could you provide a URL for me to test?

https://imgur.com/gallery/0efLLu1

**Comment by Akifyss** [comment]
Ok, thank you. Can you access the URL and then right-click on the image to click the "Copy image link" option?

**Comment by NextStep-IM** [comment]
That worked! Thanks! The 'Copy image link' option gave me a link with '.png' at the end of it.
