### ISSUE TITLE
Option to add color and increase indentation in bulleted lists

### ISSUE THREAD

**Issue by JigenDD** [Akifyss/obsidian-border#16]
Hi! I'm really enjoying the latest additions to the theme. And the "carded" layout to the theme really rocks. 

One thing that could be improved in my opinion are bulleted (and numbered) lists. In Live Preview mode, the lack of enough indentation to the right (_and also lack of padding room in relation to the paragraphs that immediately preceded them above_) makes it hard to immediately discern bullets from the rest of the text. 

These are the things which _I think_ would help improve things:

- Add an option to increase bullet indentation to the right side.
- Add different decoration (different symbols) between bullet levels, making it a bit more like MS Word.
- Add an option for bullets and numbered list numbers to have some color. Either inherited from the accent color _(a more vibrant variation of the tone, to make them as visible as possible)_ or simply allowing the user to customize it, for light and dark theme alike.

The following is an example of the things we can do in MS word, which facilitate visual discernment. I believe that in Border Theme things could look even better, with better vertical lines to separate different bullet levels.
![image](https://user-images.githubusercontent.com/119014255/212122368-593e6ca2-a55b-4883-994e-afe81d7ff9f3.png)

Thanks in advance, and keep up with the **excellent** work! Happy New Year too

**Comment by Akifyss** [comment]
Hello, some relevant options have been added to Style Settings, which you can find in the "Editor-Lists" section, please update and have a check.
