### ISSUE TITLE
When theme used alongside Style Settings, stacked tabs scroll stops working

### ISSUE THREAD

**Issue by northswiss** [Akifyss/obsidian-border#160]
To reproduce:

1. Enable border theme
2. Open multiple tabs
3. Ensure stacked tabs are enabled
4. Observe that you can swipe left and right to navigate between tabs (on Mac OS)
5. Enable Style Settings plugin (which is a recommended complement to this theme
6. Now the horizontal scrolling does not work and you have to click on a tab title to bring it into view. 

Let me know if you need any more details. I am running:

![MBP details@2x](https://github.com/Akifyss/obsidian-border/assets/1618276/90ca30f0-3727-43db-a7ae-c4c8f623d550)

**Comment by Akifyss** [comment]
Is this issue similar to the problem you encountered? If so, you may need to disable the card layout or import the code from the link:
https://github.com/Akifyss/obsidian-border/issues/47

**Comment by northswiss** [comment]
After adding the custom CSS, it solved the problem. Closing issue. Thanks @Akifyss 🙏
