### ISSUE TITLE
Hiding Window Buttons on Mac

### ISSUE THREAD

**Issue by mrstrzx** [Akifyss/obsidian-border#162]
is it possible to be able to hide the window buttons on mac?
<img width="137" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/82619328/4aaa7751-ac07-49d1-9ee0-3366ec598ffe">

**Comment by Akifyss** [comment]
You can download this plugin and adjust the following values:

<img width="697" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23567154/40d4d16a-3e4b-4271-957a-78cfab5e4ec7">

---

<img width="782" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23567154/224af6cd-cb81-43df-aea6-f673acd05239">
