### ISSUE TITLE
Card Layout breaks stacked tabs horizontal scroll

### ISSUE THREAD

**Issue by BogdanCodreanu** [Akifyss/obsidian-border#163]
1. Toggle on Card layout
2. Open multiple tabs with `Stacked Tabs` on.
3. Horizontal scrollbar is missing from bottom, and it doesn't work on `Shift + MouseScroll`.

You can see it working if you toggle off Card layout

**Comment by Akifyss** [comment]
Is this issue similar to the problem you encountered? If so, you may need to disable the card layout or import the code from the link:
#47

**Comment by BogdanCodreanu** [comment]
Yes, it's exactly that issue! Thank you
