### ISSUE TITLE
 Presets Usage - Where to copy exactly?

### ISSUE THREAD

**Issue by anamyk** [Akifyss/obsidian-border#164]
I am trying to follow the instructions on the presets.It says "(Presets Usage: Copy code from link, paste it into style settings and restart obsidian.)"

Sorry but I dont get where I should copy this exactly? Can you provide path and filename or explain please.

That would be awesome, I love the theme and card layout and want to learn how to customize it.
Thank you!

**Comment by Akifyss** [comment]
Is this helpful?
![1](https://github.com/Akifyss/obsidian-border/assets/23567154/b189564c-5f07-41e4-8e0d-0fd438603431)

**Comment by anamyk** [comment]
Yes! Thank you so much for the quick answer!!

Do you have any idea where this setting for the Translucent Preset is?
> (Extra step: Enable "translucent window" in Setting-Appearance)

If anyone is having the same problems, the light or dark presets/themes need to match the general obsidian settings in Settings -> Appearance -> Base color scheme
If you want a light preset, the 'Base color scheme' also needs to be light
If you want a dark preset, the 'Base color scheme' also needs to be dark

**Comment by Akifyss** [comment]
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/e55f5275-031a-4bff-8865-c441e5f93114)

**Comment by anamyk** [comment]
Ahhh its not supported in Linux. Thats why I cannot find it, as I use Ubuntu.
Okay no problem. 

Thank you for your help and the awesome theme!

**Comment by Akifyss** [comment]
Sorry about that.
I will provide further explanation in the document later.
