### ISSUE TITLE
line height, Line Length, paragraph spacing, justify

### ISSUE THREAD

**Issue by TheCodeverse** [Akifyss/obsidian-border#17]
Hello! I hope to adjust the line height and Line Length and paragraph spacing of the note text, and set the text to be justified, and to hide the blank status bar at the bottom. thanks!

**Comment by Akifyss** [comment]
Hello, some relevant options have been added to Style Settings, which you can find in the "Editor-Paragraph" section, please update and have a check. 
And I'm not sure what you mean by "blank status bar", but if you want to hide the bottom status bar, you can refer to this image:
![image](https://user-images.githubusercontent.com/23567154/212376113-20f512fb-0ab9-4720-bb0e-f76d61bf22c6.png)

**Comment by TheCodeverse** [comment]
> 

谢谢你这么快就响应了我的反馈！（我看到你在回复其他用户反馈时使用了中文，我想你是懂中文的，所以我就直接中文回复）

我刚刚升级到了 0.8.1.1 版本，发现行间距和两端对齐都可用了，但在阅读模式下修改段间距，它只在正文和标题之间有效，在正文的多个段落之间无效。编辑模式下修改段间距，在正文的多个段落之间也有效，但有个问题，有些段落无法点击和编辑，比如我的一篇文章有12个段落，修改编辑模式的段间距后，第9、10、11个段落无法点击也无法编辑，用键盘控制鼠标上下移动，会跳过第9、10、11段。
你可以参考一下 Blue Topaz 主题，它的段间距处理得很好，而且它还能缩减笔记最底部的预留空白大小（原本滚动条拉到底，底部有半个屏幕高度的预留空白）。

**Comment by TheCodeverse** [comment]
另外，能否再增加一个可以完全取消卡片模式的选项。卡片的阴影我全部设为零，但四周仍然还有一个边框，我希望可以完全关闭这个，当我把左右侧栏、顶标签页栏、底部状态栏全部自动隐藏之后，就是一个完全空白屏幕，然后上面只有我的内容，没有任何边框和线条。这就完美了。

**Comment by Akifyss** [comment]
> > 
> 
> 谢谢你这么快就响应了我的反馈！（我看到你在回复其他用户反馈时使用了中文，我想你是懂中文的，所以我就直接中文回复）
> 
> 我刚刚升级到了 0.8.1.1 版本，发现行间距和两端对齐都可用了，但在阅读模式下修改段间距，它只在正文和标题之间有效，在正文的多个段落之间无效。编辑模式下修改段间距，在正文的多个段落之间也有效，但有个问题，有些段落无法点击和编辑，比如我的一篇文章有12个段落，修改编辑模式的段间距后，第9、10、11个段落无法点击也无法编辑，用键盘控制鼠标上下移动，会跳过第9、10、11段。 你可以参考一下 Blue Topaz 主题，它的段间距处理得很好，而且它还能缩减笔记最底部的预留空白大小（原本滚动条拉到底，底部有半个屏幕高度的预留空白）。

你好，关于第一个问题，在阅读模式下，我这里段间距设置是有效的，如图所示，橙色的那部分就是设置好的段间距。你可以截张图给我看看吗？
![image](https://user-images.githubusercontent.com/23567154/212449330-1e7f6c0a-f222-42e1-b9af-a582957618f6.png)
关于第二个问题，确实有你所说的问题。Blue Topaz的实现方式我看了，但这会导致 高亮所在行 功能变丑，我认为得不偿失，况且编辑模式的段间距可以通过添加空行实现，因此我将在下一个版本去除这个功能，只保留阅读模式的段间距设置。

**Comment by Akifyss** [comment]
> 另外，能否再增加一个可以完全取消卡片模式的选项。卡片的阴影我全部设为零，但四周仍然还有一个边框，我希望可以完全关闭这个，当我把左右侧栏、顶标签页栏、底部状态栏全部自动隐藏之后，就是一个完全空白屏幕，然后上面只有我的内容，没有任何边框和线条。这就完美了。

当你在style setting中将底层背景设置为编辑器的颜色时，并将阴影去除时，视觉上的边框是可以被去除的。
![image](https://user-images.githubusercontent.com/23567154/212457166-755ae1ee-4c18-47e3-9265-4caf02b4e22c.png)

**Comment by TheCodeverse** [comment]
> > 另外，能否再增加一个可以完全取消卡片模式的选项。卡片的阴影我全部设为零，但四周仍然还有一个边框，我希望可以完全关闭这个，当我把左右侧栏、顶标签页栏、底部状态栏全部自动隐藏之后，就是一个完全空白屏幕，然后上面只有我的内容，没有任何边框和线条。这就完美了。
> 
> 当你在style setting中将底层背景设置为编辑器的颜色时，并将阴影去除时，视觉上的边框是可以被去除的。 ![image](https://user-images.githubusercontent.com/23567154/212457166-755ae1ee-4c18-47e3-9265-4caf02b4e22c.png)

谢谢，按这个方法可以实现。

**Comment by Akifyss** [comment]
排查了一下，如果仅仅只是换行的话，obsidian的阅读模式并不会把它视作新段落，只有当每个段落之间有空行隔开，阅读模式才会视为不同的段落。
因此，如果当整篇文章的段落都没有空行隔开的话，它们只会被视为一个段落，段间距只会在首尾生效。新版加了一个开关来避免这个问题，可以更新看看。

**Comment by TheCodeverse** [comment]
> 排查了一下，如果仅仅只是换行的话，obsidian的阅读模式并不会把它视作新段落，只有当每个段落之间有空行隔开，阅读模式才会视为不同的段落。 因此，如果当整篇文章的段落都没有空行隔开的话，它们只会被视为一个段落，段间距只会在首尾生效。新版加了一个开关来避免这个问题，可以更新看看。

刚刚升级了 0.8.2.1 版本，段间距的问题解决了，感谢！

**Comment by TheCodeverse** [comment]
还有一个小问题，能否缩减文末的半屏预留空白空间？如图

Border 主题的文末预留空白空间：
![screenshot_20230115141613](https://user-images.githubusercontent.com/37426761/212526187-d2cf6749-d3f4-4bb7-8f65-ddc35a13ac7b.png)

Blue Topaz 主题开启了缩减预留空白功能之后：
![screenshot_20230115141644](https://user-images.githubusercontent.com/37426761/212526209-c66e37d9-bf99-4b91-a04e-cead347464c1.png)

**Comment by Akifyss** [comment]
有点不太理解这个功能的作用？

**Comment by TheCodeverse** [comment]
> 有点不太理解这个功能的作用？

的确是个可有可无的需求。

**Comment by Akifyss** [comment]
这里是CSS代码片段，可以自行导入obsidian：https://github.com/Akifyss/obsidian-border/blob/main/snippets/bottom-blank-space.CSS
