### ISSUE TITLE
folder and document icon

### ISSUE THREAD

**Issue by BCS1037** [Akifyss/obsidian-border#171]
Could the folder icon and file icon be changed to the previous version as shown in the following image?

![image](https://github.com/Akifyss/obsidian-border/assets/120721474/c52e369e-d72a-4bd3-8dde-b45d508cac57)

**Comment by Akifyss** [comment]
Sorry, there are currently no plans to revert the icons, but thank you for letting me know your preference. I'll see if it's possible to bring them back later.
