### ISSUE TITLE
暗黑模式问题、文字宽度、标题样式和文内代码引用改进

### ISSUE THREAD

**Issue by Amenomiya-Sumire** [Akifyss/obsidian-border#173]
1. 暗黑模式下，无法更改卡片的圆角数值
2. 
![image](https://github.com/Akifyss/obsidian-border/assets/152671582/36a7aa42-dd8d-4ec2-9ad1-0279e7a1f2d9)
希望能自定义这个竖线的颜色，并使其稍微和标题间距大一点。还有，这条线（包括引用块的竖线）好像跟文字不完全对齐
3. 希望能自定义页面文字宽度
4. 希望能让文内代码保持和代码块类似的预设风格

**Comment by Akifyss** [comment]
1. 关于第一个问题，我这里是可以设置的。可以看看你填写的数值吗？
2. 关于第二个问题。竖线色彩选项和间距问题将在之后的更新改善。
可以暂时导入以下代码修改对应的标题竖线颜色。
```css
h1,.HyperMD-header-1{
    --h1-indicator-color:green/*替换此处的色彩*/!important;
}
```
3. 关于第三个问题，可以在“编辑区-段落-段落行宽”处修改。
4. 抱歉目前还暂时还没有此计划。可能会在未来的版本中实现它。
