### ISSUE TITLE
关于代码块的建议

### ISSUE THREAD

**Issue by biukang** [Akifyss/obsidian-border#174]
1. 代码块可以增加行号吗
2. 预览模式下，希望可以和编辑模式一样显示代码块语言
非常感谢您的付出

**Comment by Akifyss** [comment]
你好。
1. 代码块加行号可以导入这个issue里的片段实现： https://github.com/Akifyss/obsidian-border/issues/125
2. 抱歉，这个功能用css主题来实现，可能不能做得特别完善，所以暂时还不会添加，但是我会再留意一下看看。
