### ISSUE TITLE
editor,代码块 键入符style问题

### ISSUE THREAD

**Issue by ddatsh** [Akifyss/obsidian-border#177]
代码样式，比如用 dracula 后， 键入符就不显示了
![1](https://github.com/Akifyss/obsidian-border/assets/1809194/0da7edc7-0eb1-48b8-8cc6-5821a9f02119)
![2](https://github.com/Akifyss/obsidian-border/assets/1809194/5417af0a-caa5-49df-bcc0-b1f7eb427ebf)

**Comment by Akifyss** [comment]
你现在的主题版本是多少？

**Comment by ddatsh** [comment]
> 你现在的主题版本是多少？

{
	"name": "Border",
	"version": "1.6.6",
	"minAppVersion": "0.16.0",
	"author": "Akifyss",
	"authorUrl": "https://github.com/Akifyss"
}
