### ISSUE TITLE
一个全新的想法💡：供大佬参考

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#18]
大概是一种能添加颗粒背景的仿生纸主题，即模拟显示生活中的宣纸。大佬可以尝试开发一个中国风极简主题，ob里面缺这个创意。

**Comment by Akifyss** [comment]
我的想法是尽量让用户自己来自定义。如果想要颗粒纸背景，可以参考如图设置：
![image](https://user-images.githubusercontent.com/23567154/212462391-bc7dabbb-c6b7-4c63-a9fe-8e11f7cc3dd2.png)
底层背景设置为：url("https://www.transparenttextures.com/patterns/cream-paper.png")

**Comment by miaoziguan** [comment]
我认为非常nice（狗头）

**Comment by miaoziguan** [comment]
url("https://www.transparenttextures.com/patterns/cream-paper.png")

**Comment by miaoziguan** [comment]
这个功能真的太强悍了，可自定义的风格千变万化。
希望也能给中间栏和侧边栏也加上自定义CSS背景
绝绝子，这样用户基本上可以随心所欲打造不同的调性主题。

**Comment by Akifyss** [comment]
新版已添加
