### ISSUE TITLE
Cursor bug in live preview with long equations

### ISSUE THREAD

**Issue by StrangeGirlMurph** [Akifyss/obsidian-border#186]
```md
- $\text{FTIME}(t(n))=\left\{ f \mid f \text{ wird von einer t(n)-zeitbeschränkten DTM berechnet} \right\}$
line x
line y
```

This content creates some very weird behavior. Maybe just try it out. It's not that simple to describe. 

When I am actively editing the file this renders to the following in live preview:
![Screenshot_20240228_144534](https://github.com/Akifyss/obsidian-border/assets/62220780/35c7b021-253e-40b7-aa73-ee6e9ab378b6)
For all the lines afterwards the cursor is off by a line. When I select line y with my mouse the cursor appears in line x.

When obsidian isn't the active window or I press shift or alt the live preview it switches to this:
![image](https://github.com/Akifyss/obsidian-border/assets/62220780/75bc951f-7708-4326-a6f3-c26d557e85b9)
Which maps the mouse click correctly again. After a single mouse click it switches to the first state though.

**Comment by Akifyss** [comment]
I'm sorry, I may not have understood your meaning correctly. I tested it in my own environment and didn't encounter any issues. Could you please test it again in a sandbox environment and provide a video recording?

![2](https://github.com/Akifyss/obsidian-border/assets/23567154/8ba4c8b4-19c7-4da9-bfdd-49e3f9cb01e0)

**Comment by StrangeGirlMurph** [comment]
Here is a video. I'll close this issue because I noticed it has nothing to do with borders. I'll open an issue somewhere else. It's very weird. In some cases everything is fine. But it isn't even consistent I think.

https://github.com/Akifyss/obsidian-border/assets/62220780/eb6bdf13-76c0-4b9f-932f-4a4f55cc7d3c
