### ISSUE TITLE
Suggestions for background and font size of inline code.

### ISSUE THREAD

**Issue by raylanb** [Akifyss/obsidian-border#190]
From:

.markdown-rendered :not(pre)>code,
.cm-s-obsidian span.cm-inline-code {
    color: var(--inline-code-normal)
}

![image](https://github.com/Akifyss/obsidian-border/assets/56618618/ff8bf231-2dd9-4258-b4da-b5eb585c38d2)

Change to:

.markdown-rendered :not(pre)>code,
.cm-s-obsidian span.cm-inline-code {
    color: #e95d00;
    background: #cccccc62;
    font-weight: bold;
    font-size: 1em;
}

![image](https://github.com/Akifyss/obsidian-border/assets/56618618/6f14ce8f-044a-4607-8a8d-3f4c33f17f56)

This way is clearer.

Or change it to a configurable option in the plugin's style settings.

**Comment by Akifyss** [comment]
You can configure them in this section：
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/63a329ae-0a96-4b3b-8c3b-777976c1578f)

**Comment by raylanb** [comment]
Of course I can debug here, but I cannot set the font-weight and font-size. If I want to set these two contents, I still need to go to the theme.css file to set the code.

**Comment by Akifyss** [comment]
Adding font-weight and font-size similar to other elements in the style settings will make the already complex setting even more complicated, sorry.
Since you can write CSS code, I believe adding custom snippets in "Appearance-CSS snippets" is a better way.

**Comment by raylanb** [comment]
This is also a good choice. I just feel that the default background and style are a bit lacking in unity with other content, so it will be more harmonious later on. I have achieved this effect through snippets.

**Comment by Akifyss** [comment]
Thank you for your suggestion and feedback. Improvements may be made in the future.

**Comment by teristam** [comment]
Just want to add that I really like the border theme, but the inline code background style is really out of place. I hope the default will be changed.
