### ISSUE TITLE
Bold and italic font doesn't follow color scheme when in blockquotes

### ISSUE THREAD

**Issue by realvz** [Akifyss/obsidian-border#192]
I have customized the theme using the style settings plugin to set the color of bold text to red. However, when the text is in block quotes, the color scheme is not respected. 

Normal text:
![image](https://github.com/Akifyss/obsidian-border/assets/3195405/fffd8008-03c2-47e2-8e14-f4df6548637e)

Text is block quotes: 
![image](https://github.com/Akifyss/obsidian-border/assets/3195405/53c31cd1-68cf-4151-8447-0b3880b3c91c)

**Comment by Akifyss** [comment]
The new version has fixed this issue. You can try updating it.
