### ISSUE TITLE
Horizontal Rule styling.

### ISSUE THREAD

**Issue by mantacid** [Akifyss/obsidian-border#197]
My issue is that there is no style. As in the horizontal rule (- - - ) does not display at all.

**Comment by Akifyss** [comment]
Perhaps my understanding is incorrect. Do you mean your horizontal rule (- - - ) has disappeared? In my environment, the horizontal rule (- - - ) is normal. I guess it might be conflicting with some plugins. Could you try again in a sandbox environment?

**Comment by mantacid** [comment]
Nevermind, I'm just stupid. I changed the color of some element to purely transparent to get rid of the annoying lines in the style settings, unaware that that also hid the horizontal rules. If possible, it might be wise to make those separate options in the style settings.
