### ISSUE TITLE
希望能对DB Folder插件进行支持

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#2]
如题所示，该主题影响到DB Folder的标题下来选项无法正确读取

**Comment by Akifyss** [comment]
你好，可以再详细描述一下问题吗？我目前发现的问题是点击表头后菜单无法触发显示，不知道说的是不是这个问题？

**Comment by miaoziguan** [comment]
> 你好，可以再详细描述一下问题吗？我目前发现的问题是点击表头后菜单无法触发显示，不知道说的是不是这个问题？

是的

**Comment by miaoziguan** [comment]
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/115944923/210513848-4f09b403-48c8-4fe1-94ca-af5e74b95e37.png">

如图所示，这块的在列数比较少的情况下会比较空，影响观感，是否可以单独给db Folder的列宽改变一下

**Comment by Akifyss** [comment]
已更新
