### ISSUE TITLE
插件适配：Full Calendar的颜色

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#20]
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/115944923/212701965-e735170c-23c0-49e1-9caf-41b11430aaf5.png">
如图所示，Full Calendar无法自定义颜色，希望大佬能够让插件能够自定义颜色

**Comment by Akifyss** [comment]
抱歉，由于精力有限，除非是插件与主题出现兼容问题，太过细节的插件优化应该是不会考虑了。不过你可以考虑给原插件作者提issues。

**Comment by miaoziguan** [comment]
好的，感谢大佬

**Comment by miaoziguan** [comment]
好的，感谢大佬
