### ISSUE TITLE
亮色模式下深色代码块内容的选中问题

### ISSUE THREAD

**Issue by karise-guo** [Akifyss/obsidian-border#206]
我在亮色模式下将代码块设置成了 Dracula 主题以后，代码块的内容用鼠标选中就无法展示选中背景了，我要如何让深色的代码块也显示选中背景呢，浅色的代码块是有选中背景的，求助...

![iShot_2024-03-15_15 16 13](https://uploads.linear.app/67e02151-0cce-46fe-95dd-7227aa34e0e2/eb288ae4-e94c-4124-b354-2e48afc90d3f/9b49c4ed-c9b8-4fd4-9e30-a571d9377069?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY3ZTAyMTUxLTBjY2UtNDZmZS05NWRkLTcyMjdhYTM0ZTBlMi9lYjI4OGFlNC1lOTRjLTQxMjQtYjM1NC0yZTQ4YWZjOTBkM2YvOWI0OWM0ZWQtYzliOC00ZmQ0LTllMzAtYTU3MWQ5Mzc3MDY5IiwiaWF0IjoxNzEwNTc0NjM1LCJleHAiOjMzMjgxMTM0NjM1fQ.nIkh3GcBoPbhDf3WlddaYYJh7Me7UXy9KzBzpmGD8uE)

![iShot_2024-03-15_15 13 20](https://uploads.linear.app/67e02151-0cce-46fe-95dd-7227aa34e0e2/e7ddc7b1-9d11-4552-8521-5f420ff64695/e119e0c9-a96d-40eb-a31a-745743d0b78f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY3ZTAyMTUxLTBjY2UtNDZmZS05NWRkLTcyMjdhYTM0ZTBlMi9lN2RkYzdiMS05ZDExLTQ1NTItODUyMS01ZjQyMGZmNjQ2OTUvZTExOWUwYzktYTk2ZC00MGViLWEzMWEtNzQ1NzQzZDBiNzhmIiwiaWF0IjoxNzEwNTc0NjM1LCJleHAiOjMzMjgxMTM0NjM1fQ.iMeWarLHsCWtDzeRpxU1tyP-LiTCeuR-ePKrbfsRPnc)

![iShot_2024-03-15_15 14 29](https://uploads.linear.app/67e02151-0cce-46fe-95dd-7227aa34e0e2/c27db2ba-782b-404a-be76-af2cd46b8b3e/e9aa155f-3baf-45ae-9c13-6d5af84f0873?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY3ZTAyMTUxLTBjY2UtNDZmZS05NWRkLTcyMjdhYTM0ZTBlMi9jMjdkYjJiYS03ODJiLTQwNGEtYmU3Ni1hZjJjZDQ2YjhiM2UvZTlhYTE1NWYtM2JhZi00NWFlLTljMTMtNmQ1YWY4NGYwODczIiwiaWF0IjoxNzEwNTc0NjM1LCJleHAiOjMzMjgxMTM0NjM1fQ.vIEhmExq781KHGEGDN3ZHBx25auf7fwlwnySe95wtDI)

**Comment by Akifyss** [comment]
新版已修复，可以更新试试

**Comment by karise-guo** [comment]
@Akifyss 感谢你的回复，我更新了主题最新版本，然后我发现我看不到深色代码块的选中色，是因为我修改了主题色为 `#44484F` 导致了深色代码块的选中色非常浅。

![image](https://github.com/Akifyss/obsidian-border/assets/16834649/3b17caf4-dd6d-43f4-8ec5-7b58590f2e0f)

然后我尝试按照你的提交修改了我本地 `.obsidian/themes/Border/theme.css` 下的代码：
```css
.codeblock-style-dracula .cm-s-obsidian .HyperMD-codeblock span::selection {
    background-color: #d3c074;
}
```
但似乎并没有效果，请问我有办法能够自己修改代码块选中背景色吗，如果作者能够在`Style Setting`里加一个自定义的选项那就更棒了～

<img width="904" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/16834649/9c4232ce-f84c-460d-af44-de53a02b2c9b">

**Comment by Akifyss** [comment]
刚刚有更新了一版，可以再试试。应该是还需要重新安装obsidian来提升安装程序版本才能生效

**Comment by karise-guo** [comment]
我更新后可以了，非常完美，感谢！
