### ISSUE TITLE
关于Canvas的功能建议

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#21]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/115944923/212711751-f1819f3a-d4ed-425b-aabb-360f7d959206.png">
如图所示，Canvas自带描边的太粗，不太符合border主题的气质。
希望大佬出一个能调节描边的功能（🙏）

**Comment by Akifyss** [comment]
这个后面会考虑的

**Comment by Akifyss** [comment]
新版已更新。可以在“组件-白板“中手动调节
