### ISSUE TITLE
Paper-like preset background not working with stacked tabs

### ISSUE THREAD

**Issue by Lanwara** [Akifyss/obsidian-border#214]
I'm using the [Paper-like preset](https://github.com/Akifyss/obsidian-border/blob/main/presets/Paper-like.json) for its really nice background.

It works great normally, like so:

![Stacked tabs OFF. Notice the grainy background.](https://github.com/Akifyss/obsidian-border/assets/89237755/94efb243-93c8-4762-8819-3ad0ee0878bc)

But as soon as I enable Stacked Tabs I lose that background:

![Stacked tabs ON. The nice background is no more!](https://github.com/Akifyss/obsidian-border/assets/89237755/a8c7b028-5009-49ec-ae46-52a32de5d4c4)

## Maybe useful info

[My style settings.](https://gist.github.com/Lanwara/9942798121bfbcbb8502b8341ffc91c0) (External link to a gist because the SVGs are too big to be directly placed here.)

**Comment by Akifyss** [comment]
This is actually the same issue as this issue: #76. Currently there is no fix for it, sorry
