### ISSUE TITLE
Version 1.7.13 flickers when sliding documents around

### ISSUE THREAD

**Issue by Airpy** [Akifyss/obsidian-border#218]
Version 1.7.13 flickers when sliding documents around, it doesn't happen when switching to the default theme.

<img width="964" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/20046478/90865712-4316-40d1-bab0-ae62c456106d">

<img width="907" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/20046478/9c94eb4d-9d69-4cc5-a95d-db49464bd9e1">

As shown above, a blank will appear when flashing, and the actual content will be displayed after less than 1 second.

**Comment by Akifyss** [comment]
This is probably related to the performance issues of this theme. You can refer to this issue: #102. It may gradually improve later, but currently cannot be resolved well. Sorry.
