### ISSUE TITLE
Frustration with auto hiding tab bar 

### ISSUE THREAD

**Issue by machado-t** [Akifyss/obsidian-border#219]
I've encountered a minor frustration with the auto-hiding functionality of the tab bar. Specifically, moving the mouse to regions of the tab bar where there are neither buttons nor tabs present doesn't seem to trigger the appearance of the tab bar. 

It would be much more intuitive if the tab bar could be revealed by hovering over any part of its zone, regardless of whether there are any elements in that area. Even when the mouse cursor is moved all the way to the top edge of the screen, on right above a tab, it still fails to become visible.

Thanks

**Comment by Akifyss** [comment]
I've looked into it; those blank areas have been designated as the window's drag region, which means they won't respond to any interactive events. As a result, the effect you're looking for can't be implemented at this time. Sorry about that.
