### ISSUE TITLE
Option to increase width of certain elements + file navigation (like minimal)

### ISSUE THREAD

**Issue by JigenDD** [Akifyss/obsidian-border#22]
Hello! I've been using Border A LOT as of late, given that the amount of quality improvements have stacked one on top of the other amazingly well. 

# Table, Image, iFrame and Video width
One limitation I've come to find recently is certain elements being too narrow for my needs. I'm a heavy table user, with them often having 4 or more rows, and that requires more space than usual. Thus far, one theme that helped me with this – and to my knowledge, the only theme that supports it – was the _Minimal_ theme.

![image](https://user-images.githubusercontent.com/119014255/213889840-718ab99a-b175-4041-a503-9fc41e38aeb4.png)

In the minimal theme settings plugin we'd have these options to alter the width and display mode of many elements, like images, iframes (YouTube videos for example) and tables. 

It would be pretty cool if Border got the ability to set the display mode these elements differently. Things like alignment (left, center, right), whether they over-extend the editor into "wide line" limits, if we get to zoom images on click, etc

# File Navigation
By default (and IMHO) Obsidian doesn't have the most visually pleasant file outline. It gets cluttered way too fast because there's only one level of selection (1 pane), unlike say, OneNote, which features 2 panes, one after the others. We can make things slightly better with plugins like Icon Folder, but we can only do so much. 

There's a few things that border could do to make file navigation a little bit better:
- Option **not** to trim file or folder name (like minimal)
- Option to set separate colors for **folder icon**, and **file icon**  making the visual distinction between the 2 greater. The option to set folder font in bold by default would be great. 

Many thanks for the great job!

**Comment by JigenDD** [comment]
The new changes are much appreciated!

In regards to object width, I can use "image zoom", BUT turning on or off the full width tables option does nothing (i.e. tables continue to be the same width as the text body)

**Comment by Akifyss** [comment]
Hi, turning on full width table will expand the table width to full line width (you can increase the line width in "Editor-Paragraph"). This option works for me. Can you take a screenshot so I can see it?

![Frame 1994](https://user-images.githubusercontent.com/23567154/214855483-dd6e2c86-a783-4e0c-9b57-e7c21e161e5c.png)

**Comment by JigenDD** [comment]
Hi, what I was asking if it would be feasible in border would be implementing something as in the example below, which comes straight from the Minimal Theme, with tables set to "Maximum Line Width" in the "Minimal Theme Settings".

![image](https://user-images.githubusercontent.com/119014255/214998553-a2adc291-9760-48cf-8319-0d234800932b.png)

Implementing the ability to set tables to "Text Width", "Wide Line Width" and "Maximum Line Width" (just like in Minimal) would be a major advantage of the Border theme.

P.S. I am able to get tables to show just like you demonstrated in your screenshot, but I was looking into the possibility of taking things one step further, and let tables be **_wider_** than the normal text width. Just like Minimal allows for.

**Comment by Akifyss** [comment]
Hi, as I said before, I have no plans to implement this feature at the moment. I have previously tried to reference the Minimal Theme implementation and found that it would require a major change at some level of the code which I am sure would create conflicts and even bugs with the current code. I have tried other implementations but they do not work very well.

Here is a CSS snippet, which you can import into obsidian yourself: https://github.com/Akifyss/obsidian-border/blob/main/snippets/table-width-adjust.css.

After importing this CSS snippet, you can adjust table width in Style Setting. The disadvantage of this snippet is that the adjusted table width is not adaptive. If you have a better way of doing this, please let me know.

**Comment by Akifyss** [comment]
An improved css snippet has been added to the new version. Instead of manually importing the css snippet above, you can now set the table width directly in style settings.

**Comment by JigenDD** [comment]
I've been playing around with your solution, and thus far it has been amazing and very functional. Even by setting the table wider, the table will smoothly auto-size in smaller windows. Amazing work, many thanks!

**Comment by Arnoud-B** [comment]
I'd just like to add my support for the original request. I'm enjoying this theme a lot and would like to switch from Minimal.

However, I'm using dataloom quite a bit, and it seems impossible to get the dataloom table to take full width in Border (without also increasing paragraph width, which would make the text very hard to read on a large monitor). As those tables can get big, it's quite difficult to manage them in Border. So I'm hoping support for maximizing dataloom tables will come in the future.

If I should create a new issue for this instead, let me know.

**Comment by Akifyss** [comment]
You can try importing the following CSS snippet to see if it works::
```css
.dataloom-table {
    width: 100%;
}
```

**Comment by Arnoud-B** [comment]
It seems that .dataloom-table will resize the table within .dataloom-app. Changing the width of .dataloom-app makes it wider, but this can already be set in the DataLoom plugin settings.

The issue with the latter, in Border, is that the loom is not centered. So it will extend towards the right only, leaving a lot of empty space on the left. On top of that, it is relative to the paragraph (text?) width. So when you resize the window, the loom either doesn't fit anymore or is too small.

Would it be a solution to apply the same style to .dataloom-app as to tables?

**Comment by Akifyss** [comment]
Sorry, I haven't used dataloom before, so I'm not quite sure which table you're referring to. Could you please provide some images?

**Comment by Arnoud-B** [comment]
Sure, these should help:
![Screenshot 2024-02-01 at 18 04 17 (Obsidian)@2x](https://github.com/Akifyss/obsidian-border/assets/11488458/914e98d7-5a2a-45f9-9512-368e1eaac49e)
![Screenshot 2024-02-01 at 18 02 28 (Obsidian)@2x](https://github.com/Akifyss/obsidian-border/assets/11488458/83edb71e-096b-41e7-bf5f-2bf6fbed0223)

I forgot that I changed the table width with the Style Settings plugin, but this plugin adapts to what is available in the theme (I get very different options when Minimal is active, for instance). So I suppose it could automatically find anything specific to DataLoom-type content as well once it's there.

**Comment by Akifyss** [comment]
This code snippet can make the width of the dataloom table equal to the width of the table.：
```css
.table-width-customized :is(div,span):has(>.dataloom-embedded-container) {
    overflow: auto;
    width: var(--table-width) !important;
    margin-left: calc((var(--table-width) - 100%) / -2) !important;
}
```

**Comment by Arnoud-B** [comment]
Thanks, almost there! It seems to adjust the width correctly, but not the margin-left. The dataloom table still starts at the same spot as a paragraph.

**Comment by Akifyss** [comment]
Strange, it works fine in my environment, so I couldn't find any abnormal reasons. Sorry.

**Comment by Arnoud-B** [comment]
Well that's weird. I just created a new vanilla vault, and installed: your theme, the DataLoom and Style Settings plugins, and loaded the CSS snippet. Set the table width to "Customizable table width" at 88% in Style Settings. Result is still the same:
![Screenshot 2024-02-02 at 12 33 15 (Obsidian)@2x](https://github.com/Akifyss/obsidian-border/assets/11488458/285c7eac-bc71-4493-b1b4-bfedd4017e42)

**Comment by Akifyss** [comment]
Is this helpful?
```css
.table-width-customized .view-content :is(div,span):has(>.dataloom-embedded-container) {
    overflow: auto;
    width: var(--table-width) !important;
    margin-left: calc((var(--table-width) - 100%) / -2) !important;
}
```

**Comment by Arnoud-B** [comment]
Yes! That fixed it. Thanks so much 🙏
