### ISSUE TITLE
Bug: External links incorrectly using internal link color from style settings

### ISSUE THREAD

**Issue by machado-t** [Akifyss/obsidian-border#220]
External links are using the color intended for internal links as defined in the Style Settings plugin. Other aspects like hover color, underlining, and other styles for external links work as intended and do not seem to be affected.
Thanks

**Comment by machado-t** [comment]
While it is fixed for markdown links, e.g. [](), it seems to be not fixed for links not inside []()

**Comment by Akifyss** [comment]
I haven't found out which ones yet, could you please help point them out?

**Comment by Akifyss** [comment]
theme has been updated, you can give it another try.
