### ISSUE TITLE
Smaller side drawer for pads?

### ISSUE THREAD

**Issue by jiywww** [Akifyss/obsidian-border#223]
It's not a big matter, but it would be great if the side drawer (both left and right) could be slightly smaller on tablets for a better visual impact. Currently, it slightly overlaps with the system status bar (as shown in the screenshots below).

<img src="https://github.com/Akifyss/obsidian-border/assets/57605947/a5c08ed2-180d-45b8-8548-f70b216c01ef" width=400>
<img src="https://github.com/Akifyss/obsidian-border/assets/57605947/8fafaa11-4e11-4352-a4eb-d2efd19a3e14" width=400>
<img src="https://github.com/Akifyss/obsidian-border/assets/57605947/17aee397-505d-4502-b27d-f71a8f5a0b4b" width=400>
<img src="https://github.com/Akifyss/obsidian-border/assets/57605947/c8f5ebf0-1ba6-4722-8bd5-66074b0c774e" width=400>

**Comment by Akifyss** [comment]
The new version has fixed this issue. You can try updating it.
