### ISSUE TITLE
想问一下，插件设置里的标题文字和第二行文字的颜色是在哪里修改的

### ISSUE THREAD

**Issue by Ghoulswh** [Akifyss/obsidian-border#226]
看到群友用了您的主题，觉得这个字体颜色很好看，想问下是通过Style setting设置的，还是主动添加css片段
![QQ图片20240331000704](https://github.com/Akifyss/obsidian-border/assets/142091830/bd51caef-6937-43f5-bc81-0fa607021729)

**Comment by Akifyss** [comment]
应该是这两个地方，不过需要得先知道那两个颜色的色值。

![image](https://github.com/Akifyss/obsidian-border/assets/23567154/260140c8-08b9-4ba2-ab2b-2b371df46338)
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/92bf4d32-bc05-4d34-b907-1969b1e72b0e)

**Comment by Ghoulswh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
