### ISSUE TITLE
右上角缩小，关闭等按钮操作困难

### ISSUE THREAD

**Issue by zezehihi** [Akifyss/obsidian-border#23]
![Snipaste_2023-01-28_11-27-34.jpg](https://img1.imgtp.com/2023/01/28/rafi2b2P.jpg)
![Snipaste_2023-01-28_11-33-12.jpg](https://img1.imgtp.com/2023/01/28/IN9rHJM5.jpg)
在Auto hide tab bar模式打开时
放大、缩小窗口和修改窗口大小很困难。

1.是不是悬停时tab bar上的按钮没正确显示？
2.如果不是1的问题，可以设置放大、缩小、关闭窗口按钮显示吗？

**Comment by Akifyss** [comment]
其他的autohide模式有问题吗？请确保执行了以下操作，试试重新安装[obsidian](https://obsidian.md)。（因为autohide功能用到了一个新的CSS特性，只有重新安装下载的obsidian才带有这个特性）。如果仍然有问题，可以麻烦截一张动态给我看看吗
![image](https://user-images.githubusercontent.com/23567154/215250994-9cb47622-11be-4edc-a91b-c3bd901a353f.png)

**Comment by zezehihi** [comment]
其它的autohide模式没有问题。
---
直接重新安装了，解决了。
