### ISSUE TITLE
需求：border自动隐藏两侧边栏

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#232]
佬，好久不见，一直致力于推广border主题，需求如下：

![image](https://uploads.linear.app/67e02151-0cce-46fe-95dd-7227aa34e0e2/8e74e499-d981-492b-85df-a6d652a9c4a6/5187f4ca-2582-4ad5-92ee-f6428295dc63?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY3ZTAyMTUxLTBjY2UtNDZmZS05NWRkLTcyMjdhYTM0ZTBlMi84ZTc0ZTQ5OS1kOTgxLTQ5MmItODVkZi1hNmQ2NTJhOWM0YTYvNTE4N2Y0Y2EtMjU4Mi00YWQ1LTkyZWUtZjY0MjgyOTVkYzYzIiwiaWF0IjoxNzEyNTY3NTEyLCJleHAiOjMzMjgzMTI3NTEyfQ.YR0k8VvPnQUixGjcC5mXEFZiBhUBmlyqe2NYhjFBdrA "=715x")

![image](https://uploads.linear.app/67e02151-0cce-46fe-95dd-7227aa34e0e2/44ddd39d-ca50-41c9-b132-6131e624f371/24fde563-aa68-4f7b-ba26-33187ca010e8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY3ZTAyMTUxLTBjY2UtNDZmZS05NWRkLTcyMjdhYTM0ZTBlMi80NGRkZDM5ZC1jYTUwLTQxYzktYjEzMi02MTMxZTYyNGYzNzEvMjRmZGU1NjMtYWE2OC00ZjdiLWJhMjYtMzMxODdjYTAxMGU4IiwiaWF0IjoxNzEyNTY3NTEyLCJleHAiOjMzMjgzMTI3NTEyfQ.uvdKKOvj8DELPuJnnsuBk3DiFx_MS0gRBvms_lqeauc "=678x")

**Comment by Akifyss** [comment]
感觉用css不太好实现，或者说实现的效果不会太好。我之后去试试看，但是不能保证。也可以试试auto hide 和Sidebar Expand on Hover 这两个插件

**Comment by Akifyss** [comment]
这段时间试了以下，效果确实不咋好。抱歉

**Comment by miaoziguan** [comment]
好的，大佬幸苦了

Akifyss ***@***.***> 于2024年6月8日周六 18:55写道：
