### ISSUE TITLE
Highlight in Codeblock is not visible when a codeblock style is selected.

### ISSUE THREAD

**Issue by kolumdium** [Akifyss/obsidian-border#234]
When you highlight text in a codeblock with a codeblock style selected it is not visible that the text is highlighted.
It seems that the ::selection is not corretly applied.
By suggestion of an obsidian member on discord I tried to apply my own style by adding .view-content which worked.
I then tried to fix the issue in the theme.css to see where the problem was.
Adding a .view-content here to resolved the problem.

Example:
```
.view-content .codeblock-style-dracula .cm-s-obsidian .HyperMD-codeblock ::selection,
.codeblock-style-dracula .markdown-rendered pre ::selection {
    background-color: hsl(from var(--code-normal) h s l / 20%);
}
```

I am not sure what the proper way to fix it is.

**Comment by Akifyss** [comment]
You can check out this：https://github.com/Akifyss/obsidian-border/issues/227
Reinstalling Obsidian should fix the problem.
