### ISSUE TITLE
The Border theme are choppy and unstable in Obsidian

### ISSUE THREAD

**Issue by EvgenA** [Akifyss/obsidian-border#237]
Guys, I want to thank you for creating the Border theme, which I just discovered.
But the fact is that I have a problem and I'm afraid I need help.
On my computer, after installing the theme (Border v.1.7.16), no matter which appearance presets I choose and install, Sunset or Glassmorphism, both are choppy and unstable in Obsidian (v. 1.5 .12) on OS Sonoma (v.14.4.1). Obviously, the theme comes with Style Settings, but currently I haven't managed to resolve this really unpleasant phenomenon. Whereas the Blue Topaz theme, for example, or the default Obsidian theme, are fluid and work very well.
Do you have any advice or a solution to remedy this?
I thank you in advance.

**Comment by Akifyss** [comment]
Does it mean it's very laggy? Some presets with pictures may indeed not be very performance-friendly. You can try not to use them. And the theme does have its own performance issues, too. Here is a performance-related issue that might be helpful: https://github.com/Akifyss/obsidian-border/issues/102 . This problem may not be solved in the short term, sorry.
