### ISSUE TITLE
Request to support multiple checkbox states?

### ISSUE THREAD

**Issue by bhavul** [Akifyss/obsidian-border#24]
Hi,

May I first say thanks for building such an amazing theme. It's chef's kiss. 
I believe it may be missing support for multiple checkbox styles -- such as one here : https://gist.github.com/OliverBalfour/b87459fd55cf1f5832a2e0996a6f45a0

Do you think it's possible to add that?

Thanks!

**Comment by Akifyss** [comment]
This feature will be supported soon.

**Comment by Akifyss** [comment]
This feature is available in the new version, here is the syntax:
![Checkboxes](https://user-images.githubusercontent.com/23567154/216659283-a93a7c92-e160-4155-b0e6-8a88cad94d96.png)

**Comment by bhavul** [comment]
Thanks a tonne!

**Comment by jcesguerram** [comment]
> This feature is available in the new version, here is the syntax:
> 
> ![Checkboxes](https://user-images.githubusercontent.com/23567154/216659283-a93a7c92-e160-4155-b0e6-8a88cad94d96.png)

Hi. I can't get the checkboxes to look like that. Is there something I need to install or turn on?
Is it necessary o add the snippet of for the checkboxes in ITS theme?

**Comment by Akifyss** [comment]
> > This feature is available in the new version, here is the syntax:
> > ![Checkboxes](https://user-images.githubusercontent.com/23567154/216659283-a93a7c92-e160-4155-b0e6-8a88cad94d96.png)
> 
> Hi. I can't get the checkboxes to look like that. Is there something I need to install or turn on? Is it necessary o add the snippet of for the checkboxes in ITS theme?

This feature works in my environment. Could you provide some more detailed information? For example, how is this feature performing currently? Are there any pictures or videos available?

**Comment by jcesguerram** [comment]
> ed information? For example, how is this feature performing currently? Are there any pictures or videos available?

reschedule and question look like this, for example:

![Checkboxes](https://github.com/user-attachments/assets/d1832715-9a81-446a-8cbc-4bb33eaa0993)

**Comment by Akifyss** [comment]
> > ed information? For example, how is this feature performing currently? Are there any pictures or videos available?ED信息？例如，此功能目前表现如何？有图片或视频吗？
> 
> reschedule and question look like this, for example:重新安排和问题如下所示，例如：
> 
> ![Checkboxes](https://private-user-images.githubusercontent.com/122333212/349191535-d1832715-9a81-446a-8cbc-4bb33eaa0993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTA4MzksIm5iZiI6MTcyMTE1MDUzOSwicGF0aCI6Ii8xMjIzMzMyMTIvMzQ5MTkxNTM1LWQxODMyNzE1LTlhODEtNDQ2YS04Y2JjLTRiYjMzZWFhMDk5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxNzIyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTA0NmRjNjNlMGY5ZTE0ZmQzODQyNzc2ZGYyYThhOWM4NjViYWJjZDBlODE2Nzk1NDRlY2RiYTIzOTFiZjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wQoKZYjSigIQ_RLY3c7E6g2p1B7urCfSWJHMCrUp2Eo)

It seems like there might be a conflict with some plugins. Could you test it again in a sandbox environment?

**Comment by jcesguerram** [comment]
> > > ed information? For example, how is this feature performing currently? Are there any pictures or videos available?ED信息？例如，此功能目前表现如何？有图片或视频吗？
> > 
> > 
> > reschedule and question look like this, for example:重新安排和问题如下所示，例如：
> > ![Checkboxes](https://private-user-images.githubusercontent.com/122333212/349191535-d1832715-9a81-446a-8cbc-4bb33eaa0993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTA4MzksIm5iZiI6MTcyMTE1MDUzOSwicGF0aCI6Ii8xMjIzMzMyMTIvMzQ5MTkxNTM1LWQxODMyNzE1LTlhODEtNDQ2YS04Y2JjLTRiYjMzZWFhMDk5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxNzIyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTA0NmRjNjNlMGY5ZTE0ZmQzODQyNzc2ZGYyYThhOWM4NjViYWJjZDBlODE2Nzk1NDRlY2RiYTIzOTFiZjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wQoKZYjSigIQ_RLY3c7E6g2p1B7urCfSWJHMCrUp2Eo)
> 
> It seems like there might be a conflict with some plugins. Could you test it again in a sandbox environment?

mmm how would i do that?

any idea which plugin could be causing the conflict? i tried disbling the tasks plugin to see if it was it, but it wasn't

**Comment by jcesguerram** [comment]
what if i deleted the whole section on 'alternative checkboxes' from the border theme css file? would a plugin with that functionality be able to render them correctly?

**Comment by Akifyss** [comment]
I don't know which part you want to render correctly. If it's the function of some plugins, you can try deleting them.
