### ISSUE TITLE
Theme makes highlighting nodes very hard in graph view

### ISSUE THREAD

**Issue by garbosz** [Akifyss/obsidian-border#249]
normally when you mouse over a node in graph view, the node and its connections will be highlighted, but with border theme highlighting nodes becomes very inconsistent and very hard to do. it looks like the point on the node that detects the hover gets shrunk down into a singular pixel near the bottom of the dot.

**Comment by garbosz** [comment]
enabling the hover line indicator seems to make highlighting nodes much more predictable and reliable.

**Comment by Akifyss** [comment]
This feature is working fine in my environment. Can you test it in a sandbox environment? I suspect it might be an issue with some plugins.

![12](https://github.com/Akifyss/obsidian-border/assets/23567154/c5bfc393-7e27-408c-8358-93292103779c)
