### ISSUE TITLE
【样式问题】左上角关闭样式重叠

### ISSUE THREAD

**Issue by helloChenLei** [Akifyss/obsidian-border#25]
<img width="345" alt="Xnip2023-02-02_20-59-51" src="https://user-images.githubusercontent.com/94668118/216331842-71ee4fcc-f9f2-4b39-bc08-c5c4705b0cc3.png">
<img width="316" alt="Xnip2023-02-02_20-59-45" src="https://user-images.githubusercontent.com/94668118/216331846-bbf51981-0961-4125-bfd8-67091eb385a9.png">
详情参考截图。

**Comment by Akifyss** [comment]
我的电脑是win，不能调试。你那里关闭自动隐藏功能，还会出现重叠问题吗

**Comment by helloChenLei** [comment]
关闭后是这样：
<img width="335" alt="image" src="https://user-images.githubusercontent.com/94668118/216337735-b586359b-e5cd-4bbd-b037-7e56dc2d5b2b.png">

**Comment by Akifyss** [comment]
看来关闭自动隐藏功能后应该是正常的？我希望解决这个问题，但是我没有mac，无法调试，目前对这个问题也无能为力😢。

**Comment by helloChenLei** [comment]
我若线上提供协助，是否可以快速定位问题原因呢？

**Comment by Akifyss** [comment]
能否请你录这样一段视频/截图给我。我想先了解mac上这几个按钮的名字。（mac上好像是cmd + shift +i 开启开发者工具）
![动画](https://user-images.githubusercontent.com/23567154/216356992-951277ab-bbc6-4f28-8a3a-035a08ba3821.gif)

**Comment by helloChenLei** [comment]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/94668118/216470713-a982993e-6ada-43bc-8642-5377bf6892d9.png">
似乎无法选中关闭/最小化/最大化这个icon，光标一直在它的下面，没办法选择上面那层。

**Comment by Akifyss** [comment]
那应该是这三个按钮不允许被修改，这个问题应该是无解了😢。
新版本试图解决一楼第二张图的重叠问题，可以更新试试有没有问题。把tab的自动隐藏给关了，其他两个开着应该可以正常使用。

**Comment by helloChenLei** [comment]
解决了，这个主题我最喜欢的是卡片布局和隐藏tab 😂

**Comment by helloChenLei** [comment]
在这里顺便提一个需求呗，希望在编辑对应文档的时候，支持左侧文件列表自动定位到对应文件。

**Comment by Akifyss** [comment]
是这种效果吗？如果是的话，主题应该是实现不了的，应该需要插件。可以试试Make.md 这个插件，里面有这个功能（需要手动开启）
![动画](https://user-images.githubusercontent.com/23567154/216622658-7c503db8-6494-49d5-b5f4-60fb7ae2b42f.gif)

**Comment by zcysxy** [comment]
我也遇到了这个问题。一般主题解决这个问题的方法都是安装 Electron Window Tweaker 插件调整按钮位置

**Comment by Akifyss** [comment]
我之前安装过这个插件，但是没有看到相关的设置，莫非是只在macos上才显示？

**Comment by Akifyss** [comment]
> 我也遇到了这个问题。一般主题解决这个问题的方法都是安装 Electron Window Tweaker 插件调整按钮位置


我之前安装过这个插件，但是没有看到相关的设置，莫非是只在macos上才显示？

**Comment by zcysxy** [comment]
> 我之前安装过这个插件，但是没有看到相关的设置，莫非是只在macos上才显示？

有可能，这是 mac 上的设置页面
<img width="873" alt="image" src="https://user-images.githubusercontent.com/48207708/222038237-aa22e95c-3b16-4efe-9643-92d33963d822.png">

**Comment by Akifyss** [comment]
> > 我之前安装过这个插件，但是没有看到相关的设置，莫非是只在macos上才显示？
> 
> 有可能，这是 mac 上的设置页面 <img alt="image" width="873" src="https://user-images.githubusercontent.com/48207708/222038237-aa22e95c-3b16-4efe-9643-92d33963d822.png">

win上只有这两项😂，顺便问下可以通过主题css配合这个插件来控制macos交通灯吗
![image](https://user-images.githubusercontent.com/23567154/222038751-686ed60f-27ad-495d-a6f7-4bf309e9a43c.png)

**Comment by zcysxy** [comment]
> win上只有这两项😂，顺便问下可以通过主题css配合这个插件来控制macos交通灯吗 ![image](https://user-images.githubusercontent.com/23567154/222038751-686ed60f-27ad-495d-a6f7-4bf309e9a43c.png)

我看了下它的代码，它好像是用下面两个变量控制的按钮位置。但我试了下用 css snippet 没法控制，它好像只会读取设置里的量。
```css
:root {
  --ewt-traffic-light-x: ${x}px;
  --ewt-traffic-light-y: ${y}px;
}
```

**Comment by Akifyss** [comment]
> > win上只有这两项😂，顺便问下可以通过主题css配合这个插件来控制macos交通灯吗 ![image](https://user-images.githubusercontent.com/23567154/222038751-686ed60f-27ad-495d-a6f7-4bf309e9a43c.png)
> 
> 我看了下它的代码，它好像是用下面两个变量控制的按钮位置。但我试了下用 css snippet 没法控制，它好像只会读取设置里的量。
> 
> ```css
> :root {
>   --ewt-traffic-light-x: ${x}px;
>   --ewt-traffic-light-y: ${y}px;
> }
> ```

好的，非常感谢！ 
那后续应该只能加上一个引导说明让用户自己手动调整了
