### ISSUE TITLE
highlight color bad !!!! >:(((((

### ISSUE THREAD

**Issue by yonatankremer** [Akifyss/obsidian-border#250]
not a fan of the shade in dark mode, doesn't seem like it could be customized with the plugin too. sick theme anyway lol, i'd just like to be able to change da color without cloning the entire theme and changing a css one liner

**Comment by Akifyss** [comment]
Which highlight color are you referring to? Could you provide an image?

**Comment by yonatankremer** [comment]
my bad, it was the italics (didn't notice it colors). tbh nice to have, although i'd imagine the default being the same color as the other text makes more sense
