### ISSUE TITLE
请问落日图片路径如何设置本地路径

### ISSUE THREAD

**Issue by lovecuidong** [Akifyss/obsidian-border#251]
"Appearance-dark@@background-underlying-CSS-dark": "url(\"https://github.com/Akifyss/obsidian-border/blob/main/img/sunset-bg.png?raw=true\") bottom/cover no-repeat fixed",，国内网络github加载慢，请问这个如何设置本地图片的url

**Comment by Akifyss** [comment]
obsidian好像不太能通过css掉用本地图片。目前有两个办法：一是把这张图片下载到国内的某个云，再把链接复制下来。二是把这张图片转为base64格式：https://www.base64-image.de/
