### ISSUE TITLE
[bug] Confliction with Editing Toolbar

### ISSUE THREAD

**Issue by ProudBenzene** [Akifyss/obsidian-border#266]
<img width="1072" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/93238080/7b27cca8-7942-4edc-ba96-932b18ecb480">

When I activate in-note lookup in the Border theme, the lookup box seems to overlap with the interface of the Editing toolbar plugin, and it performs normally while in the default theme.

Maybe it is a small bug? Could you have a fix on it please? Thank yopu for your dedication on the excellent theme!

**Comment by Akifyss** [comment]
The new version has fixed this issue. You can try updating it.
