### ISSUE TITLE
Custom Icons for the Files List are broken on Obsidian v1.6 (Catalyst)

### ISSUE THREAD

**Issue by imgradeone** [Akifyss/obsidian-border#269]
On [Obsidian 1.6.0](https://obsidian.md/changelog/2024-05-09-desktop-v1.6.0/) release, the left sidebar layout gets a major update, but it also breaks the "Custom Icons" features included in the Border Theme. The folder icons of folders on the root directory are completely invisible.

> Currently there's a workaround: simply disable the Custom Icons feature.

**Examples:**

| Custom Icons enabled and broken | Custom Icons disabled |
| ---- | ---- |
| ![image](https://github.com/Akifyss/obsidian-border/assets/30969327/972cab81-8c19-4aba-9ba6-4407f61ee709) | ![image](https://github.com/Akifyss/obsidian-border/assets/30969327/cbcecac7-f2c3-4288-88f2-121baa68fd2c) |

**Comment by Akifyss** [comment]
The new version has fixed this issue. You can try updating it.
