### ISSUE TITLE
DB Folder插件在暗黑模式下的小问题

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#27]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/115944923/217972863-1a6a3f03-5f67-4aae-8f95-fa05107333ca.png">
如图所示，标签文字是亮模式下的显示状态。
大佬新春快乐

**Comment by Akifyss** [comment]
这个貌似不是border主题的问题，我用默认主题也是这样的。貌似插件的作者已经开始着手修复了，你可以关注这个issue：

https://github.com/RafaelGB/obsidian-db-folder/issues/809

https://github.com/users/RafaelGB/projects/7/views/4?filterQuery=%23809+

**Comment by miaoziguan** [comment]
好的，感谢大佬
