### ISSUE TITLE
预设主题 Boundary 的 Tab 栏的颜色问题

### ISSUE THREAD

**Issue by x1a0q1** [Akifyss/obsidian-border#272]
你好 👋
最近在使用 Boundary 这个预设主题发现了一点小问题。

在正常情况（比如桌面环境）下，Tab 栏的颜色显示为白字黑底：
<img width="562" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23022965/c6ec5630-e8ad-44eb-86d0-9fff97dfd870">

而在移动设备（比如iPad）里，Tab 栏的颜色显示为白字灰底：
<img width="425" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23022965/d37642c7-b7cb-4c2e-a9ce-cac3b696601f">

移动设备上的灰底会导致文字难以辨别，希望与桌面环境的颜色进行一个统一🙏

**Comment by Akifyss** [comment]
抱歉目前还没有针对移动端的预设，所以的预设都是针对桌面端的。
由于桌面端和移动端的差异过大，在移动端使用这些预设大概率会有问题。可能之后会有一些针对移动端设计的预设。

**Comment by x1a0q1** [comment]
好的👌完全理解，非常感谢。
