### ISSUE TITLE
BUG: Stacked Tabs Not Sliding with Trackpad Gestures – Style Settings plugin

### ISSUE THREAD

**Issue by aaronjz** [Akifyss/obsidian-border#274]
Hi, 

I am loving the Border theme, but I've noticed when using stacked tabs I'm not able to "slide" between the tabs with the trackpad like I can in other themes. 

I did a little digging and noticed when I turned off the Style Settings plugin, the sliding through the tabs/panes in the stacked tabs with the trackpad worked great. But when I turned the Style Settings plugin back on, I was not able to slide with the trackpad. So something in the Style Settings seems to be interfering with the trackpad gestures. 

Let me know if you need anything else from me. Thanks!

**Comment by Akifyss** [comment]
Is this issue similar to the problem you encountered? If so, you may need to disable the card layout or import the code from the link:
https://github.com/Akifyss/obsidian-border/issues/47
