### ISSUE TITLE
Difficulty of use on the title bar buttons

### ISSUE THREAD

**Issue by iblowmymind** [Akifyss/obsidian-border#275]
Hello,
First of all, just wanted to say- I love the theme! I've been using Minimal for a while before coming across this theme, and I've switched to it and I've been using it ever since.

One minor annoyance I have with the theme, though, is that on the title bar, the window control buttons' interaction boxes do not extend all the way to the corners of the window (or the screen edge when maximized), which leads to awkward interactions where a usual muscle memory flick of a mouse to the upper right corner does not line me up with the close window button, which leads to me having to awkwardly reposition the mouse slightly lower to be able to actually hit the close button, as seen in the GIF attached below.

![Obsidian_mbGMazKJOo](https://github.com/Akifyss/obsidian-border/assets/28228415/43680c02-4656-43b8-8aa9-0b97562f6d82)

For reference, here's the behaviour of typical Windows app title bars, where the buttons actually extend to the corners of the window:

![ApplicationFrameHost_E79grAjzcC](https://github.com/Akifyss/obsidian-border/assets/28228415/92c92279-31a4-4f13-abb8-383ec18d58d1)

Could an option be added so that the window controls extend to the edges of the window?

Thanks!

**Comment by Akifyss** [comment]
The new version has fixed this issue. You can try updating it.

**Comment by iblowmymind** [comment]
Thank you, this is perfect!
