### ISSUE TITLE
白板卡片在双击后显示失真

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#28]
如图所示
<img width="331" alt="image" src="https://user-images.githubusercontent.com/115944923/217973375-ad71f084-9c0d-4cc7-ae3a-1f176fb95c9b.png">

**Comment by Akifyss** [comment]
这个问题我复现不出来，可以录段视频或者提供更多的信息吗

**Comment by miaoziguan** [comment]
[](url)

https://user-images.githubusercontent.com/115944923/218133214-f0efd38a-22e7-405e-9726-afbc0d40ab18.mp4

**Comment by Akifyss** [comment]
很奇怪，我这里触发不了。你那边只有border主题会这样吗？
![动画](https://user-images.githubusercontent.com/23567154/218141452-a4afa133-6423-4ab8-8bad-22425b800f8e.gif)

**Comment by miaoziguan** [comment]
会不会有一种可能就是我自定义了背景导致的？

**Comment by miaoziguan** [comment]
其他主题也是这样，我估计是插件冲突，我去排查一下

**Comment by miaoziguan** [comment]
开启了安全模式就正常了，是插件😂

**Comment by miaoziguan** [comment]
找到原因了，开了Table Enhancer这个插件就会导致显示问题，还是和大佬说下，避免后面的用户走弯路

**Comment by Akifyss** [comment]
好的🫡
