### ISSUE TITLE
自动隐藏动效有闪屏&&建议添加强制隐藏

### ISSUE THREAD

**Issue by 112567** [Akifyss/obsidian-border#281]
隐藏左侧功能区菜单后，容易误触，希望添加鼠标触碰后不会自动弹出的选项（如强制隐藏而非自动隐藏）。
并且自动隐藏的滑动特效好像有点bug,会触发闪屏。
感谢大大🙏🙏

**Comment by Akifyss** [comment]
你好，第一个问题，obsidian 应该会在下一个版本添加这个功能，所以到时候应该可以得到解决。第二个问题闪屏，经我之前的测试应该是一个性能问题，当电脑负载过大就有可能发生，性能问题暂时还是没有很好的解决方法，抱歉。

**Comment by 112567** [comment]
好的，感谢您的回复



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月29日 22:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Akifyss/obsidian-border] 自动隐藏动效有闪屏&&建议添加强制隐藏 (Issue #281) |

你好，第一个问题，obsidian 应该会在下一个版本添加这个功能，所以到时候应该可以得到解决。第二个问题闪屏，经我之前的测试应该是一个性能问题，当电脑负载过大就有可能发生，性能问题暂时还是没有很好的解决方法，抱歉。
