### ISSUE TITLE
开启卡片布局后，在 outline 版块拖拽文章目录标题延迟会非常大

### ISSUE THREAD

**Issue by shimmeris** [Akifyss/obsidian-border#282]
在文件窗口移动文件也会有一定的延迟。

测试视频（仅安装主题及 style settings 插件，开启了卡片布局）：

https://github.com/Akifyss/obsidian-border/assets/17252049/6526ddd1-d70c-4c03-94b8-3f769fcfe56d

**Comment by Akifyss** [comment]
你现在的obsidian 版本是多少，我在最新版试了下，感觉正常
![12](https://github.com/Akifyss/obsidian-border/assets/23567154/4db8f1ea-e07b-4410-91be-cb8a62080088)

**Comment by shimmeris** [comment]
我也是最新版的 1.6.2，系统是 macOS 14.5，新创建的测试库，唯一修改的配制：
<img width="774" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/17252049/0eeaa384-1f3d-4fc7-a421-7d009ada2cce">

**Comment by Akifyss** [comment]
好，我的环境是Windows，我之后测试一下mac os。

**Comment by shimmeris** [comment]
UPDATE：发现使用触控板拖拽没有任何问题，外接鼠标拖拽就存在该延迟。。

**Comment by Akifyss** [comment]
我和你的完全相反，鼠标完全正常，触控板很卡。
猜测原因应该是卡片布局消耗的性能过大，特别是下面这段，目前还没有想到解决方案，抱歉。
<img width="692" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23567154/955022c4-3b6a-469d-b6c1-ad3d1396075f">

**Comment by shimmeris** [comment]
鼠标和触控板的差别有原因吗

**Comment by Akifyss** [comment]
这个感觉是玄学，Obsidian 默认主题也会有这个问题，我这里的表现也是触控板会更卡一些，应该是 Obsidian 本身的问题。
