### ISSUE TITLE
如何更改当前行的背景色？

### ISSUE THREAD

**Issue by li0817** [Akifyss/obsidian-border#287]
想把图中表示当前行的灰色给改了
![image](https://github.com/Akifyss/obsidian-border/assets/27659768/51da4b87-4b1b-4ddd-b975-30b15d51ff1d)
设置中没找到，谷歌了一下css但效果不理想
![image](https://github.com/Akifyss/obsidian-border/assets/27659768/996a9835-18ee-422a-83e9-5da08ed25502)
因为结果成这样了，它把不需要改颜色的行号全改了，反而是唯一需要改颜色的当前行的行号没改
![image](https://github.com/Akifyss/obsidian-border/assets/27659768/b4c84307-0e81-4aa5-957e-f564387ed176)
所以，改当前行的颜色的正确css……该怎么写？

**Comment by li0817** [comment]
对了，顺便问一句标题下方的红色分割线的css是什么
![image](https://github.com/Akifyss/obsidian-border/assets/27659768/4dd40a6d-14ee-4089-b0ad-21e37711df66)
我想对红色分割线试试看不同的颜色、不淡化、以及将线条放在左侧的效果；
![image](https://github.com/Akifyss/obsidian-border/assets/27659768/c2a88522-24a2-4772-b05b-592cee84f47a)
当然，尝试结果依旧不理想……
![image](https://github.com/Akifyss/obsidian-border/assets/27659768/b735b0ff-9df3-4e3f-8ba9-57a6ec96d330)

**Comment by Akifyss** [comment]
可以在这个地方改：
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/884ff935-80c7-43f8-8615-e8d87ae55603)

分割线的css是这一个，可以试试改改样式：
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/ac7a8c07-5dd1-47cb-ae1e-67fa22202d03)

**Comment by li0817** [comment]
@Akifyss 若是在不打开专注模式的情况下，没有办法修改光标所在行的背景色吗？

**Comment by Akifyss** [comment]
打开专注模式，再把透明度拉回1，应该就是你说的这个效果
