### ISSUE TITLE
关于自动隐藏文件名的功能能够自动调节反应时间就好了

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#29]
主要是太灵敏了反而会影响操作，如果可以自动调节反应时间应该会好一点

**Comment by Akifyss** [comment]
自动隐藏文件名？是这个吗
![image](https://user-images.githubusercontent.com/23567154/218247679-d6b12a8a-f4bf-4d72-a230-f346ff7ad475.png)

**Comment by miaoziguan** [comment]
对的，因为误触频率会很高

**Comment by Akifyss** [comment]
在个选项应该已经添加了，可以“components-动效速度”中调整。也可以选择把上面那个选项改为fixed

**Comment by miaoziguan** [comment]
好的，感谢大佬🙏
