### ISSUE TITLE
Missing vault switcher and settings icons

### ISSUE THREAD

**Issue by amperag** [Akifyss/obsidian-border#292]
Hi there, I'm not sure if I did something wrong or if it's a bug with the theme:

(1) In Obsidian 1.6 the sidebar has been redesigned. There should be a new vault switcher at the bottom.
**But I can't seem to find it.**

(2) How do I access the settings? As a workaround I now open the settings via the command pallette.
**I can't seem to find the settings icon.** 

Greetings!

PS: This is how my sidebar looks at the moment (file and folder names removed):
![grafik](https://github.com/Akifyss/obsidian-border/assets/61867589/2583b33c-1077-4736-9d36-2cd6dbb0f516)

**Comment by Akifyss** [comment]
My environment is functioning normally. Could you try it in a sandbox? I suspect the issue might be caused by a plugin. Normally, it should work like this:
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/a9f6305e-219b-43e6-8aa1-6f30cedbbc23)
