### ISSUE TITLE
[BUG] Theme zoom function is bugged when used with Obsidian Image Toolkit Plugin 

### ISSUE THREAD

**Issue by ianTevesAcc** [Akifyss/obsidian-border#293]
When the theme is used in conjunction with the [Image Toolkit Plugin](https://github.com/sissilab/obsidian-image-toolkit), It prevents the Image toolkit from functioning. You can't work around it because if you turn off the image zoom functionality through Obsidian Styles plugin, it blocks zooming for both the theme and the plugin.

To reproduce:
1. activate and install [Obsidian Image Toolkit](https://github.com/sissilab/obsidian-image-toolkit) and Obsidian Border theme
2. paste an image into a note
3. restart obsidian
4. left click the image

Expected Behavior: The Obsidian Image Toolkit plugin is activated, so the image is zoomed in. (Or there is an option in the settings in order to override the Border theme zoom functionality to be disabled in order for the plugin zoom functionality to be the one that functions)

Result: The Border theme zoom functionality is the one that functions and there is no way to turn it off.

Additional: I don't know if I should put this as a feature request or a bug as its not really a bug, its just an incompatibility to the Image Toolkit plugin. But basically the feature request is to add a way to disable the Border theme zoom functionality, so that I can use the zoom functionality of the Image Toolkit plugin instead.

**Comment by Akifyss** [comment]
I don't quite understand what you mean by "It prevents the Image toolkit from functioning." Could you please provide some images or video information? Because when I disable the options below, I don't notice much difference using the Image Toolkit Plugin under both border theme and default theme.
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/0c016192-72d9-4915-bf8f-b28aeb3d9049)

**Comment by ianTevesAcc** [comment]
Sorry 😅. I tried to record a video of what happened but luckily the problem solved itself somehow. 
I tried that solution already and it didn't work. Weirdly for some reason, it works now.
Sorry for the hassle. But thank you for the help!
