### ISSUE TITLE
Nested blockquote accent lines not consistent with parent blockquote

### ISSUE THREAD

**Issue by batrand** [Akifyss/obsidian-border#295]
- Open sandbox vault and install Border
- Create a blockquote with nested blockquotes, like so:

```
> TITLE
> > subtitle subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  
> > > subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle  subtitle   
```

Result:
![image](https://github.com/Akifyss/obsidian-border/assets/8514709/e7669715-68fa-4a13-856f-4b4ce002c124)
- The left accent lines of the children blocks extend further down compared to the parent's left accent line
- The left accent lines of the children blocks don't have any radius, while the parent's does have radius

**Comment by Akifyss** [comment]
I just checked, and the blockquote accent lines have a rather complex structure in the DOM tree. This makes it nearly impossible to style them with CSS alone to match the parent blockquote. Sorry.
