### ISSUE TITLE
Can't find it in the obsidian third-party plug-in market

### ISSUE THREAD

**Issue by muyiacc** [Akifyss/obsidian-border#299]
Searching for Border did not result in any plugins appearing

**Comment by muyiacc** [comment]
![图片](https://github.com/Akifyss/obsidian-border/assets/115904774/c2fd0619-b900-4e7c-903b-76ec58fdd3ce)

**Comment by Akifyss** [comment]
<img width="1081" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23567154/358187fd-3c3c-4da8-9beb-97e1af939890">

**Comment by muyiacc** [comment]
okay,think you
