### ISSUE TITLE
希望大佬能添加一个纯黑主题模式和暖白主题模式

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#3]
如题所示，感恩大佬

**Comment by Akifyss** [comment]
这个以后应该会实现的

**Comment by Akifyss** [comment]
纯黑模式已添加，可以再style settings里的 “色彩-暗色模式背景” 更改。
暖白主题可以先将“色彩-亮色模式背景”改为“adapt to accent color”，再选用一个暖色调的主题色即可实现。
![image](https://user-images.githubusercontent.com/23567154/210532204-d7dab9e2-1408-4503-aeca-f28fdac7a361.png)

**Comment by miaoziguan** [comment]
> 纯黑模式已添加，可以再style settings里的 “色彩-暗色模式背景” 更改。 暖白主题可以先将“色彩-亮色模式背景”改为“adapt to accent color”，再选用一个暖色调的主题色即可实现。 ![image](https://user-images.githubusercontent.com/23567154/210532204-d7dab9e2-1408-4503-aeca-f28fdac7a361.png)

好的，感谢🙏大佬

**Comment by miaoziguan** [comment]
新的小问题。
如图所示。
<img width="160" alt="image" src="https://user-images.githubusercontent.com/115944923/210534873-e4640b87-7ad0-4d75-93c3-b87be84e0583.png">
<img width="279" alt="image" src="https://user-images.githubusercontent.com/115944923/210535072-3dc6cef5-ca64-42b6-b0d8-5a57accb2265.png">
当改变色值以后，在亮模式下，ui的对比度略微不够清晰，影响阅读

**Comment by Akifyss** [comment]
这个确实是。应该是主题色选得太浅了，这上面的颜色是跟着主题色走的。可以把主题色的色值改得深一些。我之后可能会添加一些自定义选项来改善这个问题。

**Comment by miaoziguan** [comment]
好的，期待大佬的打磨，奥力给。

**Comment by Akifyss** [comment]
整体UI的颜色是基于默认主题色的亮度和饱和度来计算的，一旦选的主题色偏得太远(比如太深或者太浅)，生成的UI颜色就会很深或者很浅，对比度就会出现问题。新版本中在style settings中添加了 色彩-自定义颜色 这个选项，可以去手动调整来改善对比度。

**Comment by miaoziguan** [comment]
试用了，非常完美！
