### ISSUE TITLE
Restore default light preset

### ISSUE THREAD

**Issue by nicosomb** [Akifyss/obsidian-border#30]
Hello, 

Thank you for your theme. 
To restore default light theme, is that enough to click on the "reset all settings to default" icon in "style settings" section?

**Comment by Akifyss** [comment]
Hi, If you just want to restore default light theme，this button should work.

![image](https://user-images.githubusercontent.com/23567154/218430537-0f724322-697e-4a92-90a2-6476efb462fe.png)

**Comment by nicosomb** [comment]
Thank you. 

I think that
