### ISSUE TITLE
Support for Typewriter Mode's plugin's Full Screen mode.

### ISSUE THREAD

**Issue by batrand** [Akifyss/obsidian-border#301]
Hello! The theme doesn't seem to be working correctly with Full Screen mode from this plugin https://github.com/davisriedel/obsidian-typewriter-mode 

Steps to reproduce:
- Open Sandbox vault
- Install themes: Border and Minimal (for comparison)
- Install plugin (Typewriter mode, David Riedel)
- Ctrl-P -> toggle fullscreen writing mode
- Switch between Border and Minimal to see the difference.

Minimal light:
![image](https://github.com/Akifyss/obsidian-border/assets/8514709/7c154d92-b019-40fe-b2c1-38eb70a479ec)

Border light:
![image](https://github.com/Akifyss/obsidian-border/assets/8514709/d8941676-c873-47fb-aed9-320a65cea2f2)

Minimal dark:
![image](https://github.com/Akifyss/obsidian-border/assets/8514709/ad14e69e-123f-4fad-a452-b64543ee4481)

Border dark (the background is complete black instead of the dark colour of the theme)
![image](https://github.com/Akifyss/obsidian-border/assets/8514709/d74ca12e-3a0d-43f3-95a4-777e86457adf)
Border dark default colour outside of fullscreen mode for comparison:
![image](https://github.com/Akifyss/obsidian-border/assets/8514709/b097007f-01e0-467a-8037-28a41136ffba)

**Comment by Akifyss** [comment]
The new version has fixed this issue. You can try updating it.
