### ISSUE TITLE
Is that possible to change the selected text background color at code block?

### ISSUE THREAD

**Issue by jiangaq** [Akifyss/obsidian-border#304]
If I choose dark theme, like dracula for code block, it will not show any background color on selected text. If choose light theme, it works.

**Comment by Akifyss** [comment]
Can I take a look at the screenshot?

If you can't see any background color, reinstalling Obsidian might solve the problem.

**Comment by jiangaq** [comment]
if choose Dracula :
<img width="810" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/26076033/5f68dba2-35cc-4d74-9926-97b92a26144b">

If choose Customize:
<img width="817" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/26076033/7f8076ca-cd3b-44e3-bb7a-3817c3fff1f2">

**Comment by Akifyss** [comment]
重新下载安装 Obsidian 试试呢？

How about reinstalling Obsidian?

**Comment by jiangaq** [comment]
可是我换个主题就好的，应该和obsidian没关系的吧

换Maple：
<img width="341" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/26076033/349378da-ee40-42cb-831d-f6fba39135d7">

**Comment by Akifyss** [comment]
确实是有关系的，可以试试

**Comment by jiangaq** [comment]
> 确实是有关系的，可以试试

关了Style setting插件就好了，应该是里面哪个设置问题，可是我没找到

**Comment by Akifyss** [comment]
好吧，但其实重新安装 Obsidian确实是有效的，所有反馈这个问题的人都成功了
