### ISSUE TITLE
Heading colors instead of vertical bar

### ISSUE THREAD

**Issue by jcesguerram** [Akifyss/obsidian-border#306]
Would it be possible to have headings with different font color instead of (or as an option to) the vertical bars?

**Comment by Akifyss** [comment]
If I understand correctly, you should be able to set in style settings
<img width="771" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23567154/01d95b3e-0cab-4ee0-b4f1-ba36e9c78740">

**Comment by jcesguerram** [comment]
oh i hadn't seen that, thanks a lot!
