### ISSUE TITLE
Bold text color

### ISSUE THREAD

**Issue by jcesguerram** [Akifyss/obsidian-border#307]
This is probably a dumb question but I haven't figured it out: When i have txt in bold the text appears in a red font. How can i change that?
And how can i change it so that it adjusts to it's 'surroundings'? (for example, bolded text in a green callout would appear green)

**Comment by jcesguerram** [comment]
> This is probably a dumb question but I haven't figured it out: When i have txt in bold the text appears in a red font. How can i change that? And how can i change it so that it adjusts to it's 'surroundings'? (for example, bolded text in a green callout would appear green)

... and relatedly, how can i make titles in callouts appear less thick?

**Comment by jcesguerram** [comment]
i figured this out :)

**Comment by comolake** [comment]
+1. how did u fix it?

**Comment by jcesguerram** [comment]
> +1. how did u fix it?

the bold text in red? i went to the theme.css file and looked for the section on italics and bold and just erased the color part
