### ISSUE TITLE
What are the options for blockquote backgrounds?

### ISSUE THREAD

**Issue by jcesguerram** [Akifyss/obsidian-border#308]
Where can i find options for blockquote backgrounds?

**Comment by Akifyss** [comment]
<img width="842" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23567154/370656c8-67a0-4287-896f-f5a0db2ce88d">

**Comment by jcesguerram** [comment]
that's the only option?

**Comment by Akifyss** [comment]
What "only option"? Don't you need options for blockquote backgrounds?

**Comment by jcesguerram** [comment]
i do. and you point me to one that says 'transparent' so i'm wondering wwhat else i can put in there.

**Comment by Akifyss** [comment]
This is just the value I filled in personally. It is actually an input box that can fill in any css background value. Please refer to: https://developer.mozilla.org/en-US/docs/Web/CSS/background

**Comment by jcesguerram** [comment]
ah i see, thanks!
one question, if i replaced the blockquotes section in the theme.css file with something like the following would it work?

blockquote{
  display:block;
  background: #fff;
  padding: 15px 20px 15px 45px;
  margin: 0 0 20px;
  position: relative;
  
  /*Font*/
  font-family: Georgia, serif;
  font-size: 16px;
  line-height: 1.2;
  color: #666;
  text-align: justify;
  
  /*Borders - (Optional)*/
  border-left: 15px solid #c76c0c;
  border-right: 2px solid #c76c0c;
  
  /*Box Shadow - (Optional)*/
  -moz-box-shadow: 2px 2px 15px #ccc;
  -webkit-box-shadow: 2px 2px 15px #ccc;
  box-shadow: 2px 2px 15px #ccc;
}

blockquote::before{
  content: "\201C"; /*Unicode for Left Double Quote*/
  
  /*Font*/
  font-family: Georgia, serif;
  font-size: 60px;
  font-weight: bold;
  color: #999;
  
  /*Positioning*/
  position: absolute;
  left: 10px;
  top:5px;
}

blockquote::after{
  /*Reset to make sure*/
  content: "";
}

blockquote a{
  text-decoration: none;
  background: #eee;
  cursor: pointer;
  padding: 0 3px;
  color: #c76c0c;
}

blockquote a:hover{
 color: #666;
}

blockquote em{
  font-style: italic;
}

**Comment by Akifyss** [comment]
I tried it. It doesn't seem to work.

**Comment by jcesguerram** [comment]
> I tried it. It doesn't seem to work.

oh ok, well thank you very much for your help!
