### ISSUE TITLE
Hovered line indicator

### ISSUE THREAD

**Issue by nicosomb** [Akifyss/obsidian-border#31]
It's me again. 

As showed here https://github.com/Akifyss/obsidian-border#active-line-highlight-and-hovered-line-indicator, I'd like to see an indicator in the gutter editor (at the left of each line). 
All is ok in the configuration (the 2 settings are not disabled). 

How can I fix that please?

**Comment by Akifyss** [comment]
Hi, sorry I don't quite understand what "gutter editor" refers to, can you provide a screenshot or more information please?

**Comment by nicosomb** [comment]
Sorry, it's the used term for IDE 😉 
In the screenshot, I mean the blue vertical line : 

![Capture d’écran 2023-02-13 à 17 43 06](https://user-images.githubusercontent.com/121870/218518873-ce182f3f-ab2c-478c-b21c-55b34e0cd06d.png)

**Comment by Akifyss** [comment]
Sorry, I am not a proficient speaker of English😂. So you can't see the blue vertical line on your side?

**Comment by nicosomb** [comment]
That's right : I can't see it.

**Comment by Akifyss** [comment]
That's weird, can you report your system and theme version? 
You could probably try downloading and reinstalling obsidian (as I use :has() for this function, only a reinstalled and downloaded obsidian has this feature).

**Comment by nicosomb** [comment]
New info: it works on my linux computer. Not on my macbook.

**Comment by Akifyss** [comment]
This feature should not be OS related, my guess is that this feature may require Electron 21:

https://github.com/obsidianmd/obsidian-releases/releases/tag/v1.1.8-E21

**Comment by nicosomb** [comment]
Ok i will have a look (it’s okay on my iPhone too)

**Comment by nicosomb** [comment]
I have Obsidian 1.1.12 on my macos.

**Comment by Akifyss** [comment]
I'd like to confirm that you have re-downloaded and installed your obsidian from the official website? If you have been using obsidian since before 1.1.8, you may need to re-install obsidian from the official website to upgrade to Electron 21.

**Comment by nicosomb** [comment]
It works :tada: Thank you! 

My installer was still on 1.0.0 version un fact.
