### ISSUE TITLE
Border 主题和 Editing Toolbar 同时安装出现卡顿

### ISSUE THREAD

**Issue by ZichaoXiong** [Akifyss/obsidian-border#314]
开发者您好，macOS 下同时安装 Border 1.9.8 和 Editing Toolbar 2.4.16 会产生严重的卡顿现象，包括输入内容无法显示，设置界面闪烁缺失等等。请问有办法解决吗？

图1:无法显示输入内容
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/36321918-dcea-4775-ac60-0ad6a45eb2a3">

图2:设置内容缺失
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/d5d090a4-d6ac-4b43-9e9e-7255be76d563">

**Comment by Akifyss** [comment]
这个主题确实有性能问题。而且这个性能问题是和某些功能绑定的，要解决性能问题，需要把这些功能的代码移除掉，可以参考这个issue：#102。性能问题除了删除代码外可能没有什么解法，抱歉。

**Comment by ZichaoXiong** [comment]
按照 #102 所示的方法删除部分代码后仍然卡顿，但是在非全屏状态下情况稍好。请问假如只想保留 markdown 编辑区域文本渲染的外观的话，应当保留哪些代码呢？

**Comment by Akifyss** [comment]
如果只保留编辑区的话，只保留这些区块就可以了
![image](https://github.com/user-attachments/assets/8f003237-2995-4bab-b9a6-4391adf41262) editor后边
![image](https://github.com/user-attachments/assets/719de41d-de6a-4816-9855-7be761612e1d)  mobile前边

以及以下区块：
![image](https://github.com/user-attachments/assets/851f2f24-d147-4da6-9048-9fefff6b2096)

**Comment by ZichaoXiong** [comment]
这样确实可以解决问题，非常感谢。
