### ISSUE TITLE
[FEATURE]: Follow prefers-reduced-motion to remove animations

### ISSUE THREAD

**Issue by Rikiub** [Akifyss/obsidian-border#318]
It would be useful to users which don't use **Style Settings Plugin** and don't want animations.
It's applied as system level, like you can read in **MDN documentation**.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by Akifyss** [comment]
The new version has fixed this issue. You can try updating it.
