### ISSUE TITLE
突然灵机一动？有个巧妙的想法💡

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#32]
<img width="858" alt="image" src="https://user-images.githubusercontent.com/115944923/218723322-757c8328-3d4a-460c-b748-08a44d20a412.png">
如图所示，大佬可以多开发几个图案，或者搞个自定义图案。
只是建议（狗头）

**Comment by Akifyss** [comment]
这只是空状态插图，类似下面的这种，用来直观地提醒用户没有内容或数据，感觉不太需要自定义😶‍🌫️？

![image](https://user-images.githubusercontent.com/23567154/218728392-c927ec36-2b2c-4667-8a62-0ab653643860.png)

**Comment by miaoziguan** [comment]
嗯，在我看来，这是人文主义的一种体现方式，它可能并不重要，但是足够有趣。但考虑到大佬的时间和精力所以也是提一个或许可以去选择实施的建议（狗头）。用户可以自定义出自己想要的logo，也蛮好玩的。

**Comment by Akifyss** [comment]
如果实在想要自定义的话，可以导入下面这个CSS 片段，再在style settings中手动更改

[customize-empty-state-image.zip](https://github.com/Akifyss/obsidian-border/files/10773713/customize-empty-state-image.zip)

**Comment by miaoziguan** [comment]
好的，感谢大佬
