### ISSUE TITLE
Callout内容块颜色可以调整

### ISSUE THREAD

**Issue by ProudBenzene** [Akifyss/obsidian-border#325]
Callout Style1、2、4的内容块在浅色模式下均为白色，不能和背景颜色进行较好的融合，比较突兀，有些许影响观感；深色模式下就没有这个问题：

<img width="628" alt="iShot_2024-08-19_12 17 27" src="https://github.com/user-attachments/assets/c0563082-1067-45a2-ae2c-ead05879690e">
<img width="629" alt="iShot_2024-08-19_12 17 48" src="https://github.com/user-attachments/assets/76f0eefc-69de-4098-a57a-923b69cffa6c">

希望作者大大可以稍微调整一下Callout内容块部分在浅色模式下的配色～

**Comment by Akifyss** [comment]
背景的内容可以在这里调整；
![image](https://github.com/user-attachments/assets/d4ef622a-e601-48c9-b3b5-89bc06a43bec)

---

callout style 的参数可以参照此图:
![image](https://github.com/user-attachments/assets/c303c08b-03dc-45ef-bbab-0ba0a82eefb6)
