### ISSUE TITLE
suggest : release and change log

### ISSUE THREAD

**Issue by mystery4f** [Akifyss/obsidian-border#327]
Hello Akifyss, can you release the border theme version when you update it, and provide the changelog, because I am very concerned about the new changes.

**Comment by wxmup** [comment]
me,too

**Comment by Akifyss** [comment]
You can see the information for each update here, but they are actually just some minor optimizations/fixes, so there's no need to pay too much attention to it.https://github.com/Akifyss/obsidian-border/commits/main
