### ISSUE TITLE
Width of the text

### ISSUE THREAD

**Issue by talvi-frsch** [Akifyss/obsidian-border#339]
Hello!
I would like to know if it's possible to manage the width of the text panel in the Style Settings plugin?
Thank you!

![image](https://github.com/user-attachments/assets/2c017374-620c-4c03-a8ab-fc04d5c7d2fd)

**Comment by Akifyss** [comment]
You can adjust the text width in this section:
![image](https://github.com/user-attachments/assets/f06891da-6c10-406f-ba6b-f46253165c51)
