### ISSUE TITLE
中文字重不生效

### ISSUE THREAD

**Issue by GITHubSiWei** [Akifyss/obsidian-border#34]
大佬，主题太漂亮了，就是字重在设置里设为900后，只有英文生效，中文不生效，不知道是字库问题还是，主题设置有问题。
![2023-02-18_21-05](https://user-images.githubusercontent.com/17538796/219867529-306d72ca-3639-4f60-9a2f-3a9fac1555a0.png)

**Comment by Akifyss** [comment]
你好，我感觉应该是字库的问题。感觉绝大多数中文字体应该没有那么多的字重支持（不然设计工作量太大了）。我用的思源黑体设置的字重是有效的。
![image](https://user-images.githubusercontent.com/23567154/219868255-f3111f06-a4ef-4eff-bbf4-9bae70d2ca43.png)
