### ISSUE TITLE
Line highlights stopped functioning

### ISSUE THREAD

**Issue by Qupci** [Akifyss/obsidian-border#35]
Hi! Line highlighting stopped functioning after some update (probably a week ago). Highlighting doesn't appear on lines anymore with the active line or by cursor hovering. In the Style Settings section, "Emphasis on line" toggles do not affect anything. Border theme installation on the fresh Vault has the same issue.

**Comment by Akifyss** [comment]
This is strange. Here is a similar issue that you can refer to：https://github.com/Akifyss/obsidian-border/issues/31
Anyway，you can try the solution here：
![image](https://user-images.githubusercontent.com/23567154/220233724-5fdc233d-7ccc-4ad5-978c-b3e408590212.png)

**Comment by Qupci** [comment]
> This is strange. Here is a similar issue that you can refer to：#31 Anyway，you can try the solution here： ![image](https://user-images.githubusercontent.com/23567154/220233724-5fdc233d-7ccc-4ad5-978c-b3e408590212.png)

Reinstalling Obsidian fixed my issue. Thank you!
