### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by hongfei0501** [Akifyss/obsidian-border#354]
是否可以帮忙做一个护眼模式？

**Comment by Akifyss** [comment]
目前已经有了一个护眼预设了：https://github.com/Akifyss/obsidian-border/blob/main/presets/Eye-friendly.json；可以导入试试；
不满意的话，这个主题是可以自定义背景和各种颜色的；自己调出来的效果应该会更称心

**Comment by hongfei0501** [comment]
好的，非常感谢！
