### ISSUE TITLE
Search boxes on sidepane views overlap other elements when "Auto hide header icons in sidepane" is on

### ISSUE THREAD

**Issue by juanangelpes** [Akifyss/obsidian-border#359]
When the "Hide header icons in sidepane" option is enabled in the Obsidian theme settings, search boxes on sidepane views (e.g. Outline, Backlinks, All Properties) overlap with other elements in the interface.

<img width="787" alt="image" src="https://github.com/user-attachments/assets/55e12b73-eb06-42f9-ac74-1fd1fba6690c">
<img width="373" alt="image" src="https://github.com/user-attachments/assets/27e41698-8246-4be0-a29e-e6891ecebc4f">
<img width="291" alt="image" src="https://github.com/user-attachments/assets/a463e23a-b577-47f1-bc11-2f39767e34db">
<img width="286" alt="image" src="https://github.com/user-attachments/assets/e7ad272a-f800-4a04-8fcc-859cb024e1b1">

**Comment by Akifyss** [comment]
The new version has fixed this issue. You can try updating it.

**Comment by juanangelpes** [comment]
great, thank you!
