### ISSUE TITLE
Them settings in Style Setting should have one main section and the subsection

### ISSUE THREAD

**Issue by danieltomasz** [Akifyss/obsidian-border#36]
Hi 
great  work with making the plugin!

I obserwed the the settings of the theme dont have a on "border" place but are placed as several separate items  into "Style Settings"
<img width="844" alt="image" src="https://user-images.githubusercontent.com/7980381/220218007-dcf79265-9aae-4371-86a7-1c788abb28ac.png">

Would be nice to have one setting option  that contain  all  the rests of options, like other plugins

**Comment by Akifyss** [comment]
Hi. Some themes (like minimal) also have many main sections.
![image](https://user-images.githubusercontent.com/23567154/220235589-04c600df-ec98-42a7-9a71-b867f7efd304.png)
This removes a hierarchy and ensures that users can quickly set theme options without having to click too many times.

The border theme has **Appearance** presets for users to import, before importing users usually need to set the **Appearance** option (only one of them) to default. If there is only one main section, users can only set all options to default, which requires users to manually set other overridden options later, which is not good UX.

**Comment by danieltomasz** [comment]
Thanks for explaining your motivation!
As this kind of UX decision is always a bit subjective I will not argue further  for my personal preferences:) 
 
Again thank you for making  a such nice theme :)
