### ISSUE TITLE
代码块文本宽度不一

### ISSUE THREAD

**Issue by XinyongGuo** [Akifyss/obsidian-border#361]
![image](https://github.com/user-attachments/assets/c6267c97-e546-4c5d-87d5-94e0a601cae7)
应该是“-”被识别成换行并且显示时两端对齐，使得空格被拉长，就像双栏论文的参考文献一样。
切换其他的主题显示正常，设置里没找到相关选项

**Comment by Akifyss** [comment]
可能是这个选项的问题，关掉应该就可以了
<img width="793" alt="image" src="https://github.com/user-attachments/assets/e4c37b26-e72e-46cf-b79f-1dafe7379b87">
