### ISSUE TITLE
在Obsidian1.7.4上特别特别卡，不能用的程度

### ISSUE THREAD

**Issue by Y-ASLant** [Akifyss/obsidian-border#362]
我录了[视频](https://aslant-api.cn/d/ASLant/ASLant/Z-Backup/AGC/2024-10-31_14-44-21.mkv?sign=frv14q3XFOcxuJSxgvwWw-AkDArh3wCd1JW51stYtCY=:0)
作者大大可以看一下 ，大致就是在1.7.4上最最最卡的地方是文件列表，超级不跟手，禁用所有插件后，依旧不跟手!!!!!，但是比现在好的多的多，其次就是文中阅读长一点的mark down文件，卡的加载查不出来，帧率极低，在之前的版本也不跟手 跟现在这个版本禁用所有插件 一样 虽然也不跟收但是能用，希望作者优化精简一下，我也尝试卸载重新安装主题 恢复主题默认设置 问题依旧，（电脑配置AMD6800H，Windows11专业版24H2，显卡3070，内存ddr5 5600Mhz）不确定是我电脑问题还是主题问题

**Comment by Y-ASLant** [comment]
都是开着的，我现在将我在使用的笔记仓库打包了，你可以试一下，我是非常非常卡的，里面有着我用到的插件和及字体
![image](https://github.com/user-attachments/assets/24b62610-5680-4ff9-8c38-5233f88d2202)
[Obsidian测试仓库](https://aslant-api.cn/d/ASLant/ASLant/Z-Backup/APK/Test_Obsidian_Local.7z?sign=wD9QwSpAtgbDEFCLM_LqRwX9h0PZszJYZIG4KRLCW3Y=:0)

**Comment by Y-ASLant** [comment]
> ![12](https://private-user-images.githubusercontent.com/23567154/382001054-5259ecd3-ce66-4300-bd20-1201a8703e93.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Njc1MzQsIm5iZiI6MTczMDQ2NzIzNCwicGF0aCI6Ii8yMzU2NzE1NC8zODIwMDEwNTQtNTI1OWVjZDMtY2U2Ni00MzAwLWJkMjAtMTIwMWE4NzAzZTkzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEzMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYjFhZmE4ZGEyOTk3ZjVhZDRhOTU4NGU0Y2IxNGJlYzk0ODA2ZmVkYTI1ZGM2ZTJmODk2ZmEyMmU5ZjJkYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EKj09KVuzedF-BoYUZmLM7As-kU6_RxARtKIgpYMNcA) [ ![12](https://private-user-images.githubusercontent.com/23567154/382001054-5259ecd3-ce66-4300-bd20-1201a8703e93.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Njc1MzQsIm5iZiI6MTczMDQ2NzIzNCwicGF0aCI6Ii8yMzU2NzE1NC8zODIwMDEwNTQtNTI1OWVjZDMtY2U2Ni00MzAwLWJkMjAtMTIwMWE4NzAzZTkzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEzMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYjFhZmE4ZGEyOTk3ZjVhZDRhOTU4NGU0Y2IxNGJlYzk0ODA2ZmVkYTI1ZGM2ZTJmODk2ZmEyMmU5ZjJkYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EKj09KVuzedF-BoYUZmLM7As-kU6_RxARtKIgpYMNcA) ](https://private-user-images.githubusercontent.com/23567154/382001054-5259ecd3-ce66-4300-bd20-1201a8703e93.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Njc1MzQsIm5iZiI6MTczMDQ2NzIzNCwicGF0aCI6Ii8yMzU2NzE1NC8zODIwMDEwNTQtNTI1OWVjZDMtY2U2Ni00MzAwLWJkMjAtMTIwMWE4NzAzZTkzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEzMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYjFhZmE4ZGEyOTk3ZjVhZDRhOTU4NGU0Y2IxNGJlYzk0ODA2ZmVkYTI1ZGM2ZTJmODk2ZmEyMmU5ZjJkYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EKj09KVuzedF-BoYUZmLM7As-kU6_RxARtKIgpYMNcA) [ ](https://private-user-images.githubusercontent.com/23567154/382001054-5259ecd3-ce66-4300-bd20-1201a8703e93.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Njc1MzQsIm5iZiI6MTczMDQ2NzIzNCwicGF0aCI6Ii8yMzU2NzE1NC8zODIwMDEwNTQtNTI1OWVjZDMtY2U2Ni00MzAwLWJkMjAtMTIwMWE4NzAzZTkzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEzMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYjFhZmE4ZGEyOTk3ZjVhZDRhOTU4NGU0Y2IxNGJlYzk0ODA2ZmVkYTI1ZGM2ZTJmODk2ZmEyMmU5ZjJkYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EKj09KVuzedF-BoYUZmLM7As-kU6_RxARtKIgpYMNcA) 感觉不至于啊，我的是7800X3D，也是24H2，电脑性能上理论上应该差距不大，但是感觉不算卡；
> 
> 你有开启这个选项吗？ ![image](https://private-user-images.githubusercontent.com/23567154/382002394-96027f00-ef05-4404-9c7d-6bfbfb969c43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Njc1MzQsIm5iZiI6MTczMDQ2NzIzNCwicGF0aCI6Ii8yMzU2NzE1NC8zODIwMDIzOTQtOTYwMjdmMDAtZWYwNS00NDA0LTljN2QtNmJmYmZiOTY5YzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEzMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YmE1ZTRjYmYwYTg0ODUyYWM1YzRkYmUwNGViYmFjNzgzMTZhODlkNzAzM2FiMzZmZTFmZDkxMWQ4YWIxYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wmz1AS800VgBC9CKNDiM6AuXRAaM4PjdFY-oDg6snrg)

都是开着的，这是我的[obsidian仓库](https://aslant-api.cn/d/ASLant/ASLant/Z-Backup/APK/Test_Obsidian_Local.7z?sign=wD9QwSpAtgbDEFCLM_LqRwX9h0PZszJYZIG4KRLCW3Y=:0) 不只是列表卡顿严重，包括markdown文件内容的渲染，
![image](https://github.com/user-attachments/assets/8e99efd7-7527-4f57-a683-7bf12670451d)

**Comment by Akifyss** [comment]
估计是Code Styler 这个插件的原因，关闭之后，性能会好很多
![12](https://github.com/user-attachments/assets/23e199a7-a73d-4f9a-9be4-c82367f49676)

![image](https://github.com/user-attachments/assets/bb551fb7-8006-4786-956b-f75ecc982dca)

**Comment by Y-ASLant** [comment]
情况是有所缓解，可能这个插件与主题冲突，因为我换成默认主题 未有丝毫影响，这个主题在1.7.4上比在1.6.7上更卡

**Comment by Akifyss** [comment]
最近主题是没有什么实质性更新的，不清楚什么原因。这个主题确实会比默认的卡，但是目录的异常卡顿我倾向是和主题没什么关系的，因为我原本的不卡，装了code styler之后也变得巨卡，去code styler 的repo 看到也有人再提卡顿的issue。 所以至少目录的卡顿我也没法帮到你什么，抱歉

**Comment by Y-ASLant** [comment]
好的 谢谢
