### ISSUE TITLE
dark mode下光标是黑色看不清楚

### ISSUE THREAD

**Issue by jiangaq** [Akifyss/obsidian-border#367]
我加了这个正常了，不知道对不对，能不能下次修复下加到css里去：

.theme-dark {
    caret-color: auto; 
}

**Comment by Akifyss** [comment]
能提供截图吗，因为我这边还算清楚，而且主题代码里也没有改caret-color，我想看看是不是某个预设的原因
![image](https://github.com/user-attachments/assets/8f68a6e7-621d-4289-9b08-72b402311e09)

**Comment by jiangaq** [comment]
奇怪白天再看，又正常了，我没动过什么，昨晚就是黑暗模式光标是黑色的

**Comment by Akifyss** [comment]
你现在再切换到暗色模式呢？

**Comment by jiangaq** [comment]
我白天也是暗色模式的，现在正常

**Comment by Akifyss** [comment]
那就不太清楚了，目前无法定位问题，不太好解决抱歉
