### ISSUE TITLE
Tab Title Bar -> Fixed (obsidian default) is not working

### ISSUE THREAD

**Issue by pckc** [Akifyss/obsidian-border#37]
Following the path:
Style Settings > Components > Tab Title Bar -> Fixed (obsidian default) 

The fixed option isn't working. The plugin will always use the autohide function.

**Comment by Akifyss** [comment]
This feature is working fine for me, could you please provide me with more information. 
For example, some screenshots or videos that reflect the problem, I also want to check your installer version (not APP current version) to troubleshoot the problem

**Comment by pckc** [comment]
I'm sorry if I misinterpreted the feature. 
I'm using installer version 1.1.8

While "Show Tab Title Bar" is on, both "Tab Tile Bar" options will autohide.


![Obsidian_56SB6Y7hk0](https://user-images.githubusercontent.com/54250441/220762094-b1fe2143-569a-4c87-a8a9-e017e00cabe1.gif)

**Comment by Akifyss** [comment]
This is strange. The normal reaction should be like this
![1](https://user-images.githubusercontent.com/23567154/220810478-429e23df-84e9-4792-a8e0-8c57c6964ee7.gif)

I'm not sure if this is installer version related, but you could still try reinstalling obsidian to upgrade the installer version first.
![image](https://user-images.githubusercontent.com/23567154/220810120-63828b31-ce9d-4b42-add4-b30ce8277a11.png)

**Comment by pckc** [comment]
I have tried to disable snippets, plugins, and whatsoever but I have no idea of what kind of variables might be causing this.

I also reinstalled again, but nothing changed.
![image](https://user-images.githubusercontent.com/54250441/221027976-19c697bc-2f45-4c63-98da-053d1b7c2b96.png)

The problem doesn't happen on other themes:
![FOt8Jkbr6G](https://user-images.githubusercontent.com/54250441/221033631-64c552b3-8ae7-4844-a7df-811c638c1aed.gif)

(I'm more than willing to hide the title and continue using border, since it is by far my favorite theme available, but would be nice to have the fixed title)

**Comment by Akifyss** [comment]
![image](https://user-images.githubusercontent.com/23567154/221086813-5c0cc424-f52a-4e73-b72a-1a518f820d83.png)
One small detail you may have missed is that your installer version needs to be > 1.1.8 (and I noticed that your installer = 1.1.8).

So try to re-download obsidian on [the official website](https://obsidian.md/) to upgrade the installer version, (note that the installer version version needs to be >1.1.8, not = 1.1.8, after my test, when your installer version = <1.1.8, there are many functions and does not work properly)

![image](https://user-images.githubusercontent.com/23567154/221087396-20ccde7f-7735-4c44-beae-2d6136b58650.png)

**Comment by pckc** [comment]
I'm sorry for the misinterpretation!

But the same behavior is showing in installers (that was how far I went)
![explorer_ivlQOw9qbo](https://user-images.githubusercontent.com/54250441/221212279-a1716f60-3344-4edc-9f25-4afcac7f56e8.png)

I will make a clean install later.

**Comment by Akifyss** [comment]
Use the first installer in the picture below, which can be downloaded from [here](https://obsidian.md/download)

![image](https://user-images.githubusercontent.com/23567154/221220650-32cec8ce-95c2-44b6-9bc9-48bf9368eba6.png)
