### ISSUE TITLE
The content inside the canvas is blocked and the content cannot be fully displayed.

### ISSUE THREAD

**Issue by lxmwwl** [Akifyss/obsidian-border#375]
![image](https://github.com/user-attachments/assets/40ba893a-0b91-415e-89a4-ed383a5900c4)

**Comment by lxmwwl** [comment]
> Sorry, I can’t reproduce it. Could you reproduce it in a sandbox environment and describe the process for reproducing it?

Thank you for your answer. I realized that there might be something wrong. Then I checked the plug-in and css fragment. Finally, I found that there was something wrong with some settings in the style setting.

**Comment by Akifyss** [comment]
Is this related to the border theme settings? Could you inform me so that I can locate the issue?

**Comment by lxmwwl** [comment]
> Is this related to the border theme settings? Could you inform me so that I can locate the issue?

![image](https://github.com/user-attachments/assets/398a6259-1ed4-41b3-9184-951a9a30842b)
Okay, actually the problem lies here

**Comment by Akifyss** [comment]
It seems that Obsidian also considers canvas as an embed element, and this option itself should not be modifiable, sorry. But I'm curious why this is set to 100% here? A value of 100% means turning the element into a circle; if there is no such requirement, it is recommended to set it to a regular border-radius value.

**Comment by lxmwwl** [comment]
> It seems that Obsidian also considers canvas as an embed element, and this option itself should not be modifiable, sorry. But I'm curious why this is set to 100% here? A value of 100% means turning the element into a circle; if there is no such requirement, it is recommended to set it to a regular border-radius value.

This is a value I just reset🤦‍♂️

**Comment by Akifyss** [comment]
OK, this field is used to adjust the rounded corners of the embedded content. If the rounded corners are set too large, the content outside the rounded corners will be clipped. If there are no special requirements, it is recommended to keep this field as default.
