### ISSUE TITLE
阅读模式下，表格的空行的行高会变的特别小，编辑模式的实时预览就正常。默认主题也是这样，有没有办法解决。

### ISSUE THREAD

**Issue by putiwushu1234** [Akifyss/obsidian-border#379]
编辑模式实时预览如下
![Quicker_20241124_234039](https://github.com/user-attachments/assets/0a9b2d40-8b5d-418a-aaeb-3844fb1bb0f4)

阅读视图如下
![Quicker_20241124_234148](https://github.com/user-attachments/assets/e5e348bd-145e-4cf7-b90d-cc21903aabf7)

**Comment by Akifyss** [comment]
可以为表格设置一个固定高度，比如
```css
tr{
    height: 30px;
}
```
但是这个方法应该不完美，可以向官方反馈
