### ISSUE TITLE
Extra Checkbox Behavior

### ISSUE THREAD

**Issue by omicreativedev** [Akifyss/obsidian-border#380]
I'm not sure this is something that can actually be fixed but I thought I'd report it anyway.

If we define custom checkboxes such as:

- [?] Question
- [i] Information
- [S] Amount
- [*] Star
- [b] Bookmark
- ["] Quote

These checkboxes render as clickable. But if you click on one, it converts to done state. Then if you unclick it, it converts to not-done state. Could there be a way to:

1. Make these fancy type of checkboxes UNCLICKABLE
2. OR, make these fancy types revert to their previous type upon unclicking

Also, is there a way to define more types?

Thanks!

**Comment by Akifyss** [comment]
It might be impossible to achieve this effect with a CSS theme. Perhaps some plugins could do it, but I'm not really sure, sorry.
