### ISSUE TITLE
关于段落间距

### ISSUE THREAD

**Issue by putiwushu1234** [Akifyss/obsidian-border#383]
这里面的段落间距是怎样的，为什么我修改段落间距后，标题与正文之间的段落间距变了，正文之间的段落间距没变。

**Comment by Akifyss** [comment]
这里的段落间距是直接用的官方提供的变量，应该是主要会对阅读模式起效，而且阅读模式下，如果两段文本之间没有空白行的话，obsidian不会将它们识别成两个段落，而且这个由于这个原因，两段没有空白行文本之间的距离基本上是调不了的
