### ISSUE TITLE
Collapsed Header Level Indicator Overlapping with Header In Reading Mode

### ISSUE THREAD

**Issue by isdmg** [Akifyss/obsidian-border#385]
Obsidian Version: 1.7.7
Border Version: 1.10.9

Collapsed Header Level Indicator in Editing Mode (not overlapping)
![image](https://github.com/user-attachments/assets/11a35ed5-a941-4b12-a9a5-87c2df133ba0)

Collapsed Header Level Indicator in Reading Mode (overlapping)
![image](https://github.com/user-attachments/assets/5cf561b8-f327-417f-b8cd-1ea238cea86b)

**Comment by Akifyss** [comment]
The new version has fixed this issue. You can try updating it.
