### ISSUE TITLE
关于平滑光标的建议

### ISSUE THREAD

**Issue by wxmup** [Akifyss/obsidian-border#387]
vs code有平滑光标,有人也给obsidian实现了一个类似的效果的(css+ninja插件),就是输入中文时,光标永远都只会在文字的开头.
能在主题上实现类似的效果吗?

效果图如下:
![2024-12-06 13-24-02](https://github.com/user-attachments/assets/b0b9b309-db01-40fa-bc89-41401b38a7e3)

原帖
https://forum.obsidian.md/t/cursor-smooth-caret-animation/31068/25

**Comment by Akifyss** [comment]
感觉css可能不太能实现，抱歉
