### ISSUE TITLE
The border outline doesn't work well on macOS when tab bar is hidden

### ISSUE THREAD

**Issue by erwagasore** [Akifyss/obsidian-border#388]
I am enjoying using your theme. But when hidding `tab bar` on macOS the default button for window are not well positioned with the outline border. I personally think that you can give a possibility to customise the outline size using `styling-setting`.

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/6d3ea123-76ab-47a9-b366-2d3cac067653">

**Comment by Akifyss** [comment]
The position of the traffic light buttons in macOS occupies a large vertical space, so in auto-hide mode, if you want the traffic light to display normally, you must make the outline size relatively large. As a result, the space gained from auto-hide is almost negligible, making the tab auto-hide feature somewhat useless in this case. To be honest, I personally think this feature is not very suitable for Mac, and I recommend turning it off. Sorry.
