### ISSUE TITLE
大佬，今天更新后好像出了点事故😂

### ISSUE THREAD

**Issue by GITHubSiWei** [Akifyss/obsidian-border#39]
![Screenshot_2023-02-25-07-03-49-634_md obsidian](https://user-images.githubusercontent.com/17538796/221318717-ea856f4f-2cfa-49cd-a4f8-98921a9560fe.jpg)
移动端会有版本提示弹窗，版本移动端1.4.2，是因为内测版的原因嘛

**Comment by Akifyss** [comment]
我的疏忽，新版已经修复。

推测原因可能是系统默认的webview版本不够，没记错的话应该是要大于106
![image](https://user-images.githubusercontent.com/23567154/221336521-13f0e301-80f1-48ec-92d5-b951be487df2.png)

**Comment by GITHubSiWei** [comment]
![Screenshot_2023-02-25-12-44-31-210_com miui securitycenter](https://user-images.githubusercontent.com/17538796/221338735-6c9fefbc-c673-4ff2-909a-39dfcbf28f83.jpg)
果然佩服
