### ISSUE TITLE
代码块选中了，但是没有显示效果

### ISSUE THREAD

**Issue by catfishjpg** [Akifyss/obsidian-border#390]
![image](https://github.com/user-attachments/assets/81ba42aa-c322-451d-a793-02e88a050207)
![image](https://github.com/user-attachments/assets/c5400596-0f75-4793-a644-0ede580eaa41)
但是实际上border主题的代码块已经选中了，只是没有显示效果，怎么显示这个选中状态的效果

**Comment by Akifyss** [comment]
你可以查看这个：#227

重新安装 Obsidian 应该可以解决问题。

**Comment by catfishjpg** [comment]
感谢，已经解决了
