### ISSUE TITLE
侧边栏文字大小在1.7.7版本下会和编辑器文字大小一起变化

### ISSUE THREAD

**Issue by ZoeyNya** [Akifyss/obsidian-border#392]
如题目所说的那样
侧边栏（文件夹管理、标签栏等等）文字大小在1.7.7版本下会和编辑器文字大小一起变化。
这样的话会显得有些不协调，希望侧边栏文字大小能自定义或是固定一个值

**Comment by Akifyss** [comment]
我现在没能遇到这种情况，可以录一个视频吗

**Comment by ZoeyNya** [comment]
https://github.com/user-attachments/assets/b786ad48-072b-4dd8-a327-a3b509ddfeed

稍微录了一下，可以看到模糊的两侧侧边栏文字都有随文字大小一起变动，之前的版本没有这种情况

**Comment by Akifyss** [comment]
这个应该不是border主题，应该是别的主题吧。
