### ISSUE TITLE
iPadOS Title Bar Covers the UI

### ISSUE THREAD

**Issue by djmtype** [Akifyss/obsidian-border#394]
As shown in my screenshot the top of this theme is stuck under the title bar, and therefore inaccessible. 
![IMG_0161](https://github.com/user-attachments/assets/5044f705-4da4-49d2-b518-00741b82528a)

I tried other themes, and they appear fine, so it doesn’t seem like an Obsidian bug.

**Comment by djmtype** [comment]
Never mind, I saw the option for card layout under mobile settings in the Style Settings plugin.

**Comment by Akifyss** [comment]
The new version has fixed this issue. You can try updating it.
