### ISSUE TITLE
希望大佬能增加一个卡片主题模式

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#4]
如题所示，感恩大佬

**Comment by Akifyss** [comment]
这个我不太理解，可以详细描述一下吗？

**Comment by miaoziguan** [comment]
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/115944923/210512051-2f834c1e-71b1-47bd-83eb-e2b1d35d8019.png">
大概就是类似于这样，当然，这个只是一个小建议（狗头）

**Comment by Akifyss** [comment]
这个后续应该会考虑的

**Comment by Akifyss** [comment]
卡片模式已添加，需要在style settings上手动开启

**Comment by miaoziguan** [comment]
已经使用，非常完美，nice
