### ISSUE TITLE
Feature Request: option to disable or lower opacity of dotted background for code blocks

### ISSUE THREAD

**Issue by batrand** [Akifyss/obsidian-border#40]
Hey there! I recently discovered the theme on the store and I love it! A heavy contender for Minimal as my default theme! One feature I use heavily is code blocks, ie. inline content marked with 2 backticks, or a new block wrapped by 3 backticks.

When using the Border theme, these features have a dotted background:
![image](https://user-images.githubusercontent.com/8514709/221447912-29d64b5e-b215-4839-889d-091cd97cee2c.png)

I find the dots to be very distracting. It would be nice to have the option to either
1. Reduce the opacity of the dots so they're not too prominent, or
2. Disable the dots entirely.

This would really aid the theme's accessibility for me :D

**Comment by batrand** [comment]
@Akifyss I checked for updates and saw new version also has the code for removing the background, which is awesome! I actually got curious and poked around, and I just realised the same background is also used in quotes and table heads. Can you add the option to toggle them, too? Thanks!!

**Comment by Akifyss** [comment]
Relevant options have been added in the new version

**Comment by batrand** [comment]
thank you! it looks awesome!

**Comment by Fastidious** [comment]
> Relevant options have been added in the new version

Where do I find the options for this (code blocks, block quotes, inline code)? I just opened #73, and it relates.
