### ISSUE TITLE
Feature Request: option to disable headings' left indicator

### ISSUE THREAD

**Issue by batrand** [Akifyss/obsidian-border#41]
Another feature request :D would be nice to have the option to disable these lil guys:

![image](https://user-images.githubusercontent.com/8514709/221448165-cfc790db-4048-4577-abfc-6448610df5bc.png)

I see that we have an option to remove them for hovered/active lines, but I can't find the option to remove them for headings.

**Comment by Akifyss** [comment]
The new version adds an option to remove the indicator, which can be found in the "editor-heading".

**Comment by batrand** [comment]
thank you so much for such a prompt update! that's awesome
