### ISSUE TITLE
[FEATURE REQUEST] Add support for Projects plugin

### ISSUE THREAD

**Issue by decatetsu** [Akifyss/obsidian-border#42]
It would be cool to have adapted styles for Projects plugin (https://github.com/marcusolsson/obsidian-projects). It looks strange (see an image below). Something like changing all background to theme's color or just stretch gray background would be nice.

![image](https://user-images.githubusercontent.com/56955307/222084421-9c8366ed-49cc-4466-a1b6-0d8ad5051fdf.png)

**Comment by Akifyss** [comment]
Support has been added to the new version. The background can be changed in "Plugin-Project".

**Comment by decatetsu** [comment]
Awesome! Thank you!
