### ISSUE TITLE
hide header indicator

### ISSUE THREAD

**Issue by DutchPete** [Akifyss/obsidian-border#43]
How can I hide the green vertical bar:

![image](https://user-images.githubusercontent.com/10794265/222122480-89987daf-0287-4bf2-a033-67a97a877921.png)

I want to hide for all header levels.

**Comment by decatetsu** [comment]
@DutchPete You need to use Style Settings plugin. In its settings, go to "Editor > Headings" and turn on "Remove headings indicator"

**Comment by DutchPete** [comment]
Before opening this issue I did look everywhere in your Style Settings but did not find anything indicative of this feature. I checked again just now, there was still nothing:

![image](https://user-images.githubusercontent.com/10794265/222187536-dbc530db-e8ac-4c2d-a035-de3292835366.png)

I updated, and the option toggle is there.
Many thanks, and well done with a nice theme!
