### ISSUE TITLE
[FEATURE REQUEST] Add ability to turn off underline for internal links

### ISSUE THREAD

**Issue by decatetsu** [Akifyss/obsidian-border#44]
I was seeing this setting in the Minimal's Style settings. In my opinion, not only I want to make internal links seamless in the text. Thank you in advance!

**Comment by Akifyss** [comment]
Relevant options have been added in the new version.
![image](https://user-images.githubusercontent.com/23567154/222213110-77cde299-ae4f-4d35-a82d-4170a25cb557.png)

**Comment by decatetsu** [comment]
Thank you, it works!
