### ISSUE TITLE
BUG: indicator bar overlaps the first character of a line

### ISSUE THREAD

**Issue by batrand** [Akifyss/obsidian-border#46]
![image](https://user-images.githubusercontent.com/8514709/222583864-c7e0162a-e60a-44c2-9bdc-a05304956283.png)

Try out this markdown snippet:
```
> [! important] lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 
> lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 
lorem ipsum 
```

you will see that the left blue indicator bar overlaps the `>` character, and runs over the very first `l` character in the last line. It looks weird to me; perhaps it needs to be shifted a bit to the left?

**Comment by Akifyss** [comment]
Fixed in the new version

**Comment by batrand** [comment]
wow that is quick! thanks!
