### ISSUE TITLE
一点小小的适配

### ISSUE THREAD

**Issue by GITHubSiWei** [Akifyss/obsidian-border#48]
![Screenshot_2023-03-08-16-53-26-329_md obsidian](https://user-images.githubusercontent.com/17538796/223667779-9f28ec22-5d04-4297-b005-3e6acc80de31.jpg)
![Screenshot_2023-03-08-16-53-30-845_md obsidian](https://user-images.githubusercontent.com/17538796/223667801-4ddbe945-4e3e-4c20-80db-e12912a8c8b9.jpg)
大佬，主题最新这个块的icon和文字会错位包括后面的折叠图标😂只在移动端试了，PC端不知道咋样，

**Comment by Akifyss** [comment]
好奇怪，我的手机貌似是正常的。要不试试新建一个空库看看会不会有问题
![e404bb69c1b179333b1e8233daad8f9](https://user-images.githubusercontent.com/23567154/223678053-c201ab43-c113-42cf-abbe-774755f5be1d.jpg)

**Comment by GITHubSiWei** [comment]
好的

**Comment by GITHubSiWei** [comment]
https://piugo-nav.oss-cn-hangzhou.aliyuncs.com/Obsidian%20%E4%BD%BF%E7%94%A8%E6%8A%80%E5%B7%A7%E8%AE%B0%E5%BD%95.md
![image](https://user-images.githubusercontent.com/17538796/223882735-d86b7ade-df31-4e09-b41d-27e28d2bc6db.png)

大佬这是md文件，我这新库还是有这个问题

**Comment by Akifyss** [comment]
那新库里的其他标注是正常的吗？还是只有这一个异常

**Comment by GITHubSiWei** [comment]
新库其他正常 但标题会错位

**Comment by Akifyss** [comment]
貌似这不是border主题的问题，其他主题也会这样，默认的主题也是。可以考虑向obsidian官方反应一下

**Comment by GITHubSiWei** [comment]
好的，辛苦了 大佬 /跪
