### ISSUE TITLE
堆叠模式下的小问题

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#49]
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/115944923/223868124-6df375a3-366b-467c-9153-5f39208de33c.png">
如图所示，在背景有所自定义的情况下，堆叠标签页的主题没有匹配过来。

**Comment by Akifyss** [comment]
你中间栏位置的背景自定义的是什么颜色

**Comment by miaoziguan** [comment]
是自定义的带纹理的背景样式（深一点的灰色）

**Comment by miaoziguan** [comment]
不搞堆叠就是正常的

**Comment by Akifyss** [comment]
是这样的，堆叠模式的背景是不允许自定义css的（背景颜色是可以自定义的）。因为自定义css可能会导致几个背景透明的标签页叠在一起，连字都看不清。
![image](https://user-images.githubusercontent.com/23567154/223919144-13db82f6-f344-4607-8d35-8b898f8d0618.png)

**Comment by miaoziguan** [comment]
好的明白了谢谢大佬
