### ISSUE TITLE
BUG: translucency in secondary windows

### ISSUE THREAD

**Issue by batrand** [Akifyss/obsidian-border#51]
Hey there! I think there's some issues with translucency on secondary windows. I'm seeing it in the default and Minimal themes which I posted on the Obsidian forum [here](https://forum.obsidian.md/t/translucent-window-option-makes-titlebar-text-greyed-out/52374/4?u=batrand), but since Border looks more pronounced, I thought I should post here too.

# Reproduce
- Sandbox Vault, install Border
- Dark mode, no translucency:
![image](https://user-images.githubusercontent.com/8514709/224671807-ee9b271a-3029-4c8e-a15f-9eacc74d1285.png)
- Dark mode, translucent (note secondary window frame looks washed out)
![image](https://user-images.githubusercontent.com/8514709/224671900-c84be0af-3f0e-48e1-9f4f-2c618fdcca5e.png)
- Light mode, no translucency:
![image](https://user-images.githubusercontent.com/8514709/224672007-0ae05b37-e60c-4cbb-964f-285504ca47a1.png)
- Light mode, translucent: (note how the second window looks like it just has no translucency)
![image](https://user-images.githubusercontent.com/8514709/224672085-3a3e1768-eda9-4129-94f6-92fffee4c038.png)

That is on Windows, and looks like it's having a similar issue on Mac as well:
![image](https://user-images.githubusercontent.com/8514709/224674105-20647240-7f16-4e05-a163-0942813fd126.png)

# Notes
I think there's something going on with Obsidian about this issue, as I noted in the forum thread. Since Border has a more pronounced look, maybe it could be helpful for the main Obsidian app in identifying what the issue is. Thought I should let you know too.

**Comment by Akifyss** [comment]
Hello there. I've encountered this issue previously and attempted to resolve it without success. It appears that an official fix may be required for this inherent problem with Obsidian. Providing positive feedback to the official staff may be more constructive.
