### ISSUE TITLE
Plugin Callout Manager settings page not working with the Border theme

### ISSUE THREAD

**Issue by batrand** [Akifyss/obsidian-border#52]
Steps:
- Sandbox vault, install Callout manager
- Create new callout, and you can edit it using these buttons:
![image](https://user-images.githubusercontent.com/8514709/226149371-6f036a08-9a73-4167-b864-afe529e550aa.png)
- Install Border
- These buttons no longer work
![image](https://user-images.githubusercontent.com/8514709/226149395-7ae7a019-dbb4-479a-96f2-696cc8f21873.png)

**Comment by Akifyss** [comment]
Fixed in the new version

**Comment by batrand** [comment]
Thanks! Can confirm that it works now!
