### ISSUE TITLE
Feature Request: option for old button colour/shadow style

### ISSUE THREAD

**Issue by batrand** [Akifyss/obsidian-border#55]
Hey there! I see that the recent update changed the style of the active buttons' colouring and shadowing to be a bit more flat. I prefer the old style where it looked more rounded; it feels more unique compared to other themes. This is what I mean (I unfortunately no longer have the older version to grab a screenshot of)
![image](https://user-images.githubusercontent.com/8514709/227680021-e6e6951a-bf9a-43d2-b5b5-21144000f9ba.png)

Will you consider adding a style to switch between both?

**Comment by Akifyss** [comment]
![image](https://user-images.githubusercontent.com/23567154/227688575-32780c1e-7342-4549-a2c0-ae57e11c6a4a.png)

Hello!  You can fill in these codes to restore the old style:

input-shadow(light mode): `inset 0px 0px 0px 1px var(--background-modifier-border), 0px 1px 2px rgba(0, 0, 0, 0.04), inset 0px -4px 8px rgba(0, 0, 0, 0.05), inset 0px 4px 4px rgba(255, 255, 255, 0.15), inset 0px 2px 2px rgba(255, 255, 255, 0.25), inset 0px 1px 0px rgba(255, 255, 255, 0.5), inset 0px -2px 2px rgba(0, 0, 0, 0.04)`

input-shadow-hover(light mode): `inset 0px 0px 0px 1px var(--background-modifier-border-hover), 0px 1px 2px rgba(0, 0, 0, 0.05), inset 0px -4px 8px rgba(0, 0, 0, 0.05), inset 0px 4px 4px rgba(255, 255, 255, 0.15), inset 0px 2px 2px rgba(255, 255, 255, 0.25), inset 0px 1px 0px rgba(255, 255, 255, 0.5), inset 0px -2px 2px rgba(0, 0, 0, 0.05)`

input-shadow(dark mode): `inset 0px 0px 0px 1px var(--background-modifier-border), 0px 0px 0px 1px rgba(0, 0, 0, 0.5), inset 0px -4px 8px rgba(0, 0, 0, 0.2), inset 0px -1px 0px rgba(0, 0, 0, 0.4), inset 0px 4px 8px rgba(255, 255, 255, 0.05), inset 0px -2px 2px rgba(0, 0, 0, 0.1), inset 0px 2px 2px rgba(255, 255, 255, 0.05), inset 0px 1px 0px rgba(255, 255, 255, 0.05), 0px 1px 2px rgba(0, 0, 0, 0.25)`

input-shadow(dark mode): `inset 0px 0px 0px 1px var(--background-modifier-border-hover), 0px 0px 0px 1px rgba(0, 0, 0, 0.5), inset 0px -4px 8px rgba(0, 0, 0, 0.2), inset 0px -1px 0px rgba(0, 0, 0, 0.4), inset 0px 4px 8px rgba(255, 255, 255, 0.05), inset 0px -2px 2px rgba(0, 0, 0, 0.1), inset 0px 2px 2px rgba(255, 255, 255, 0.05), inset 0px 1px 0px rgba(255, 255, 255, 0.05), 0px 1px 2px rgba(0, 0, 0, 0.25)`

**Comment by batrand** [comment]
Thanks!
