### ISSUE TITLE
Highlight Active Card overlay overlaps with 'canvas cards / canvas notes'

### ISSUE THREAD

**Issue by Aeases** [Akifyss/obsidian-border#58]
![image](https://user-images.githubusercontent.com/96164686/229341482-9e6d0fef-c9bd-44d9-bec4-d74b5d034c2a.png)

Installer Version: **1.1.9**
Obsidian Version: **1.1.16**

![image](https://user-images.githubusercontent.com/96164686/229341536-021eb024-3026-4e33-adc2-d615ae40498d.png)

**Comment by Akifyss** [comment]
Fixed in the new version
