### ISSUE TITLE
希望大佬能为大纲增加层级引导线

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#6]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/115944923/210513554-bc3b79b3-93e9-4ecb-a5fb-1a50854b9c44.png">

例如这样。目前我是用第三方的css实现的

**Comment by Akifyss** [comment]
新版本中已添加，不过需要在style settings中手动来开启。是从 https://github.com/subframe7536/obsidian-theme-maple 这里移植过来的，他的十分完美。

**Comment by miaoziguan** [comment]
好的，大佬神速
