### ISSUE TITLE
大佬可以加入一些图片排版的css自定义样式么。

### ISSUE THREAD

**Issue by PencilMing** [Akifyss/obsidian-border#60]
或者推荐一些方便的图片排版css

**Comment by Akifyss** [comment]
抱歉，目前暂时还没有这个计划，但是我找到了一些插件/css片段链接，你可以试试看

- https://github.com/vertis/obsidian-image-layouts
- https://github.com/efemkay/obsidian-modular-css-layout/blob/main/MCL%20Gallery%20Cards.css
- https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Snippets/S%20-%20Aside.css
