### ISSUE TITLE
Stuttery, jittery performance (skipped frames) when using Callouts 

### ISSUE THREAD

**Issue by JigenDD** [Akifyss/obsidian-border#62]
While Border is unquestionably an amazing theme, it seems like it tanks the performance quite a bit, compared to other more graphically lightweight themes (like Minimal -- which while packed with customization features, for some reason is lighter on graphical resources usage). Recently, I think I was able to isolate one of the culprits for decreased graphical performance. 

It seems like using **callouts** -- and even more so _callouts inside callouts_ -- will cause performance to tank quite a bit when scrolling. We will have this jittery, somewhat unresponsive animations, when scrolling or when clicking the folder menus. Not using callouts seems to improve performance quite a bit.

My suggestion for now would be to -- like Minimal -- implement the ability to allow the user to **disable** _Callout Color Blending_, as the transparencies of the callouts adjusting to background color and other callouts use quite a bit of resources.

**Comment by Akifyss** [comment]
I'm not sure if the performance problem is caused by the callout. You can test this code to see if it alleviates the performance problem (the effect is the same as disabling Callout Color Blending in Minimal theme):
```css
body{--callout-blend-mode:normal;}
```
If there is any situation, please let me know.

**Comment by JigenDD** [comment]
I just tried that CSS and you're right: The difference is negligible. There is something of a small performance improvement when scrolling up and down, but the improvement is so diminutive, that only someone looking for it would notice. 

This seems to be more of a problem related to the electron as a (_burdensome, resource heavy_) framework, and not directly theme-related.

**Comment by Akifyss** [comment]
Maybe turning off Card layout or Auto-hide might help performance

**Comment by Akifyss** [comment]
Hello, I do not have a macOS device currently, so I cannot further investigate the performance issues of the border theme on macOS. But you can try the following measures to see if they can improve performance:
+ Reinstall Obsidian to upgrade the installer version.
+ Make sure hardware acceleration is enabled. ![image](https://user-images.githubusercontent.com/23567154/233289109-e9c89156-8486-49f3-a629-b0f0673f67b8.png)
+ Remove extra animation: ![image](https://user-images.githubusercontent.com/23567154/233294501-3f46b803-dc3a-4450-9d26-c8062f5fb57b.png)
+ Disable hover line indicator
![image](https://user-images.githubusercontent.com/23567154/233295743-75afa471-678f-4ed0-82d4-f7b499e45b1a.png)
+ Disable Card layout & Auto-hide

**Comment by Akifyss** [comment]
I have to say that I am surprised by the performance issues you have shown. My obsidian performance is very different from yours and I would like to offer some help, but I don't know where to start.😔
