### ISSUE TITLE
大佬，抓住bug一枚，

### ISSUE THREAD

**Issue by GITHubSiWei** [Akifyss/obsidian-border#64]
![2023-04-18_08-44](https://user-images.githubusercontent.com/17538796/232640619-1a15cb58-b0fb-40ff-90e4-9a3d30b0658e.png)

大佬，大纲拖拽调整位置，顶部会出现一个蓝线乱跳，不知道是只有我出现这个问题，你那需要复现我可以录个视频，辛苦佬了，哈哈哈哈

**Comment by Akifyss** [comment]
新版已修复，可以更新试试
