### ISSUE TITLE
Accent color shenanigans & other minor issues

### ISSUE THREAD

**Issue by JigenDD** [Akifyss/obsidian-border#65]
# Different Accent Colors for Light and Dark Mode
Hi. I've noticed that as of recently there seems to have been a regression of sorts (which is to say: "it used to work") regarding setting _different accent colors for **light** and **dark modes.**_

It seems like the accent color set at the app level set in the "Appearance" menu takes precedent over anything that is established in Style Settings regarding separate accent colors for light and dark mode. You click around different accent colors for light mode, and it does nothing. You do the same for dark mode, and it does nothing for dark mode. The accent color set in "Appearance" will never change. 

# Text alignment in File Explorer
It seems like that if we set Border not to trim file and folder names, the first line will have a space, while the second line (and onwards) will be pushed too far to the left

![image](https://user-images.githubusercontent.com/119014255/233888293-d267bc4f-f222-4cb7-ace4-1a7df3ab5ec0.png)

It would be much nicer if all lines -- no matter how long the file/folder name -- were all justified and aligned, with an equal space between them and the border to the left

# Option to change body text color
I've noticed that despite the (much welcomed) wealth of options to change the color italic, bolds and highlights, there's no visible options to change the color of normal body text. It would be a much appreciated addition, as sometimes you may want to set a warmer or more/less contrasty color, than the one automatically set (not to mention how different fonts may benefit more or less contrast, color, etc)

# Option to align images to the center
If pasted images are smaller than the full-width of the line, they will always be aligned to the left. For my aesthetic taste and also capability to focus, I _subjectively_ prefer when the images are aligned to the center. It would be a great addition if it was allowed for the user to align images _(or even other objects, which insist on aligning to the left, like YouTube Video Embeds)_ to either left, right, or (especially for me, and I'm certain, other people) **center**.

**Comment by Akifyss** [comment]
You can change body text color in “style settings-appearance-foreground”.

**Comment by Akifyss** [comment]
other issues have been resolved in the new version.
