### ISSUE TITLE
内容较长，图片较多时使用鼠标滚轮翻页会出现异常

### ISSUE THREAD

**Issue by Yaopangpang** [Akifyss/obsidian-border#69]
Obsidian版本：V1.2.7
安装程序版本：1.1.16
自定义主题模板：Translucent
内容长度：15730字符
图片张数：30张左右，图片使用图床
异常描述：
进入笔记，从头部开始使用鼠标滚轮向下翻页，翻至底部时，页面内容会跳到笔记头部
个人验证：
切换至默认主题，Minimal主题，无此现象
使用当前主题，在内容较少的笔记中使用鼠标滚轮向下翻页，无此现象
使用Style setting插件，将Dark Mode进行恢复默认，复现了异常

**Comment by Akifyss** [comment]
我这里未能复现出来，无法定位问题所在。要不你在style settings里关闭图片的相关功能并且移除动效试试

**Comment by Yaopangpang** [comment]
Style setting中关闭了图像相关的三个功能，仍然会复现
系统：MacOS venture 13.3.1 M1芯片版本
录屏文件地址：https://typoraforzz.oss-cn-hangzhou.aliyuncs.com/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B62023-05-15%2011.51.36.mov

**Comment by Akifyss** [comment]
用同样的模式和预设再试了一次，还是没能复现出来。我的设备是win，猜测有可能是系统问题。目前我也没有什么办法🥹
