### ISSUE TITLE
功能请求：侧边栏文件名增加滚动选项

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#7]
如题所示，库里面的文件名在比较长的情况下，就必须更改拦宽，如果鼠标移动到这个文件名，文件名从左到右自动浮现就能更方便些。

**Comment by Akifyss** [comment]
我试着做了一下，发现这个功能用纯CSS实现起来效果不是很好，会与其他东西有冲突。😢

**Comment by miaoziguan** [comment]
好的
