### ISSUE TITLE
Enable titlebar auto-hide on mobile too

### ISSUE THREAD

**Issue by sh-l** [Akifyss/obsidian-border#70]
Titlebar auto-hide which is available in Style Settings is only applied to desktop environment.

Please add an option to enable it for `body.is-mobile`.

**Comment by Akifyss** [comment]
Try deleting the following content in the theme file:

![image](https://github.com/Akifyss/obsidian-border/assets/23567154/4233fa62-c466-48bf-aafd-4ddf9da9a1ae)
