### ISSUE TITLE
大佬新版大纲视图出现虫子

### ISSUE THREAD

**Issue by GITHubSiWei** [Akifyss/obsidian-border#72]
![image](https://github.com/Akifyss/obsidian-border/assets/17538796/463610fd-21a8-49cc-89c9-3e27102ad931)

![image](https://github.com/Akifyss/obsidian-border/assets/17538796/eae6c514-e4af-468a-8d7a-743a765b5bc6)

新版大纲视图标题好像错位了，不知道是什么原因。

**Comment by Akifyss** [comment]
这个应该是obsidian测试版本吧，测试版好像对列表的样式做了修改（border主题的文件和大纲的列表都出现了问题）。为了避免主题修复更新影响现在正在用obsidian正式版的用户，主题的修复更新将会和obsidian正式版更新一起发出来。目前可以先把大纲视图切回默认，等更新之后再切回来。

**Comment by GITHubSiWei** [comment]
已经这么干了，辛苦大佬，哈哈哈哈（小声bb：主题太巴适了）
