### ISSUE TITLE
Exporting to PDF

### ISSUE THREAD

**Issue by Fastidious** [Akifyss/obsidian-border#73]
When exporting to PDF, the code blocks look that the screenshot below. What can be made to make their background more appealing?

<img width="850" alt="Screenshot 2023-05-19 at 09 39 07" src="https://github.com/Akifyss/obsidian-border/assets/8352292/39e415fe-44a9-4240-bf64-17f762995a55">

**Comment by Fastidious** [comment]
Found it! It is on “Style Settings” → “Editor” → “Code” “Blockquote”. Thanks!

**Comment by Akifyss** [comment]
Guess the code block background display may be related to the pdf reader, this is the appearance of a pdf I opened in Edge browser

![image](https://github.com/Akifyss/obsidian-border/assets/23567154/342fcccb-d9cd-4095-9690-c791d92b93cd)
