### ISSUE TITLE
[bug] = When I enter English in the title, the cursor automatically moves to the next line after typing 

### ISSUE THREAD

**Issue by doit132** [Akifyss/obsidian-border#75]
# Question

![动画](https://github.com/Akifyss/obsidian-border/assets/117004316/a3c3e645-1189-4587-911f-9d6b560277d1)

I used a sandbox library for troubleshooting, and it's not the reason for the plugin. 

# Try to solve

I find the possible cause if these commits.
 
![image](https://github.com/Akifyss/obsidian-border/assets/117004316/196b250b-5c43-4b6b-844a-bada50f774c7)

when I delete these commits, the bug is no longer appear.

# Obsidian version

v1.3.3

**Comment by Akifyss** [comment]
Thanks for the feedback, the bug should have been fixed in the new version.
