### ISSUE TITLE
File Explorer Highlight extends too far (Obs. 1.3 and above)

### ISSUE THREAD

**Issue by Aeases** [Akifyss/obsidian-border#79]
Ever since Obsidian 1.3 the files in the file explorer highlight all the way to the edge of the screen instead of around just the file itself like it did previously

After 1.3:
![image](https://github.com/Akifyss/obsidian-border/assets/96164686/2bdab7be-4944-4baa-ad74-8b1d24b5f016)
Prior to 1.3:
![image](https://github.com/Akifyss/obsidian-border/assets/96164686/96e01f2e-5027-43f6-9e19-3edea7d49593)
Same image on 1.3
![image](https://github.com/Akifyss/obsidian-border/assets/96164686/98bced53-3874-48a6-ab7f-5510c916e66f)

![image](https://github.com/Akifyss/obsidian-border/assets/96164686/540a773f-94d3-4cd7-8560-8ad8ae99bcb5)

**Comment by Akifyss** [comment]
This is a new [feature](https://forum.obsidian.md/t/obsidian-release-v1-3-1-insider-build/59810#improvements-1) of obsidian, and I will most likely not bother to modify it.
