### ISSUE TITLE
插件适配：Calendar插件的局部显示问题

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#8]
<img width="337" alt="image" src="https://user-images.githubusercontent.com/115944923/210937904-9f5171f0-f7ed-45b5-bbab-8ffdd4e65ed9.png">

如图所示，阅读上一眼很难定位到今天的日期，我的个人建议是增加一个小圆圈突出一下

**Comment by Akifyss** [comment]
新版本添加了一个外框来突出显示
