### ISSUE TITLE
并不是bug，能不能每次更新发个releases

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [Akifyss/obsidian-border#80]
并不是bug，能不能每次更新发个releases，这样方便更新，我在官方商店下载这个主题都不行，都需要到github上，但是国内github又有各种问题，如果您发个releases，我就可以通过beta那个插件或者官方商店进行及时下载了，麻烦了

**Comment by Akifyss** [comment]
你好，我想先了解一下为什么在官方的商店无法下载主题？是点击下载按钮没有反应吗？

**Comment by shoudeyunkaijianyueming** [comment]
抱歉，是我的原因，原因在proxy这个插件，关了就能正常下载了
