### ISSUE TITLE
weird background effect in default theme for dataview, codeblocks, quote, etc.

### ISSUE THREAD

**Issue by warm-july** [Akifyss/obsidian-border#81]
![image](https://github.com/Akifyss/obsidian-border/assets/696111/0849f083-e7dc-4028-bf80-f711f88c649e)
see the attached image, same effect is shown as background for codeblocks, quote, etc. unless manually changed in style setting,
but don't know which one is for dataview background?
Thnx!

**Comment by Akifyss** [comment]
Try changing this:
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/3d99f33b-8002-4cde-a81d-51bdf7879ee9)

**Comment by RhymeRequiem** [comment]
I'm having the same issue and I've tried putting a hex code in the settings you highlighted and it doesn't seem to do anything. I'm not familiar with CSS so if you could describe what to input for it to work it'd be appreciate ^_^

**Comment by Akifyss** [comment]
> I'm having the same issue and I've tried putting a hex code in the settings you highlighted and it doesn't seem to do anything. I'm not familiar with CSS so if you could describe what to input for it to work it'd be appreciated ^_^

I don't know what you typed but you can refer to the following：
https://developer.mozilla.org/en-US/docs/Web/CSS/background
https://developer.mozilla.org/en-US/docs/Web/CSS/background-color

**Comment by RhymeRequiem** [comment]
I've tried various formatting online and it hasn't worked. `background-color: #242424`, `background-color: #242424;`, `#242424`, `242424`, `rgba(36, 36, 36, 1)`, `rgb(36,36,36)` `background-color: rgba(36, 36, 36, 1)`, `background-color: rgb(36,36,36)`, etc etc... so I wasn't sure if there was a specific way to make it work with this.

**Comment by Akifyss** [comment]
> I've tried various formatting online and it hasn't worked. `background-color: #242424`, `background-color: #242424;`, `#242424`, `242424`, `rgba(36, 36, 36, 1)`, `rgb(36,36,36)` `background-color: rgba(36, 36, 36, 1)`, `background-color: rgb(36,36,36)`, etc etc... so I wasn't sure if there was a specific way to make it work with this.

You don't need to enter "background-color:".

**Comment by RhymeRequiem** [comment]
Those are all the formatting methods I've tried, including nott having `background-color`, and it still doesn't work.

**Comment by Akifyss** [comment]
Does anything happen if you only input "#ffffff"?

**Comment by RhymeRequiem** [comment]
Nope. Here's also some screenshots of where I've seen the background issue, though it's probably elsewhere as well, I haven't checked.
![rb7NHwCPRU](https://github.com/Akifyss/obsidian-border/assets/106857704/0a180505-2c72-47b8-8fa6-6c1ec0cc9624)
![d2vo4xwZ2i](https://github.com/Akifyss/obsidian-border/assets/106857704/babc2dae-2d7d-48b2-a1eb-1837a19616d8)

**Comment by Akifyss** [comment]
It's really strange, this feature is working fine in my environment：

https://github.com/Akifyss/obsidian-border/assets/23567154/5116171a-44b6-4e56-9f2d-dfbdea8c9582

**Comment by Akifyss** [comment]
What system are you using?

**Comment by RhymeRequiem** [comment]
I'm using Windows 11. I had Obsidian sitting on my PC for a while, I only just maybe two hours ago opened it up and updated it, updated the launcher, and started installing plugins and themes and such. When I turn off the theme, the issue with the background is no longer there as well.

**Comment by Akifyss** [comment]
So what is your question? Is it about the dotted background? This is the background that comes with this theme, if you don't like it, you can refer to the video to modify it.

**Comment by RhymeRequiem** [comment]
Modifying it doesn't do anything, that is my issue.

**Comment by Akifyss** [comment]
Which part of the background do you want to modify? Would it be convenient for you to record a video to help locate the issue?

**Comment by RhymeRequiem** [comment]
![sjvyF3E9RH](https://github.com/Akifyss/obsidian-border/assets/106857704/68045dbe-1aad-4295-9b52-d557bf6065f0)
![klFcpiMTov](https://github.com/Akifyss/obsidian-border/assets/106857704/fe8472c7-c1fe-44ed-bcc8-04a368fcd0cd)
The dotted background in these screenshots. I originally thought the dotted background was just a bug, hence why I was mentioning it, but as it is not, I'm just asking about trying to get the setting to modify it to work. The first screenshot is from the slash menu in a document and the second one is from the tasks plugin. I want that dotted background to just be one color. I can record a video if necessary.

**Comment by Akifyss** [comment]
If it's convenient for you, a video might be more helpful.

**Comment by RhymeRequiem** [comment]
https://github.com/Akifyss/obsidian-border/assets/106857704/d8cac423-7e49-4b99-8838-0c3acc5bdd5e

**Comment by RhymeRequiem** [comment]
Uploading a video directly to github didn't work for some reason so here: https://streamable.com/f5mzp4

**Comment by Akifyss** [comment]
Okay, I understand. Have you tried making changes here?

![image](https://github.com/Akifyss/obsidian-border/assets/23567154/8f95f377-d7ba-41e1-848c-3a01349c98d9)

**Comment by RhymeRequiem** [comment]
I assumed from your video that would be for something else but that worked, so thank you for the help.
