### ISSUE TITLE
Search-highlight block showed at the bottom of the window

### ISSUE THREAD

**Issue by slipdem** [Akifyss/obsidian-border#82]
When searching something inside the file - search-highlight block showed at the bottom of the window, not on the actual searched and highlighted items.

On other themes search works well, but I love this one)
Obsidian Version 1.3.4 (Installer 1.3.3), macOs 13.3.1

<img width="1298" alt="Screenshot 2023-05-29 at 16 56 34" src="https://github.com/Akifyss/obsidian-border/assets/12971337/0109ebcd-b4b5-45e6-bfc2-c3e839a28faa">

**Comment by Akifyss** [comment]
This is strange. The search-highlight block shows fine in my environment:
I don't know why for now, could you please try it again in a sandbox environment?

![image](https://github.com/Akifyss/obsidian-border/assets/23567154/5b18ad84-dba4-4bc2-82bf-60b84dd7b35d)

**Comment by slipdem** [comment]
Same in the sandbox. 
Only installed plugin in sandbox is Style Settings.
But it doesn't work properly even before plugin installed.
Also no errors in devTools console.

<img width="1136" alt="Screenshot 2023-05-29 at 19 10 33" src="https://github.com/Akifyss/obsidian-border/assets/12971337/87562184-0bad-47a7-bee7-46dfd651cf20">

**Comment by Akifyss** [comment]
Thanks for the test, the bug should have been fixed in the new version.
