### ISSUE TITLE
For vertical (vertical) pictures in the document, mouse clicks cannot zoom in, but zoom out further

### ISSUE THREAD

**Issue by zhouxinghong** [Akifyss/obsidian-border#84]
Thank you for a great theme!
Have a question about using this theme?
For vertical (vertical) pictures in the document, mouse clicks cannot zoom in, but zoom out further, which should be a wrong behavior.
System: Windows 10
Obsidian: 1.3.5
Theme Version: Latest
![image](https://github.com/Akifyss/obsidian-border/assets/54253524/e4b0d76c-19af-4f9e-ac46-8c8f07e717f5)

**Comment by zhouxinghong** [comment]
For vertical (vertical) pictures in the document, mouse clicks cannot zoom in, but zoom out further, which should be a wrong behavior.

**Comment by Akifyss** [comment]
Hello there! This is most likely not a wrong behavior, this feature scales (zoom in/out) the image to the container size, not zoom in image at all times, it comes directly from kepano's Minimal theme. I'm not sure about the possibility of zoom in images at all times.

**Comment by zhouxinghong** [comment]
There should be a limit judgment. If the image cannot be enlarged, then the original size of the image will be maintained. In short, it cannot be further reduced. You can also use vertical (portrait) images to try to see the actual effect.

**Comment by Akifyss** [comment]
I've tried it before and can confirm that it's not a wrong behavior, the image zoom function doesn't zoom in on the image, it just scales the image to the container size. Regarding what you describe, I'm not sure it can be implemented in a CSS theme. Maybe you can implement it with a plugin, like [image toolkit](https://github.com/sissilab/obsidian-image-toolkit)

**Comment by zhouxinghong** [comment]
This plugin is misbehaving

**Comment by Akifyss** [comment]
That's weird, it works fine in my environment. Maybe you can go to the plugin repository and submit an issue to fix the problem

**Comment by zhouxinghong** [comment]
Many people have submitted issues, the plugin has not been maintained for a long time

**Comment by Akifyss** [comment]
Oh, it seems so. There shouldn't be much I can do about it.

**Comment by zhouxinghong** [comment]
Your theme is great! It's just that Obsidian runs slowly sometimes. . .

**Comment by Akifyss** [comment]
Thanks, I'll try to improve it
