### ISSUE TITLE
Uncollapsed theme settings in Style Settings plugin

### ISSUE THREAD

**Issue by DensityInfinite** [Akifyss/obsidian-border#87]
Currently, the theme settings lives in the root level of the style settings menu.

<img width="774" alt="Screenshot 2023-06-21 at 9 56 19 am" src="https://github.com/Akifyss/obsidian-border/assets/84255222/23472f28-0e0f-4c6c-83c4-e91a33a330d1">

Would it be a "better practice" to collapse those in a big _folder_, in something like "Border Settings"? Just like what the other plugins & themes do. I find this to be quite confusing for new users, especially when they are using other plugins as well.

**Comment by Akifyss** [comment]
Hello, I'm sorry for the inconvenience you're experiencing. But there are some reasons for me to do so, you can check this issue: https://github.com/Akifyss/obsidian-border/issues/36.

**Comment by DensityInfinite** [comment]
Understood! Sorry for not scrolling through the old issues before opening a new one.
Thank you for making the theme! The effort you have put into this is astounding.
