### ISSUE TITLE
一个新的想法💡

### ISSUE THREAD

**Issue by miaoziguan** [Akifyss/obsidian-border#9]
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/115944923/210960695-4cd788ab-23de-438e-a7f0-ea211b2b5cf8.png">

如图所示，是否可以实现这三个区域背景单独上色🎨
这样的话可玩性，和配色会更加丰富一些🤔

**Comment by Akifyss** [comment]
👍好想法，已经添加到新版本。可以在style settings里的 自定义颜色 这个选项里单独上色

**Comment by miaoziguan** [comment]
感谢大佬，奥力给
