### ISSUE TITLE
Search doesn't highlight or mark the found result 

### ISSUE THREAD

**Issue by yusluk** [Akifyss/obsidian-border#90]
when you cmd +f or ctrl + f and search for a word in your text the found result is not marked or highlighted which is a huge inconvenience please solve ASAP, since your theme is the greatest !

**Comment by Akifyss** [comment]
The search highlight works fine in my environment. Can you please let me know the version of your border theme and the installer version of Obsidian?

**Comment by yusluk** [comment]
It works fine in the editor mode, however not on the reader mode. I am using obsidian on 1.3.5 on MacOS.

**Comment by Akifyss** [comment]
What is the version of your border theme?

**Comment by yusluk** [comment]
Uninstalling and reinstalling worked thanks.
