### ISSUE TITLE
Export to PDF: code and code block background

### ISSUE THREAD

**Issue by ajrangel** [Akifyss/obsidian-border#91]
Love this theme, however when I export notes to PDF there is a strange pattern used for the background on code and code blocks. I tried changing settings to adjust this option, but I could not find the correct setting.

**Comment by Akifyss** [comment]
You can customize the background of your code here:

<img width="1100" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23567154/a0e3d93c-490d-4ddc-9d27-bb9504c97fef">
