### ISSUE TITLE
正在编辑的块的内容无法选中

### ISSUE THREAD

**Issue by CafeBabe202** [Akifyss/obsidian-border#93]
不知道为是什么原因，正在编辑的块是无法使用鼠标选中，只有添加两个空行之后才能使用鼠标选中。

**Comment by Akifyss** [comment]
抱歉，有点没太懂，有没有截图视频什么的？

**Comment by CafeBabe202** [comment]
https://undo.vip/Markdown/2023-08-02%2012-30-12.mkv

**Comment by CafeBabe202** [comment]
> 抱歉，有点没太懂，有没有截图视频什么的？
https://undo.vip/Markdown/2023-08-02%2012-30-12.mkv
这个问题并不是一直存在，我刚该在测试的时候只是偶尔这样。我不清楚是不是我的文档的问题，我的文档是在Typora中粘贴过来的

**Comment by Akifyss** [comment]
那其他文件会这样吗？这张情况我以前从没见到过。能否麻烦在沙箱仓库中尝试一下

**Comment by CafeBabe202** [comment]
> 那其他文件会这样吗？这张情况我以前从没见到过。能否麻烦在沙箱仓库中尝试一下
其他的文件也会这样，我是在我刚开始接触obsidian，所以这个工作空间是刚刚创建的

**Comment by Akifyss** [comment]
其他主题会这样吗

**Comment by CafeBabe202** [comment]
> 其他主题会这样吗

我只测试了默认主题不会这样，不知道你有没有能复现这个问题

**Comment by Akifyss** [comment]
我从来没有遇到过这个问题，把你出问题的md文件发我一份看看吧，我测试一下

**Comment by CafeBabe202** [comment]
> 我从来没有遇到过这个问题，把你出问题的md文件发我一份看看吧，我测试一下

https://undo.vip/Markdown/%E5%9F%BA%E4%BA%8E%E7%BB%9F%E8%AE%A1%E7%89%B9%E5%BE%81%E7%9A%84%E7%AA%83%E7%94%B5%E6%A3%80%E6%B5%8B.md

下载完请通知我，我将删除链接

**Comment by Akifyss** [comment]
可以了

**Comment by CafeBabe202** [comment]
> 可以了

好的，谢谢，虽然我已经打算放弃使用 obsidian，但是还是非常感谢你能回应的的问题。对，我使用的是linux mint系统，我不知道这是不是只有在特定系统上才会出现的问题。

**Comment by CafeBabe202** [comment]
> 我也出现了类似的问题，系统是MacOS，ob最新稳定版 别的主题不会这样，开了安全模式也测试过，还是这样。 有些行，鼠标点击光标不会进入， 我终于找到规律了，作者可以试试这样的新建格式
> 
> ```ts
> ## 1
> ### 1.1
> ## 2
> 22222
> ## 3
> 3333
> ## 4
> 44444
> ## 5
> ### 5.1
> 55555
> ```
> 
> <img alt="image" width="809" src="https://user-images.githubusercontent.com/44393379/258100169-5695e9f0-b145-41f4-95b2-8d12fc6ae673.png">

我也是同样的问题，作者没有遇到问题，我想是不是 obsidian 版本问题

**Comment by itangqiao** [comment]
嗯 是的，我也是更新了版本才出现的，开发者确实得跟进最新版本适配情况，试过几款主题没有更新也不会出现这种不兼容情况。可能还是因为border主题的功能太丰富原因，"双刃剑"。
希望开发者可以尽快修复，毕竟现在的问题还挺**致命**，很多页面无法移动光标都只能开源码模式编辑，只能先用别的主题缓解一下。

**Comment by itangqiao** [comment]
> > 嗯 是的，我也是更新了版本才出现的，开发者确实得跟进最新版本适配情况，试过几款主题没有更新也不会出现这种不兼容情况。可能还是因为border主题的功能太丰富原因，"双刃剑"。 希望开发者可以尽快修复，毕竟现在的问题还挺**致命**，很多页面无法移动光标都只能开源码模式编辑，只能先用别的主题缓解一下。
> 
> 也就说旧版的没有问题吗？我现在用的是 typora，虽然非常优雅且稳定，但是功能的确不如 obsidian 丰富，习惯了所见即所得用不习惯源码模式。我开始尝试适应 obsidian，border 是我唯一觉得可以开箱即用并且比较好看的主题，但是这个的确是一个比较大的问题，所以还是放弃了，换回了 typora。

嗯 退几个版本应该没问题。
我以前也用 typora，后来用wolai,notion构建了自己的知识库，养成了日常记笔记的习惯。
当你发现你的知识库越来越庞大的时候，你就发现查询的效率至关重要，这样会积累你使用笔记的信心，而不是为了记而记，就会形成一个正循环。后面从在线转为本地的原因还是怕以后迁移成本过大，和软件绑死了，排版格式也会出现不兼容。

ob搭建真的太费精力了，因为初期就是“毛坯房”，而且还得自己去摸索一种记录风格，才能真正提升效率。但当成型后，后期基本不用管它了，就是一个普通的笔记本而已。永远可以相信，适合自己的就是最好的。

**Comment by itangqiao** [comment]
> > > 嗯 是的，我也是更新了版本才出现的，开发者确实得跟进最新版本适配情况，试过几款主题没有更新也不会出现这种不兼容情况。可能还是因为border主题的功能太丰富原因，"双刃剑"。 希望开发者可以尽快修复，毕竟现在的问题还挺**致命**，很多页面无法移动光标都只能开源码模式编辑，只能先用别的主题缓解一下。
> > 
> > 
> > 也就说旧版的没有问题吗？我现在用的是 typora，虽然非常优雅且稳定，但是功能的确不如 obsidian 丰富，习惯了所见即所得用不习惯源码模式。我开始尝试适应 obsidian，border 是我唯一觉得可以开箱即用并且比较好看的主题，但是这个的确是一个比较大的问题，所以还是放弃了，换回了 typora。
> 
> 嗯 退几个版本应该没问题。 我以前也用 typora，后来用wolai,notion构建了自己的知识库，养成了日常记笔记的习惯。 当你发现你的知识库越来越庞大的时候，你就发现查询的效率至关重要，这样会积累你使用笔记的信心，而不是为了记而记，就会形成一个正循环。后面从在线转为本地的原因还是怕以后迁移成本过大，和软件绑死了，排版格式也会出现不兼容。
> 
> ob搭建真的太费精力了，因为初期就是“毛坯房”，而且还得自己去摸索一种记录风格，才能真正提升效率。但当成型后，后期基本不用管它了，就是一个普通的笔记本而已。永远可以相信，适合自己的就是最好的。

我也最喜欢typora的即使渲染风格，思源笔记也是这样，之前也折腾过 特别喜欢， 但是数据加密、移动端收费就放弃了，虽然现在适应了ob这种编辑风格，但还是不喜欢这种。

**Comment by CafeBabe202** [comment]
> > > 嗯 是的，我也是更新了版本才出现的，开发者确实得跟进最新版本适配情况，试过几款主题没有更新也不会出现这种不兼容情况。可能还是因为border主题的功能太丰富原因，"双刃剑"。 希望开发者可以尽快修复，毕竟现在的问题还挺**致命**，很多页面无法移动光标都只能开源码模式编辑，只能先用别的主题缓解一下。
> > 
> > 
> > 也就说旧版的没有问题吗？我现在用的是 typora，虽然非常优雅且稳定，但是功能的确不如 obsidian 丰富，习惯了所见即所得用不习惯源码模式。我开始尝试适应 obsidian，border 是我唯一觉得可以开箱即用并且比较好看的主题，但是这个的确是一个比较大的问题，所以还是放弃了，换回了 typora。
> 
> 嗯 退几个版本应该没问题。 我以前也用 typora，后来用wolai,notion构建了自己的知识库，养成了日常记笔记的习惯。 当你发现你的知识库越来越庞大的时候，你就发现查询的效率至关重要，这样会积累你使用笔记的信心，而不是为了记而记，就会形成一个正循环。后面从在线转为本地的原因还是怕以后迁移成本过大，和软件绑死了，排版格式也会出现不兼容。
> 
> ob搭建真的太费精力了，因为初期就是“毛坯房”，而且还得自己去摸索一种记录风格，才能真正提升效率。但当成型后，后期基本不用管它了，就是一个普通的笔记本而已。永远可以相信，适合自己的就是最好的。

我也尝试过 wolai，notion，还有一些其他的国产笔记软件，虽然他们的功能看上去比较“优雅”，但是使用了一些自己的语法，我担心平台绑定的问题，所以就没有使用。
至于 Typora，目前的我的笔记量比较少，正在培养习惯，所以还算能够满足我的需求，但是听了你的经历感觉 Typora 功能的慢慢可能不够用了。所以还是打算在试试 Obsidian。源码模式的编辑器真的很容易写错语法，并且我觉得表格编辑真的痛苦。

**Comment by itangqiao** [comment]
> > > > 嗯 是的，我也是更新了版本才出现的，开发者确实得跟进最新版本适配情况，试过几款主题没有更新也不会出现这种不兼容情况。可能还是因为border主题的功能太丰富原因，"双刃剑"。 希望开发者可以尽快修复，毕竟现在的问题还挺**致命**，很多页面无法移动光标都只能开源码模式编辑，只能先用别的主题缓解一下。
> > > 
> > > 
> > > 也就说旧版的没有问题吗？我现在用的是 typora，虽然非常优雅且稳定，但是功能的确不如 obsidian 丰富，习惯了所见即所得用不习惯源码模式。我开始尝试适应 obsidian，border 是我唯一觉得可以开箱即用并且比较好看的主题，但是这个的确是一个比较大的问题，所以还是放弃了，换回了 typora。
> > 
> > 
> > 嗯 退几个版本应该没问题。 我以前也用 typora，后来用wolai,notion构建了自己的知识库，养成了日常记笔记的习惯。 当你发现你的知识库越来越庞大的时候，你就发现查询的效率至关重要，这样会积累你使用笔记的信心，而不是为了记而记，就会形成一个正循环。后面从在线转为本地的原因还是怕以后迁移成本过大，和软件绑死了，排版格式也会出现不兼容。
> > ob搭建真的太费精力了，因为初期就是“毛坯房”，而且还得自己去摸索一种记录风格，才能真正提升效率。但当成型后，后期基本不用管它了，就是一个普通的笔记本而已。永远可以相信，适合自己的就是最好的。
> 
> 我也尝试过 wolai，notion，还有一些其他的国产笔记软件，虽然他们的功能看上去比较“优雅”，但是使用了一些自己的语法，我担心平台绑定的问题，所以就没有使用。 至于 Typora，目前的我的笔记量比较少，正在培养习惯，所以还算能够满足我的需求，但是听了你的经历感觉 Typora 功能的慢慢可能不够用了。所以还是打算在试试 Obsidian。源码模式的编辑器真的很容易写错语法，并且我觉得表格编辑真的痛苦。

是的，Table肯定不能用语法写，所以需要ob花好几天的时间上手学习，需要了解他的插件生态，插件几乎可以实现一切你想要的。
 给个目前我可以打90分的表格编辑组合用法：
第一步： 激活：核心插件 -> 打开斜杠指令
第二步： 安装： 插件 Table Enhancr 和 Table Generator (一个是创建方便，一个是编辑方便) 所以这两个必装
第三步： 使用：/tb 回车-> 选择行列 创建 即可 

（冷知识：ob不是靠会员订阅盈利，而是靠卖ob课~ 真的好佩服国外的盈利模式，很多人都愿意为知识付费，替我们使用软件的人 “负重”）

**Comment by CafeBabe202** [comment]
> > > > > 嗯 是的，我也是更新了版本才出现的，开发者确实得跟进最新版本适配情况，试过几款主题没有更新也不会出现这种不兼容情况。可能还是因为border主题的功能太丰富原因，"双刃剑"。 希望开发者可以尽快修复，毕竟现在的问题还挺**致命**，很多页面无法移动光标都只能开源码模式编辑，只能先用别的主题缓解一下。
> > > > 
> > > > 
> > > > 也就说旧版的没有问题吗？我现在用的是 typora，虽然非常优雅且稳定，但是功能的确不如 obsidian 丰富，习惯了所见即所得用不习惯源码模式。我开始尝试适应 obsidian，border 是我唯一觉得可以开箱即用并且比较好看的主题，但是这个的确是一个比较大的问题，所以还是放弃了，换回了 typora。
> > > 
> > > 
> > > 嗯 退几个版本应该没问题。 我以前也用 typora，后来用wolai,notion构建了自己的知识库，养成了日常记笔记的习惯。 当你发现你的知识库越来越庞大的时候，你就发现查询的效率至关重要，这样会积累你使用笔记的信心，而不是为了记而记，就会形成一个正循环。后面从在线转为本地的原因还是怕以后迁移成本过大，和软件绑死了，排版格式也会出现不兼容。
> > > ob搭建真的太费精力了，因为初期就是“毛坯房”，而且还得自己去摸索一种记录风格，才能真正提升效率。但当成型后，后期基本不用管它了，就是一个普通的笔记本而已。永远可以相信，适合自己的就是最好的。
> > 
> > 
> > 我也尝试过 wolai，notion，还有一些其他的国产笔记软件，虽然他们的功能看上去比较“优雅”，但是使用了一些自己的语法，我担心平台绑定的问题，所以就没有使用。 至于 Typora，目前的我的笔记量比较少，正在培养习惯，所以还算能够满足我的需求，但是听了你的经历感觉 Typora 功能的慢慢可能不够用了。所以还是打算在试试 Obsidian。源码模式的编辑器真的很容易写错语法，并且我觉得表格编辑真的痛苦。
> 
> 是的，Table肯定不能用语法写，所以使用ob需要花好几天的时间上手学习，需要了解他的插件生态，插件几乎可以实现一切你想要的。 给个目前我可以打90分的表格编辑组合用法： 第一步： 激活：核心插件 -> 打开斜杠指令 第二步： 安装： 插件 Table Enhancr 和 Table Generator (一个是创建方便，一个是编辑方便) 所以这两个必装 第三步： 使用：/tb 回车-> 选择行列 创建 即可
> 
> （冷知识：ob不是靠会员订阅盈利，而是靠卖ob课~ 真的好佩服国外的盈利模式，很多人都愿意为知识付费，替我们使用软件的人 “负重”）

非常感谢你的分享，我开始一直以为 Obsidian 是开源的，后来才知道是商业产品。我觉得 Obsidian 把太多重要的功能交给了插件社区，但是插件社区的质量很难得到控制，所以小问题比较多。我觉得要是官方能够出一些必要插件，社区只是锦上添花就最好了。
关于 Typora，不知道以后会不会出插件的功能，我举得如果想做知识库，并退出插件功能，可能会超过 Obsidian。

**Comment by Akifyss** [comment]
感谢报告问题，新版尝试修复了，可以更新看看有没有问题

**Comment by itangqiao** [comment]
> 



> > > > > > 嗯 是的，我也是更新了版本才出现的，开发者确实得跟进最新版本适配情况，试过几款主题没有更新也不会出现这种不兼容情况。可能还是因为border主题的功能太丰富原因，"双刃剑"。 希望开发者可以尽快修复，毕竟现在的问题还挺**致命**，很多页面无法移动光标都只能开源码模式编辑，只能先用别的主题缓解一下。
> > > > > 
> > > > > 
> > > > > 也就说旧版的没有问题吗？我现在用的是 typora，虽然非常优雅且稳定，但是功能的确不如 obsidian 丰富，习惯了所见即所得用不习惯源码模式。我开始尝试适应 obsidian，border 是我唯一觉得可以开箱即用并且比较好看的主题，但是这个的确是一个比较大的问题，所以还是放弃了，换回了 typora。
> > > > 
> > > > 
> > > > 嗯 退几个版本应该没问题。 我以前也用 typora，后来用wolai,notion构建了自己的知识库，养成了日常记笔记的习惯。 当你发现你的知识库越来越庞大的时候，你就发现查询的效率至关重要，这样会积累你使用笔记的信心，而不是为了记而记，就会形成一个正循环。后面从在线转为本地的原因还是怕以后迁移成本过大，和软件绑死了，排版格式也会出现不兼容。
> > > > ob搭建真的太费精力了，因为初期就是“毛坯房”，而且还得自己去摸索一种记录风格，才能真正提升效率。但当成型后，后期基本不用管它了，就是一个普通的笔记本而已。永远可以相信，适合自己的就是最好的。
> > > 
> > > 
> > > 我也尝试过 wolai，notion，还有一些其他的国产笔记软件，虽然他们的功能看上去比较“优雅”，但是使用了一些自己的语法，我担心平台绑定的问题，所以就没有使用。 至于 Typora，目前的我的笔记量比较少，正在培养习惯，所以还算能够满足我的需求，但是听了你的经历感觉 Typora 功能的慢慢可能不够用了。所以还是打算在试试 Obsidian。源码模式的编辑器真的很容易写错语法，并且我觉得表格编辑真的痛苦。
> > 
> > 
> > 是的，Table肯定不能用语法写，所以使用ob需要花好几天的时间上手学习，需要了解他的插件生态，插件几乎可以实现一切你想要的。 给个目前我可以打90分的表格编辑组合用法： 第一步： 激活：核心插件 -> 打开斜杠指令 第二步： 安装： 插件 Table Enhancr 和 Table Generator (一个是创建方便，一个是编辑方便) 所以这两个必装 第三步： 使用：/tb 回车-> 选择行列 创建 即可
> > （冷知识：ob不是靠会员订阅盈利，而是靠卖ob课~ 真的好佩服国外的盈利模式，很多人都愿意为知识付费，替我们使用软件的人 “负重”）
> 
> 非常感谢你的分享，我开始一直以为 Obsidian 是开源的，后来才知道是商业产品。我觉得 Obsidian 把太多重要的功能交给了插件社区，但是插件社区的质量很难得到控制，所以小问题比较多。我觉得要是官方能够出一些必要插件，社区只是锦上添花就最好了。 关于 Typora，不知道以后会不会出插件的功能，我举得如果想做知识库，并退出插件功能，可能会超过 Obsidian。

完全是不可能的，Typora诞生很久了，而且它找准了自己的定位，就是稳定，轻量，简洁友好，易用。读写md软件太多了，几乎每天都可以复制一个出来，功能都比Typora多，但是活下来的极少。对于我来说现在Typora只是作为预览和阅读工具。

对于官方来说，开发插件的收益太低了，只能做付费插件，但官方还是逐渐加入了新的核心插件。重口难调，社区推动力一直都是很强的，如果不满足还可以自己来。比如 官方现在都没出延迟加载不重要的插件，一次性开启几十个插件 对于移动端压力还挺大的，所以自己找应对方案，还好有现成的脚本。

以前我总想着all in one，相信很多人都喜欢这样。 后来我发现我错了，当你折腾的东西越来越多时，会发现打造all in one真的很浪费时间，而且你不可能既要又要吧？

专业的工具做做专业的事。  - 这可能只属于我自己的心得，仅作为参考哈~

**Comment by itangqiao** [comment]
> 



> 感谢报告问题，新版尝试修复了，可以更新看看有没有问题

暂时没有复现了，辛苦辛苦~ ☕️

**Comment by CafeBabe202** [comment]
> 感谢报告问题，新版尝试修复了，可以更新看看有没有问题

非常感谢你的修复，还有两个其他的小问题，在嵌套的引用块中添加横线（---）会出现不对齐和割裂的问题，如图：

**编辑模式**

![2023-08-04 09-29-13屏幕截图](https://github.com/Akifyss/obsidian-border/assets/53887690/2e401aaf-4aba-460d-9116-70b356487466)

**预览模式**

![2023-08-04 09-28-44屏幕截图](https://github.com/Akifyss/obsidian-border/assets/53887690/d9307728-7386-44ee-adbb-c5107ceefdc9)

希望能够得到解决，谢谢

**Comment by CafeBabe202** [comment]
> > 
> 
> > > > > > > 嗯 是的，我也是更新了版本才出现的，开发者确实得跟进最新版本适配情况，试过几款主题没有更新也不会出现这种不兼容情况。可能还是因为border主题的功能太丰富原因，"双刃剑"。 希望开发者可以尽快修复，毕竟现在的问题还挺**致命**，很多页面无法移动光标都只能开源码模式编辑，只能先用别的主题缓解一下。
> > > > > > 
> > > > > > 
> > > > > > 也就说旧版的没有问题吗？我现在用的是 typora，虽然非常优雅且稳定，但是功能的确不如 obsidian 丰富，习惯了所见即所得用不习惯源码模式。我开始尝试适应 obsidian，border 是我唯一觉得可以开箱即用并且比较好看的主题，但是这个的确是一个比较大的问题，所以还是放弃了，换回了 typora。
> > > > > 
> > > > > 
> > > > > 嗯 退几个版本应该没问题。 我以前也用 typora，后来用wolai,notion构建了自己的知识库，养成了日常记笔记的习惯。 当你发现你的知识库越来越庞大的时候，你就发现查询的效率至关重要，这样会积累你使用笔记的信心，而不是为了记而记，就会形成一个正循环。后面从在线转为本地的原因还是怕以后迁移成本过大，和软件绑死了，排版格式也会出现不兼容。
> > > > > ob搭建真的太费精力了，因为初期就是“毛坯房”，而且还得自己去摸索一种记录风格，才能真正提升效率。但当成型后，后期基本不用管它了，就是一个普通的笔记本而已。永远可以相信，适合自己的就是最好的。
> > > > 
> > > > 
> > > > 我也尝试过 wolai，notion，还有一些其他的国产笔记软件，虽然他们的功能看上去比较“优雅”，但是使用了一些自己的语法，我担心平台绑定的问题，所以就没有使用。 至于 Typora，目前的我的笔记量比较少，正在培养习惯，所以还算能够满足我的需求，但是听了你的经历感觉 Typora 功能的慢慢可能不够用了。所以还是打算在试试 Obsidian。源码模式的编辑器真的很容易写错语法，并且我觉得表格编辑真的痛苦。
> > > 
> > > 
> > > 是的，Table肯定不能用语法写，所以使用ob需要花好几天的时间上手学习，需要了解他的插件生态，插件几乎可以实现一切你想要的。 给个目前我可以打90分的表格编辑组合用法： 第一步： 激活：核心插件 -> 打开斜杠指令 第二步： 安装： 插件 Table Enhancr 和 Table Generator (一个是创建方便，一个是编辑方便) 所以这两个必装 第三步： 使用：/tb 回车-> 选择行列 创建 即可
> > > （冷知识：ob不是靠会员订阅盈利，而是靠卖ob课~ 真的好佩服国外的盈利模式，很多人都愿意为知识付费，替我们使用软件的人 “负重”）
> > 
> > 
> > 非常感谢你的分享，我开始一直以为 Obsidian 是开源的，后来才知道是商业产品。我觉得 Obsidian 把太多重要的功能交给了插件社区，但是插件社区的质量很难得到控制，所以小问题比较多。我觉得要是官方能够出一些必要插件，社区只是锦上添花就最好了。 关于 Typora，不知道以后会不会出插件的功能，我举得如果想做知识库，并退出插件功能，可能会超过 Obsidian。
> 
> 完全是不可能的，Typora诞生很久了，而且它找准了自己的定位，就是稳定，轻量，简洁友好，易用。读写md软件太多了，几乎每天都可以复制一个出来，功能都比Typora多，但是活下来的极少。对于我来说现在Typora只是作为预览和阅读工具。
> 
> 对于官方来说，开发插件的收益太低了，只能做付费插件，但官方还是逐渐加入了新的核心插件。重口难调，社区推动力一直都是很强的，如果不满足还可以自己来。比如 官方现在都没出延迟加载不重要的插件，一次性开启几十个插件 对于移动端压力还挺大的，所以自己找应对方案，还好有现成的脚本。
> 
> 以前我总想着all in one，相信很多人都喜欢这样。 后来我发现我错了，当你折腾的东西越来越多时，会发现打造all in one真的很浪费时间，而且你不可能既要又要吧？
> 
> 专业的工具做做专业的事。 - 这可能只属于我自己的心得，仅作为参考哈~

Typora 的定位可能就是轻量便捷的编辑器，而不是知识库软件吧，如果只是单纯的码字我觉得它是最好的，但是如果作为知识库，还是不够的。

官方插件的收益的确比较低，并且正口难条也是问题。但是我觉得插件就是用来解决中口难调这个问题的，不喜欢的人可以不装嘛。

all in one 是很难做到的，但是我想大多数人都喜欢开箱即用。

**Comment by Akifyss** [comment]
这个应该不是主题的问题，刚刚试了下，默认主题也是这个样子的，可以考虑给obsidian官方反馈一下：
<img width="207" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/23567154/2d687d9c-d054-42ce-b54d-fb11cc136b8e">

**Comment by CafeBabe202** [comment]
> 这个应该不是主题的问题，刚刚试了下，默认主题也是这个样子的，可以考虑给obsidian官方反馈一下： <img alt="image" width="207" src="https://user-images.githubusercontent.com/23567154/258274027-2d687d9c-d054-42ce-b54d-fb11cc136b8e.png">

好的，谢谢
