### ISSUE TITLE
Hello! This theme is great!

### ISSUE THREAD

**Issue by zhouxinghong** [Akifyss/obsidian-border#94]
Hello! This theme is great!
This theme is great! But the running performance is very low, because every time the theme is enabled, Obsidian will be obviously stuck and the operation will not be smooth. Hope to greatly improve the performance. Thank you so much for your excellent themes! 👍
Windows10
The latest version of the theme

**Comment by Akifyss** [comment]
Thank you for the kind words. To improve the theme's performance, I'll need to troubleshoot its lag issues. As I'm not a professional front-end developer, this process might take some time, and I can't guarantee substantial results. I apologize for any inconvenience.

For now you can try the following measures to see if you can improve performance:

+ Reinstall Obsidian to upgrade the installer version.
+ Make sure hardware acceleration is enabled. 
+ Remove extra animation: 
+ Disable hover line indicator
+ Disable Card layout & Auto-hide
