### ISSUE TITLE
Bookmarks / File Manager Consistancy

### ISSUE THREAD

**Issue by Aeases** [Akifyss/obsidian-border#95]
Not sure if this is more feature request or bug, though;

The settings for the file manager selection style (mine is set in style settings) is not consistent with the bookmarks section despite them both having a very similar layout, see;

Files           |  Bookmarks
:-------------------------:|:-------------------------:
![](https://github.com/Akifyss/obsidian-border/assets/96164686/771a2595-d215-423a-81a0-6d130cc562a7)  |  ![](https://github.com/Akifyss/obsidian-border/assets/96164686/3994b05c-bf53-4cf8-aac4-061604fb036a)

Amazing theme btw, me & my mates literally cant find anything that compares to border dark, everything else feels, & looks inferior.

**Comment by Akifyss** [comment]
Thank you for your feedback. This issue will be addressed and improved in the next update.

**Comment by Akifyss** [comment]
The new version has been released, you can have a try
