### ISSUE TITLE
Supercharged Links Support

### ISSUE THREAD

**Issue by oyes77** [Akifyss/obsidian-border#96]
The supercharged Links plugin isn't fully supported, It has a feature of preppend text, I use it to add emojis before notes, this is with Border theme:

![image](https://github.com/Akifyss/obsidian-border/assets/53545025/429b619a-8d7b-4ee2-89d3-37ea57cbbc75)

this is with Default obsidian:

![image](https://github.com/Akifyss/obsidian-border/assets/53545025/6bbe92cc-090c-4ea6-958b-7465002cef2f)

I suppose it's due to the custom Icon you apply to notes (?, however even disabling it like I did, doesn't help much...

**Comment by Akifyss** [comment]
Supercharged links are supported in the new version, you can have a try.

**Comment by sammosna** [comment]
Would it be possible to ensure that if a file has a Supercharged Links icon, the default icon is not visible?

<img width="300" alt="image" src="https://github.com/Akifyss/obsidian-border/assets/6976083/963e03e2-b418-497c-8c82-70b0293458aa">

**Comment by oyes77** [comment]
I just disable it manually, not too much of a hassle but it would be great, not a big priority though.
