### ISSUE TITLE
Request: AutoHide CSS snippet

### ISSUE THREAD

**Issue by oyes77** [Akifyss/obsidian-border#97]
I'm not proefficient in CSS, I tried to put what seemed to be the feature in the theme to autohide stuff, to use it with other themes or default obsidian theme, but I wasn't able to t.t

![image](https://github.com/Akifyss/obsidian-border/assets/53545025/b89cbe4b-fd13-457c-9186-21b7990635be)

If someone knows or have that snippet i'm grateful nwn, It's a really great feature!

**Comment by Akifyss** [comment]
Hello, unfortunately, the code for the auto-hide feature may be intertwined with other layout-related code, making it difficult for me to distinguish them properly. I am sorry for not being able to assist you.
